package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class Aenyr extends ExpansionSet {
    private static final Aenyr instance = new Aenyr();

    public static Aenyr getInstance() { return instance; }

    private Aenyr() {
        super("Aenyr", "AYR", ExpansionSet.buildDate(2016, 12, 8), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Aerial Grace", 1, Rarity.UNCOMMON, mage.cards.a.AerialGrace.class));
        //cards.add(new SetCardInfo("Alone in the World", 2, Rarity.RARE, mage.cards.a.AloneInTheWorld.class));
        //cards.add(new SetCardInfo("Aven Acrobat", 3, Rarity.COMMON, mage.cards.a.AvenAcrobat.class));
        //cards.add(new SetCardInfo("Daring Strike", 4, Rarity.COMMON, mage.cards.d.DaringStrike.class));
        //cards.add(new SetCardInfo("Dashing Swordsman", 5, Rarity.COMMON, mage.cards.d.DashingSwordsman.class));
        //cards.add(new SetCardInfo("Delsanian Sellsword", 6, Rarity.COMMON, mage.cards.d.DelsanianSellsword.class));
        //cards.add(new SetCardInfo("Dutiful Patrollers", 7, Rarity.COMMON, mage.cards.d.DutifulPatrollers.class));
        //cards.add(new SetCardInfo("Eerie Harpist", 8, Rarity.UNCOMMON, mage.cards.e.EerieHarpist.class));
        //cards.add(new SetCardInfo("Evanescing Chord", 9, Rarity.COMMON, mage.cards.e.EvanescingChord.class));
        //cards.add(new SetCardInfo("Inspiring March", 10, Rarity.COMMON, mage.cards.i.InspiringMarch.class));
        //cards.add(new SetCardInfo("Lifesong Flutist", 11, Rarity.COMMON, mage.cards.l.LifesongFlutist.class));
        //cards.add(new SetCardInfo("Master Stoneshaper", 12, Rarity.UNCOMMON, mage.cards.m.MasterStoneshaper.class));
        //cards.add(new SetCardInfo("Mystical Minstrel", 13, Rarity.UNCOMMON, mage.cards.m.MysticalMinstrel.class));
        //cards.add(new SetCardInfo("Peaceful Thoughts", 14, Rarity.UNCOMMON, mage.cards.p.PeacefulThoughts.class));
        //cards.add(new SetCardInfo("Prismatic Harmony", 15, Rarity.UNCOMMON, mage.cards.p.PrismaticHarmony.class));
        //cards.add(new SetCardInfo("Quell Eloquence", 16, Rarity.COMMON, mage.cards.q.QuellEloquence.class));
        //cards.add(new SetCardInfo("Seasoned Dancer", 17, Rarity.COMMON, mage.cards.s.SeasonedDancer.class));
        //cards.add(new SetCardInfo("Silkfinder Ranger", 18, Rarity.COMMON, mage.cards.s.SilkfinderRanger.class));
        //cards.add(new SetCardInfo("Skylyre Archangel", 19, Rarity.RARE, mage.cards.s.SkylyreArchangel.class));
        //cards.add(new SetCardInfo("Sunblessed Dancer", 20, Rarity.UNCOMMON, mage.cards.s.SunblessedDancer.class));
        //cards.add(new SetCardInfo("Vengeful Apparitions", 21, Rarity.COMMON, mage.cards.v.VengefulApparitions.class));
        //cards.add(new SetCardInfo("Young Dreamer", 22, Rarity.COMMON, mage.cards.y.YoungDreamer.class));
        //cards.add(new SetCardInfo("Aven Vocalist", 23, Rarity.COMMON, mage.cards.a.AvenVocalist.class));
        //cards.add(new SetCardInfo("Captivating Performer", 24, Rarity.COMMON, mage.cards.c.CaptivatingPerformer.class));
        //cards.add(new SetCardInfo("Censure", 25, Rarity.UNCOMMON, mage.cards.c.Censure.class));
        //cards.add(new SetCardInfo("Deep-Sea Dreamhunter", 26, Rarity.COMMON, mage.cards.d.DeepSeaDreamhunter.class));
        //cards.add(new SetCardInfo("Diminuendo", 27, Rarity.UNCOMMON, mage.cards.d.Diminuendo.class));
        //cards.add(new SetCardInfo("Dreamborn Vision", 28, Rarity.COMMON, mage.cards.d.DreambornVision.class));
        //cards.add(new SetCardInfo("Dreamsilk Infiltrator", 29, Rarity.UNCOMMON, mage.cards.d.DreamsilkInfiltrator.class));
        //cards.add(new SetCardInfo("Ethereal Chord", 30, Rarity.COMMON, mage.cards.e.EtherealChord.class));
        //cards.add(new SetCardInfo("Fade into Nothingness", 31, Rarity.COMMON, mage.cards.f.FadeIntoNothingness.class));
        //cards.add(new SetCardInfo("Fruitful Rest", 32, Rarity.UNCOMMON, mage.cards.f.FruitfulRest.class));
        //cards.add(new SetCardInfo("Gliding Mantas", 33, Rarity.COMMON, mage.cards.g.GlidingMantas.class));
        //cards.add(new SetCardInfo("Hat Trick", 34, Rarity.COMMON, mage.cards.h.HatTrick.class));
        //cards.add(new SetCardInfo("Keeper of Secret Texts", 35, Rarity.UNCOMMON, mage.cards.k.KeeperOfSecretTexts.class));
        //cards.add(new SetCardInfo("Kirsus Hypnotist", 36, Rarity.COMMON, mage.cards.k.KirsusHypnotist.class));
        //cards.add(new SetCardInfo("Mindscraper", 37, Rarity.COMMON, mage.cards.m.Mindscraper.class));
        //cards.add(new SetCardInfo("Refute", 38, Rarity.COMMON, mage.cards.r.Refute.class));
        //cards.add(new SetCardInfo("Serenade of the Mists", 39, Rarity.UNCOMMON, mage.cards.s.SerenadeOfTheMists.class));
        //cards.add(new SetCardInfo("The Show Must Go On", 40, Rarity.COMMON, mage.cards.t.TheShowMustGoOn.class));
        //cards.add(new SetCardInfo("Silent Riddler", 41, Rarity.RARE, mage.cards.s.SilentRiddler.class));
        //cards.add(new SetCardInfo("Skyseeker", 42, Rarity.UNCOMMON, mage.cards.s.Skyseeker.class));
        //cards.add(new SetCardInfo("Sonata of Somnolence", 43, Rarity.COMMON, mage.cards.s.SonataOfSomnolence.class));
        //cards.add(new SetCardInfo("Symphonic Harmony", 44, Rarity.RARE, mage.cards.s.SymphonicHarmony.class));
        //cards.add(new SetCardInfo("Ashiok's Phantasm", 45, Rarity.COMMON, mage.cards.a.AshioksPhantasm.class));
        //cards.add(new SetCardInfo("Back Alley Crook", 46, Rarity.UNCOMMON, mage.cards.b.BackAlleyCrook.class));
        //cards.add(new SetCardInfo("Beneath the Mask", 47, Rarity.COMMON, mage.cards.b.BeneathTheMask.class));
        //cards.add(new SetCardInfo("Bequeathment", 48, Rarity.COMMON, mage.cards.b.Bequeathment.class));
        cards.add(new SetCardInfo("Blood Artist", 49, Rarity.UNCOMMON, mage.cards.b.BloodArtist.class));
        //cards.add(new SetCardInfo("Blood Pact", 50, Rarity.RARE, mage.cards.b.BloodPact.class));
        //cards.add(new SetCardInfo("Brumewing", 51, Rarity.UNCOMMON, mage.cards.b.Brumewing.class));
        //cards.add(new SetCardInfo("Chant of the Damned", 52, Rarity.UNCOMMON, mage.cards.c.ChantOfTheDamned.class));
        //cards.add(new SetCardInfo("Chorus of the Unliving", 53, Rarity.RARE, mage.cards.c.ChorusOfTheUnliving.class));
        //cards.add(new SetCardInfo("Danse Macabre", 54, Rarity.UNCOMMON, mage.cards.d.DanseMacabre.class));
        //cards.add(new SetCardInfo("Deathcaller Oracle", 55, Rarity.COMMON, mage.cards.d.DeathcallerOracle.class));
        //cards.add(new SetCardInfo("Deepwood Ritual", 56, Rarity.COMMON, mage.cards.d.DeepwoodRitual.class));
        //cards.add(new SetCardInfo("Dreadful Demise", 57, Rarity.COMMON, mage.cards.d.DreadfulDemise.class));
        //cards.add(new SetCardInfo("Dream Drinker", 58, Rarity.COMMON, mage.cards.d.DreamDrinker.class));
        //cards.add(new SetCardInfo("Duskwood Extortionist", 59, Rarity.COMMON, mage.cards.d.DuskwoodExtortionist.class));
        //cards.add(new SetCardInfo("Hymn of the Lost", 60, Rarity.COMMON, mage.cards.h.HymnOfTheLost.class));
        //cards.add(new SetCardInfo("Kenoram Ritualist", 61, Rarity.UNCOMMON, mage.cards.k.KenoramRitualist.class));
        //cards.add(new SetCardInfo("Kirsus Maniac", 62, Rarity.COMMON, mage.cards.k.KirsusManiac.class));
        //cards.add(new SetCardInfo("Minimalism", 63, Rarity.COMMON, mage.cards.m.Minimalism.class));
        //cards.add(new SetCardInfo("Nightmarish Chord", 64, Rarity.COMMON, mage.cards.n.NightmarishChord.class));
        //cards.add(new SetCardInfo("Satyr Brawler", 65, Rarity.COMMON, mage.cards.s.SatyrBrawler.class));
        cards.add(new SetCardInfo("Ultimate Price", 66, Rarity.UNCOMMON, mage.cards.u.UltimatePrice.class));
        //cards.add(new SetCardInfo("Ardent Choreography", 67, Rarity.COMMON, mage.cards.a.ArdentChoreography.class));
        //cards.add(new SetCardInfo("Avenging Mauler", 68, Rarity.COMMON, mage.cards.a.AvengingMauler.class));
        //cards.add(new SetCardInfo("Blazing Sonnet", 69, Rarity.COMMON, mage.cards.b.BlazingSonnet.class));
        //cards.add(new SetCardInfo("Chaotic Clarity", 70, Rarity.UNCOMMON, mage.cards.c.ChaoticClarity.class));
        //cards.add(new SetCardInfo("Deafening Ballad", 71, Rarity.COMMON, mage.cards.d.DeafeningBallad.class));
        //cards.add(new SetCardInfo("Fervent Balladeer", 72, Rarity.COMMON, mage.cards.f.FerventBalladeer.class));
        //cards.add(new SetCardInfo("Fiery Bolero", 73, Rarity.UNCOMMON, mage.cards.f.FieryBolero.class));
        //cards.add(new SetCardInfo("Flamedance Prodigy", 74, Rarity.COMMON, mage.cards.f.FlamedanceProdigy.class));
        //cards.add(new SetCardInfo("Goblin Chef", 75, Rarity.UNCOMMON, mage.cards.g.GoblinChef.class));
        //cards.add(new SetCardInfo("Goblin Ukulelist", 76, Rarity.COMMON, mage.cards.g.GoblinUkulelist.class));
        //cards.add(new SetCardInfo("High Road Bandit", 77, Rarity.COMMON, mage.cards.h.HighRoadBandit.class));
        //cards.add(new SetCardInfo("Inner Flame", 78, Rarity.COMMON, mage.cards.i.InnerFlame.class));
        cards.add(new SetCardInfo("Kirsus Mongrel", 79, Rarity.COMMON, mage.cards.k.KirsusMongrel.class));
        //cards.add(new SetCardInfo("Master Flamedancer", 80, Rarity.RARE, mage.cards.m.MasterFlamedancer.class));
        //cards.add(new SetCardInfo("Moltenheart Elemental", 81, Rarity.COMMON, mage.cards.m.MoltenheartElemental.class));
        //cards.add(new SetCardInfo("Parch the Mind", 82, Rarity.UNCOMMON, mage.cards.p.ParchTheMind.class));
        //cards.add(new SetCardInfo("Passionate Anthem", 83, Rarity.UNCOMMON, mage.cards.p.PassionateAnthem.class));
        //cards.add(new SetCardInfo("Piercing Shout", 84, Rarity.COMMON, mage.cards.p.PiercingShout.class));
        //cards.add(new SetCardInfo("Ragesmith", 85, Rarity.UNCOMMON, mage.cards.r.Ragesmith.class));
        //cards.add(new SetCardInfo("Roselyn Valvidia", 86, Rarity.MYTHIC, mage.cards.r.RoselynValvidia.class));
        //cards.add(new SetCardInfo("Sparkling Chord", 87, Rarity.COMMON, mage.cards.s.SparklingChord.class));
        //cards.add(new SetCardInfo("Starsong Dragon", 88, Rarity.RARE, mage.cards.s.StarsongDragon.class));
        //cards.add(new SetCardInfo("Torch Juggler", 89, Rarity.UNCOMMON, mage.cards.t.TorchJuggler.class));
        //cards.add(new SetCardInfo("Arachnoid Ambush", 90, Rarity.UNCOMMON, mage.cards.a.ArachnoidAmbush.class));
        //cards.add(new SetCardInfo("Aria of the Spider", 91, Rarity.COMMON, mage.cards.a.AriaOfTheSpider.class));
        //cards.add(new SetCardInfo("Ashanid the Dreamweaver", 92, Rarity.RARE, mage.cards.a.AshanidTheDreamweaver.class));
        //cards.add(new SetCardInfo("Awakening Melody", 93, Rarity.UNCOMMON, mage.cards.a.AwakeningMelody.class));
        //cards.add(new SetCardInfo("Chromesthesia", 94, Rarity.UNCOMMON, mage.cards.c.Chromesthesia.class));
        //cards.add(new SetCardInfo("Contemplative Ancient", 95, Rarity.COMMON, mage.cards.c.ContemplativeAncient.class));
        //cards.add(new SetCardInfo("Dreamborn Wurm", 96, Rarity.COMMON, mage.cards.d.DreambornWurm.class));
        //cards.add(new SetCardInfo("Duskwood Neophyte", 97, Rarity.UNCOMMON, mage.cards.d.DuskwoodNeophyte.class));
        //cards.add(new SetCardInfo("Flourishing Chord", 98, Rarity.COMMON, mage.cards.f.FlourishingChord.class));
        //cards.add(new SetCardInfo("Kenoram Mythmaker", 99, Rarity.UNCOMMON, mage.cards.k.KenoramMythmaker.class));
        //cards.add(new SetCardInfo("Kenoram Stalker", 100, Rarity.COMMON, mage.cards.k.KenoramStalker.class));
        //cards.add(new SetCardInfo("Lone Poet", 101, Rarity.COMMON, mage.cards.l.LonePoet.class));
        //cards.add(new SetCardInfo("Parade Mastodon", 102, Rarity.COMMON, mage.cards.p.ParadeMastodon.class));
        //cards.add(new SetCardInfo("Primal Drummer", 103, Rarity.RARE, mage.cards.p.PrimalDrummer.class));
        //cards.add(new SetCardInfo("Primeval Serenity", 104, Rarity.COMMON, mage.cards.p.PrimevalSerenity.class));
        //cards.add(new SetCardInfo("Prismavore", 105, Rarity.UNCOMMON, mage.cards.p.Prismavore.class));
        cards.add(new SetCardInfo("Satyr Wayfinder", 106, Rarity.COMMON, mage.cards.s.SatyrWayfinder.class));
        //cards.add(new SetCardInfo("Spawn of Ashanid", 107, Rarity.COMMON, mage.cards.s.SpawnOfAshanid.class));
        //cards.add(new SetCardInfo("Surreal Grandeur", 108, Rarity.COMMON, mage.cards.s.SurrealGrandeur.class));
        //cards.add(new SetCardInfo("Tale of the Lone Hunter", 109, Rarity.COMMON, mage.cards.t.TaleOfTheLoneHunter.class));
        //cards.add(new SetCardInfo("Taunting Satyr", 110, Rarity.UNCOMMON, mage.cards.t.TauntingSatyr.class));
        //cards.add(new SetCardInfo("Traveling Minstrel", 111, Rarity.COMMON, mage.cards.t.TravelingMinstrel.class));
        //cards.add(new SetCardInfo("Angelic Mentor", 112, Rarity.MYTHIC, mage.cards.a.AngelicMentor.class));
        //cards.add(new SetCardInfo("Ashdancer", 113, Rarity.MYTHIC, mage.cards.a.Ashdancer.class));
        //cards.add(new SetCardInfo("Ashiok, Harbinger of Fear", 114, Rarity.MYTHIC, mage.cards.a.AshiokHarbingerOfFear.class));
        //cards.add(new SetCardInfo("Aven Blade-Dancer", 115, Rarity.UNCOMMON, mage.cards.a.AvenBladeDancer.class));
        //cards.add(new SetCardInfo("Aven Conductor", 116, Rarity.COMMON, mage.cards.a.AvenConductor.class));
        //cards.add(new SetCardInfo("Blazeheart Idealon", 117, Rarity.COMMON, mage.cards.b.BlazeheartIdealon.class));
        //cards.add(new SetCardInfo("Book Worm", 118, Rarity.UNCOMMON, mage.cards.b.BookWorm.class));
        //cards.add(new SetCardInfo("Chaosborn Muse", 119, Rarity.RARE, mage.cards.c.ChaosbornMuse.class));
        //cards.add(new SetCardInfo("Chimerical Visitant", 120, Rarity.UNCOMMON, mage.cards.c.ChimericalVisitant.class));
        //cards.add(new SetCardInfo("Chromaborn Muse", 121, Rarity.RARE, mage.cards.c.ChromabornMuse.class));
        //cards.add(new SetCardInfo("Chromawing Idealon", 122, Rarity.COMMON, mage.cards.c.ChromawingIdealon.class));
        //cards.add(new SetCardInfo("Creativity", 123, Rarity.MYTHIC, mage.cards.c.Creativity.class));
        //cards.add(new SetCardInfo("Delsanian Aristocrat", 124, Rarity.UNCOMMON, mage.cards.d.DelsanianAristocrat.class));
        //cards.add(new SetCardInfo("Dreams from Beyond", 125, Rarity.UNCOMMON, mage.cards.d.DreamsFromBeyond.class));
        //cards.add(new SetCardInfo("Duskborn Muse", 126, Rarity.RARE, mage.cards.d.DuskbornMuse.class));
        //cards.add(new SetCardInfo("Echoborn Muse", 127, Rarity.RARE, mage.cards.e.EchobornMuse.class));
        //cards.add(new SetCardInfo("Effervescent Idealon", 128, Rarity.RARE, mage.cards.e.EffervescentIdealon.class));
        //cards.add(new SetCardInfo("Eidolic Waltz", 129, Rarity.RARE, mage.cards.e.EidolicWaltz.class));
        //cards.add(new SetCardInfo("Entry Fee", 130, Rarity.UNCOMMON, mage.cards.e.EntryFee.class));
        //cards.add(new SetCardInfo("Eraser of Thoughts", 131, Rarity.MYTHIC, mage.cards.e.EraserOfThoughts.class));
        //cards.add(new SetCardInfo("Eregon's Masterpiece", 132, Rarity.MYTHIC, mage.cards.e.EregonsMasterpiece.class));
        //cards.add(new SetCardInfo("Exquisite Idealon", 133, Rarity.RARE, mage.cards.e.ExquisiteIdealon.class));
        //cards.add(new SetCardInfo("Facestealer", 134, Rarity.RARE, mage.cards.f.Facestealer.class));
        //cards.add(new SetCardInfo("Fantasia Wyrm", 135, Rarity.UNCOMMON, mage.cards.f.FantasiaWyrm.class));
        //cards.add(new SetCardInfo("Fearless Feline", 136, Rarity.UNCOMMON, mage.cards.f.FearlessFeline.class));
        //cards.add(new SetCardInfo("Gloom Tender", 137, Rarity.MYTHIC, mage.cards.g.GloomTender.class));
        //cards.add(new SetCardInfo("Graceborn Muse", 138, Rarity.RARE, mage.cards.g.GracebornMuse.class));
        //cards.add(new SetCardInfo("Grasp of Nature", 139, Rarity.RARE, mage.cards.g.GraspOfNature.class));
        //cards.add(new SetCardInfo("Harmonious Prosperity", 140, Rarity.UNCOMMON, mage.cards.h.HarmoniousProsperity.class));
        //cards.add(new SetCardInfo("Hellish Idealon", 141, Rarity.UNCOMMON, mage.cards.h.HellishIdealon.class));
        //cards.add(new SetCardInfo("Highborn Muse", 142, Rarity.RARE, mage.cards.h.HighbornMuse.class));
        //cards.add(new SetCardInfo("Infernal Cacophony", 143, Rarity.RARE, mage.cards.i.InfernalCacophony.class));
        //cards.add(new SetCardInfo("Intrepid Poet", 144, Rarity.UNCOMMON, mage.cards.i.IntrepidPoet.class));
        //cards.add(new SetCardInfo("Journey Inward", 145, Rarity.UNCOMMON, mage.cards.j.JourneyInward.class));
        //cards.add(new SetCardInfo("Keeper of the Cycle", 146, Rarity.UNCOMMON, mage.cards.k.KeeperOfTheCycle.class));
        //cards.add(new SetCardInfo("Kenoram Scavenger", 147, Rarity.COMMON, mage.cards.k.KenoramScavenger.class));
        //cards.add(new SetCardInfo("Lifelike Canvas", 148, Rarity.RARE, mage.cards.l.LifelikeCanvas.class));
        //cards.add(new SetCardInfo("Lost in Eternity", 149, Rarity.MYTHIC, mage.cards.l.LostInEternity.class));
        //cards.add(new SetCardInfo("Lyrehorn Runehart", 150, Rarity.RARE, mage.cards.l.LyrehornRunehart.class));
        cards.add(new SetCardInfo("Lyss, Duskwood Seer", 151, Rarity.RARE, mage.cards.l.LyssDuskwoodSeer.class));
        //cards.add(new SetCardInfo("Mad Jester", 152, Rarity.COMMON, mage.cards.m.MadJester.class));
        //cards.add(new SetCardInfo("Marionette Show", 153, Rarity.MYTHIC, mage.cards.m.MarionetteShow.class));
        //cards.add(new SetCardInfo("Maskborn Muse", 154, Rarity.RARE, mage.cards.m.MaskbornMuse.class));
        //cards.add(new SetCardInfo("Masquerade Infiltrator", 155, Rarity.UNCOMMON, mage.cards.m.MasqueradeInfiltrator.class));
        //cards.add(new SetCardInfo("Masterly Maneuver", 156, Rarity.RARE, mage.cards.m.MasterlyManeuver.class));
        //cards.add(new SetCardInfo("Mental Transgression", 157, Rarity.RARE, mage.cards.m.MentalTransgression.class));
        //cards.add(new SetCardInfo("Mistwalker Idealon", 158, Rarity.COMMON, mage.cards.m.MistwalkerIdealon.class));
        //cards.add(new SetCardInfo("Moment of Quietude", 159, Rarity.RARE, mage.cards.m.MomentOfQuietude.class));
        //cards.add(new SetCardInfo("Nefarious Noble", 160, Rarity.COMMON, mage.cards.n.NefariousNoble.class));
        //cards.add(new SetCardInfo("Never Forgotten", 161, Rarity.MYTHIC, mage.cards.n.NeverForgotten.class));
        //cards.add(new SetCardInfo("Peek-a-Burn", 162, Rarity.UNCOMMON, mage.cards.p.PeekABurn.class));
        //cards.add(new SetCardInfo("Pensive Songwriter", 163, Rarity.MYTHIC, mage.cards.p.PensiveSongwriter.class));
        //cards.add(new SetCardInfo("Persona Elemental", 164, Rarity.UNCOMMON, mage.cards.p.PersonaElemental.class));
        //cards.add(new SetCardInfo("Persona Shift", 165, Rarity.UNCOMMON, mage.cards.p.PersonaShift.class));
        //cards.add(new SetCardInfo("Pretentious Critic", 166, Rarity.UNCOMMON, mage.cards.p.PretentiousCritic.class));
        //cards.add(new SetCardInfo("Prowling Idealon", 167, Rarity.UNCOMMON, mage.cards.p.ProwlingIdealon.class));
        //cards.add(new SetCardInfo("Psychic Laceration", 168, Rarity.COMMON, mage.cards.p.PsychicLaceration.class));
        //cards.add(new SetCardInfo("Pyrebloom Ritual", 169, Rarity.UNCOMMON, mage.cards.p.PyrebloomRitual.class));
        //cards.add(new SetCardInfo("Reconceptualize", 170, Rarity.UNCOMMON, mage.cards.r.Reconceptualize.class));
        //cards.add(new SetCardInfo("Resentful Giant", 171, Rarity.UNCOMMON, mage.cards.r.ResentfulGiant.class));
        //cards.add(new SetCardInfo("Sanguine Connoisseur", 172, Rarity.RARE, mage.cards.s.SanguineConnoisseur.class));
        //cards.add(new SetCardInfo("Secluded Lumidar", 173, Rarity.UNCOMMON, mage.cards.s.SecludedLumidar.class));
        //cards.add(new SetCardInfo("Seed of Despair", 174, Rarity.UNCOMMON, mage.cards.s.SeedOfDespair.class));
        //cards.add(new SetCardInfo("The Senate of Censures", 175, Rarity.MYTHIC, mage.cards.t.TheSenateOfCensures.class));
        //cards.add(new SetCardInfo("Shepherd of Souls", 176, Rarity.UNCOMMON, mage.cards.s.ShepherdOfSouls.class));
        //cards.add(new SetCardInfo("Skiv, Madcap Trickster", 177, Rarity.RARE, mage.cards.s.SkivMadcapTrickster.class));
        //cards.add(new SetCardInfo("Skyguard Challenger", 178, Rarity.RARE, mage.cards.s.SkyguardChallenger.class));
        //cards.add(new SetCardInfo("Soaring Pursuits", 179, Rarity.COMMON, mage.cards.s.SoaringPursuits.class));
        //cards.add(new SetCardInfo("Soul Fracture", 180, Rarity.UNCOMMON, mage.cards.s.SoulFracture.class));
        //cards.add(new SetCardInfo("Sound Blast", 181, Rarity.UNCOMMON, mage.cards.s.SoundBlast.class));
        //cards.add(new SetCardInfo("Steelborn Muse", 182, Rarity.RARE, mage.cards.s.SteelbornMuse.class));
        //cards.add(new SetCardInfo("Tales Retold", 183, Rarity.RARE, mage.cards.t.TalesRetold.class));
        //cards.add(new SetCardInfo("Thought Storm", 184, Rarity.RARE, mage.cards.t.ThoughtStorm.class));
        cards.add(new SetCardInfo("Thundersong Trumpeter", 185, Rarity.COMMON, mage.cards.t.ThundersongTrumpeter.class));
        //cards.add(new SetCardInfo("Torrent of Emotions", 186, Rarity.RARE, mage.cards.t.TorrentOfEmotions.class));
        //cards.add(new SetCardInfo("Tranceborn Muse", 187, Rarity.RARE, mage.cards.t.TrancebornMuse.class));
        //cards.add(new SetCardInfo("Veila Lokan", 188, Rarity.MYTHIC, mage.cards.v.VeilaLokan.class));
        //cards.add(new SetCardInfo("Verseborn Muse", 189, Rarity.RARE, mage.cards.v.VersebornMuse.class));
        //cards.add(new SetCardInfo("Vibrant Hydra", 190, Rarity.RARE, mage.cards.v.VibrantHydra.class));
        //cards.add(new SetCardInfo("Words of Denial", 191, Rarity.UNCOMMON, mage.cards.w.WordsOfDenial.class));
        //cards.add(new SetCardInfo("Worldgorger Idealon", 192, Rarity.RARE, mage.cards.w.WorldgorgerIdealon.class));
        //cards.add(new SetCardInfo("Zealous Duelist", 193, Rarity.UNCOMMON, mage.cards.z.ZealousDuelist.class));
        //cards.add(new SetCardInfo("Austere Familiar", 194, Rarity.UNCOMMON, mage.cards.a.AustereFamiliar.class));
        //cards.add(new SetCardInfo("Bladewhirl", 195, Rarity.COMMON, mage.cards.b.Bladewhirl.class));
        //cards.add(new SetCardInfo("Boon of the Twin Roses", 196, Rarity.COMMON, mage.cards.b.BoonOfTheTwinRoses.class));
        //cards.add(new SetCardInfo("Carnival Sentinel", 197, Rarity.UNCOMMON, mage.cards.c.CarnivalSentinel.class));
        //cards.add(new SetCardInfo("Creative Surge", 198, Rarity.RARE, mage.cards.c.CreativeSurge.class));
        //cards.add(new SetCardInfo("Dancing Master", 199, Rarity.RARE, mage.cards.d.DancingMaster.class));
        //cards.add(new SetCardInfo("Dreamlike Journey", 200, Rarity.UNCOMMON, mage.cards.d.DreamlikeJourney.class));
        //cards.add(new SetCardInfo("Duskwood Shaman", 201, Rarity.RARE, mage.cards.d.DuskwoodShaman.class));
        //cards.add(new SetCardInfo("Fabled Manifestation", 202, Rarity.UNCOMMON, mage.cards.f.FabledManifestation.class));
        //cards.add(new SetCardInfo("Fortune Telling", 203, Rarity.COMMON, mage.cards.f.FortuneTelling.class));
        //cards.add(new SetCardInfo("Ghastly Mural", 204, Rarity.UNCOMMON, mage.cards.g.GhastlyMural.class));
        //cards.add(new SetCardInfo("Grim Revel", 205, Rarity.UNCOMMON, mage.cards.g.GrimRevel.class));
        cards.add(new SetCardInfo("Hand of Skiv", 206, Rarity.COMMON, mage.cards.h.HandOfSkiv.class));
        //cards.add(new SetCardInfo("Impromptu Performance", 207, Rarity.RARE, mage.cards.i.ImpromptuPerformance.class));
        //cards.add(new SetCardInfo("Luck of the Draw", 208, Rarity.RARE, mage.cards.l.LuckOfTheDraw.class));
        //cards.add(new SetCardInfo("Mental Trauma", 209, Rarity.UNCOMMON, mage.cards.m.MentalTrauma.class));
        cards.add(new SetCardInfo("Opera Ghost", 210, Rarity.COMMON, mage.cards.o.OperaGhost.class));
        cards.add(new SetCardInfo("Phantasmal Triad", 211, Rarity.COMMON, mage.cards.p.PhantasmalTriad.class));
        //cards.add(new SetCardInfo("Poisonous Advantage", 212, Rarity.COMMON, mage.cards.p.PoisonousAdvantage.class));
        //cards.add(new SetCardInfo("Radiant Skinmarks", 213, Rarity.UNCOMMON, mage.cards.r.RadiantSkinmarks.class));
        //cards.add(new SetCardInfo("Renegade Fortuneteller", 214, Rarity.RARE, mage.cards.r.RenegadeFortuneteller.class));
        //cards.add(new SetCardInfo("Restless Librarian", 215, Rarity.RARE, mage.cards.r.RestlessLibrarian.class));
        cards.add(new SetCardInfo("Ribbon Whirler", 216, Rarity.UNCOMMON, mage.cards.r.RibbonWhirler.class));
        //cards.add(new SetCardInfo("Search for Inspiration", 217, Rarity.COMMON, mage.cards.s.SearchForInspiration.class));
        //cards.add(new SetCardInfo("Skiv's Regards", 218, Rarity.RARE, mage.cards.s.SkivsRegards.class));
        cards.add(new SetCardInfo("Stoic Bihorn", 219, Rarity.COMMON, mage.cards.s.StoicBihorn.class));
        cards.add(new SetCardInfo("Storytime", 220, Rarity.RARE, mage.cards.s.Storytime.class));
        cards.add(new SetCardInfo("Unfinished Creation", 221, Rarity.COMMON, mage.cards.u.UnfinishedCreation.class));
        //cards.add(new SetCardInfo("Voice of Lost Songs", 222, Rarity.UNCOMMON, mage.cards.v.VoiceOfLostSongs.class));
        //cards.add(new SetCardInfo("Wistful Sonnet", 223, Rarity.RARE, mage.cards.w.WistfulSonnet.class));
        //cards.add(new SetCardInfo("Chromatic Brush", 224, Rarity.UNCOMMON, mage.cards.c.ChromaticBrush.class));
        //cards.add(new SetCardInfo("Elegant Blade", 225, Rarity.UNCOMMON, mage.cards.e.ElegantBlade.class));
        //cards.add(new SetCardInfo("Ensorcelled Instrument", 226, Rarity.COMMON, mage.cards.e.EnsorcelledInstrument.class));
        //cards.add(new SetCardInfo("Ghostlight", 227, Rarity.UNCOMMON, mage.cards.g.Ghostlight.class));
        cards.add(new SetCardInfo("Hulking Creation", 228, Rarity.COMMON, mage.cards.h.HulkingCreation.class));
        cards.add(new SetCardInfo("Jest-In-The-Box", 229, Rarity.COMMON, mage.cards.j.JestInTheBox.class));
        cards.add(new SetCardInfo("Painter's Servant", 230, Rarity.RARE, mage.cards.p.PaintersServant.class));
        //cards.add(new SetCardInfo("Roaming Museum", 231, Rarity.UNCOMMON, mage.cards.r.RoamingMuseum.class));
        //cards.add(new SetCardInfo("Scapeforger Bauble", 232, Rarity.COMMON, mage.cards.s.ScapeforgerBauble.class));
        cards.add(new SetCardInfo("Springleaf Drum", 233, Rarity.COMMON, mage.cards.s.SpringleafDrum.class));
        //cards.add(new SetCardInfo("Strobe Light", 234, Rarity.COMMON, mage.cards.s.StrobeLight.class));
        //cards.add(new SetCardInfo("Tome of Infinity", 235, Rarity.RARE, mage.cards.t.TomeOfInfinity.class));
        //cards.add(new SetCardInfo("Boundless Halls", 236, Rarity.UNCOMMON, mage.cards.b.BoundlessHalls.class));
        cards.add(new SetCardInfo("City of Wonders", 237, Rarity.COMMON, mage.cards.c.CityOfWonders.class));
        cards.add(new SetCardInfo("Deserted Fairgrounds", 238, Rarity.COMMON, mage.cards.d.DesertedFairgrounds.class));
        cards.add(new SetCardInfo("Enlightened Valley", 239, Rarity.COMMON, mage.cards.e.EnlightenedValley.class));
        cards.add(new SetCardInfo("Ethereal Gardens", 240, Rarity.COMMON, mage.cards.e.EtherealGardens.class));
        cards.add(new SetCardInfo("Glamor District", 241, Rarity.COMMON, mage.cards.g.GlamorDistrict.class));
        //cards.add(new SetCardInfo("Heart of Inspiration", 242, Rarity.RARE, mage.cards.h.HeartOfInspiration.class));
        cards.add(new SetCardInfo("Lush Vale", 243, Rarity.COMMON, mage.cards.l.LushVale.class));
        cards.add(new SetCardInfo("Mistfire Ridge", 244, Rarity.COMMON, mage.cards.m.MistfireRidge.class));
        //cards.add(new SetCardInfo("Mount Chromaziel", 245, Rarity.MYTHIC, mage.cards.m.MountChromaziel.class));
        cards.add(new SetCardInfo("Nightmarish Morass", 246, Rarity.COMMON, mage.cards.n.NightmarishMorass.class));
        cards.add(new SetCardInfo("Sunlit Alley", 247, Rarity.COMMON, mage.cards.s.SunlitAlley.class));
        cards.add(new SetCardInfo("Twisted Woodlands", 248, Rarity.COMMON, mage.cards.t.TwistedWoodlands.class));
        //cards.add(new SetCardInfo("Vivid Paradise", 249, Rarity.UNCOMMON, mage.cards.v.VividParadise.class));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class));
        cards.add(new SetCardInfo("Island", 251, Rarity.LAND, mage.cards.basiclands.Island.class));
        cards.add(new SetCardInfo("Swamp", 252, Rarity.LAND, mage.cards.basiclands.Swamp.class));
        cards.add(new SetCardInfo("Mountain", 253, Rarity.LAND, mage.cards.basiclands.Mountain.class));
        cards.add(new SetCardInfo("Forest", 254, Rarity.LAND, mage.cards.basiclands.Forest.class));
    }
}
