package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author EikePeace
 */
public final class Ankheret extends ExpansionSet {
    private static final Ankheret instance = new Ankheret();

    public static Ankheret getInstance() { return instance; }

    private Ankheret() {
        super("Ankheret", "ANK", ExpansionSet.buildDate(2016, 12, 8), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Ainok Vanguard", 1, Rarity.UNCOMMON, mage.cards.a.AinokVanguard.class));
        //cards.add(new SetCardInfo("Atun, God of the Sun", 2, Rarity.MYTHIC, mage.cards.a.AtunGodOfTheSun.class));
        //cards.add(new SetCardInfo("Atun's Steward", 3, Rarity.UNCOMMON, mage.cards.a.AtunsSteward.class));
        cards.add(new SetCardInfo("Bonds of Faith", 4, Rarity.COMMON, mage.cards.b.BondsOfFaith.class));
        //cards.add(new SetCardInfo("Boon Magnification", 5, Rarity.UNCOMMON, mage.cards.b.BoonMagnification.class));
        cards.add(new SetCardInfo("Champion of Ainorek", 6, Rarity.COMMON, mage.cards.c.ChampionOfAinorek.class));
        //cards.add(new SetCardInfo("Divine Revelation", 7, Rarity.UNCOMMON, mage.cards.d.DivineRevelation.class));
        //cards.add(new SetCardInfo("Duality of Purity", 8, Rarity.RARE, mage.cards.d.DualityOfPurity.class));
        //cards.add(new SetCardInfo("Exodus Pilgrim", 9, Rarity.RARE, mage.cards.e.ExodusPilgrim.class));
        //cards.add(new SetCardInfo("Face the Truth", 10, Rarity.COMMON, mage.cards.f.FaceTheTruth.class));
        //cards.add(new SetCardInfo("Fervent Charioteer", 11, Rarity.COMMON, mage.cards.f.FerventCharioteer.class));
        //cards.add(new SetCardInfo("Floodplain Farmers", 12, Rarity.COMMON, mage.cards.f.FloodplainFarmers.class));
        //cards.add(new SetCardInfo("Glintsand Lammasu", 13, Rarity.COMMON, mage.cards.g.GlintsandLammasu.class));
        //cards.add(new SetCardInfo("Ibis Angel", 14, Rarity.RARE, mage.cards.i.IbisAngel.class));
        //cards.add(new SetCardInfo("Lammasu Sentinel Trap", 15, Rarity.RARE, mage.cards.l.LammasuSentinelTrap.class));
        //cards.add(new SetCardInfo("Monument Building", 16, Rarity.UNCOMMON, mage.cards.m.MonumentBuilding.class));
        //cards.add(new SetCardInfo("Mortal's Renewal", 17, Rarity.COMMON, mage.cards.m.MortalsRenewal.class));
        //cards.add(new SetCardInfo("Nabuto Ambusher", 18, Rarity.COMMON, mage.cards.n.NabutoAmbusher.class));
        //cards.add(new SetCardInfo("Name", 19, Rarity.UNCOMMON, mage.cards.n.Name.class));
        //cards.add(new SetCardInfo("Opener of the Way", 20, Rarity.RARE, mage.cards.o.OpenerOfTheWay.class));
        //cards.add(new SetCardInfo("Pack's Sandlancer", 21, Rarity.UNCOMMON, mage.cards.p.PacksSandlancer.class));
        //cards.add(new SetCardInfo("Pharaoh Nimseput", 22, Rarity.MYTHIC, mage.cards.p.PharaohNimseput.class));
        //cards.add(new SetCardInfo("Priest of Echoes", 23, Rarity.COMMON, mage.cards.p.PriestOfEchoes.class));
        //cards.add(new SetCardInfo("Recorder of Stories", 24, Rarity.COMMON, mage.cards.r.RecorderOfStories.class));
        //cards.add(new SetCardInfo("Reflector Trap", 25, Rarity.UNCOMMON, mage.cards.r.ReflectorTrap.class));
        //cards.add(new SetCardInfo("Remember the Names", 26, Rarity.COMMON, mage.cards.r.RememberTheNames.class));
        //cards.add(new SetCardInfo("Sacred Bennu", 27, Rarity.COMMON, mage.cards.s.SacredBennu.class));
        cards.add(new SetCardInfo("Sanctuary Cat", 28, Rarity.COMMON, mage.cards.s.SanctuaryCat.class));
        //cards.add(new SetCardInfo("Sandborn Seeker", 29, Rarity.COMMON, mage.cards.s.SandbornSeeker.class));
        //cards.add(new SetCardInfo("Sandchamber Trap", 30, Rarity.COMMON, mage.cards.s.SandchamberTrap.class));
        //cards.add(new SetCardInfo("Sarcophagus Sealer", 31, Rarity.UNCOMMON, mage.cards.s.SarcophagusSealer.class));
        //cards.add(new SetCardInfo("Shifting Sands", 32, Rarity.COMMON, mage.cards.s.ShiftingSands.class));
        //cards.add(new SetCardInfo("Solar Restoration", 33, Rarity.RARE, mage.cards.s.SolarRestoration.class));
        //cards.add(new SetCardInfo("Sundisk's Messenger", 34, Rarity.UNCOMMON, mage.cards.s.SundisksMessenger.class));
        //cards.add(new SetCardInfo("Unbreakable Bond", 35, Rarity.COMMON, mage.cards.u.UnbreakableBond.class));
        //cards.add(new SetCardInfo("Weigh the Heart", 36, Rarity.UNCOMMON, mage.cards.w.WeighTheHeart.class));
        //cards.add(new SetCardInfo("Wings of Afterlife", 37, Rarity.COMMON, mage.cards.w.WingsOfAfterlife.class));
        //cards.add(new SetCardInfo("ANK:Deface", 38, Rarity.UNCOMMON, mage.cards.d.AnkDeface.class));
        cards.add(new SetCardInfo("Annex", 39, Rarity.UNCOMMON, mage.cards.a.Annex.class));
        //cards.add(new SetCardInfo("Archive's Loreblade", 40, Rarity.COMMON, mage.cards.a.ArchivesLoreblade.class));
        //cards.add(new SetCardInfo("Chronowarp Trap", 41, Rarity.UNCOMMON, mage.cards.c.ChronowarpTrap.class));
        //cards.add(new SetCardInfo("Confabulate", 42, Rarity.COMMON, mage.cards.c.Confabulate.class));
        //cards.add(new SetCardInfo("Cursebreaker Mage", 43, Rarity.COMMON, mage.cards.c.CursebreakerMage.class));
        //cards.add(new SetCardInfo("Daughter of Iterinis", 44, Rarity.COMMON, mage.cards.d.DaughterOfIterinis.class));
        cards.add(new SetCardInfo("Divination", 45, Rarity.COMMON, mage.cards.d.Divination.class));
        //cards.add(new SetCardInfo("Drowning Trap", 46, Rarity.COMMON, mage.cards.d.DrowningTrap.class));
        //cards.add(new SetCardInfo("Duality of Truth", 47, Rarity.RARE, mage.cards.d.DualityOfTruth.class));
        //cards.add(new SetCardInfo("Dying of Thirst", 48, Rarity.COMMON, mage.cards.d.DyingOfThirst.class));
        cards.add(new SetCardInfo("Isle Turtle", 49, Rarity.COMMON, mage.cards.i.IsleTurtle.class));
        cards.add(new SetCardInfo("Iterinis, God of Waters", 50, Rarity.MYTHIC, mage.cards.i.IterinisGodOfWaters.class));
        //cards.add(new SetCardInfo("Lighthouse Pirates", 51, Rarity.COMMON, mage.cards.l.LighthousePirates.class));
        //cards.add(new SetCardInfo("Lunar Akhu", 52, Rarity.COMMON, mage.cards.l.LunarAkhu.class));
        //cards.add(new SetCardInfo("Master of Mysteries", 53, Rarity.UNCOMMON, mage.cards.m.MasterOfMysteries.class));
        //cards.add(new SetCardInfo("Mind Control Trap", 54, Rarity.RARE, mage.cards.m.MindControlTrap.class));
        //cards.add(new SetCardInfo("Neutralize", 55, Rarity.COMMON, mage.cards.n.Neutralize.class));
        //cards.add(new SetCardInfo("Nutkeb's Explorer", 56, Rarity.COMMON, mage.cards.n.NutkebsExplorer.class));
        //cards.add(new SetCardInfo("Palace Harpist", 57, Rarity.COMMON, mage.cards.p.PalaceHarpist.class));
        //cards.add(new SetCardInfo("Part the Sea", 58, Rarity.UNCOMMON, mage.cards.p.PartTheSea.class));
        //cards.add(new SetCardInfo("Riddle of Existence", 59, Rarity.COMMON, mage.cards.r.RiddleOfExistence.class));
        //cards.add(new SetCardInfo("Royal Archaeomancer", 60, Rarity.COMMON, mage.cards.r.RoyalArchaeomancer.class));
        //cards.add(new SetCardInfo("Scholar of Enigmas", 61, Rarity.UNCOMMON, mage.cards.s.ScholarOfEnigmas.class));
        //cards.add(new SetCardInfo("Secrets Forgotten", 62, Rarity.UNCOMMON, mage.cards.s.SecretsForgotten.class));
        //cards.add(new SetCardInfo("Serpent of Myth", 63, Rarity.UNCOMMON, mage.cards.s.SerpentOfMyth.class));
        //cards.add(new SetCardInfo("Sphinx of Right Answers", 64, Rarity.RARE, mage.cards.s.SphinxOfRightAnswers.class));
        //cards.add(new SetCardInfo("Sphinx's Renewal", 65, Rarity.COMMON, mage.cards.s.SphinxsRenewal.class));
        //cards.add(new SetCardInfo("Tamiyo, Moonseeker", 66, Rarity.MYTHIC, mage.cards.t.TamiyoMoonseeker.class));
        //cards.add(new SetCardInfo("Tamiyo's Voyage", 67, Rarity.RARE, mage.cards.t.TamiyosVoyage.class));
        //cards.add(new SetCardInfo("Telekinetic Mastery", 68, Rarity.UNCOMMON, mage.cards.t.TelekineticMastery.class));
        //cards.add(new SetCardInfo("Thought", 69, Rarity.UNCOMMON, mage.cards.t.Thought.class));
        //cards.add(new SetCardInfo("Timeless Currents", 70, Rarity.COMMON, mage.cards.t.TimelessCurrents.class));
        //cards.add(new SetCardInfo("Trapmaker's Secret", 71, Rarity.UNCOMMON, mage.cards.t.TrapmakersSecret.class));
        //cards.add(new SetCardInfo("Unexpected Flood", 72, Rarity.COMMON, mage.cards.u.UnexpectedFlood.class));
        //cards.add(new SetCardInfo("Unexplore", 73, Rarity.RARE, mage.cards.u.Unexplore.class));
        //cards.add(new SetCardInfo("Unlock the Conundrum", 74, Rarity.RARE, mage.cards.u.UnlockTheConundrum.class));
        //cards.add(new SetCardInfo("Avatar of Servitude", 75, Rarity.RARE, mage.cards.a.AvatarOfServitude.class));
        //cards.add(new SetCardInfo("Blood Offering", 76, Rarity.COMMON, mage.cards.b.BloodOffering.class));
        //cards.add(new SetCardInfo("Bloodrite Priest", 77, Rarity.UNCOMMON, mage.cards.b.BloodritePriest.class));
        //cards.add(new SetCardInfo("Bonerise Trap", 78, Rarity.RARE, mage.cards.b.BoneriseTrap.class));
        //cards.add(new SetCardInfo("Curse of the Pharaoh", 79, Rarity.UNCOMMON, mage.cards.c.CurseOfThePharaoh.class));
        //cards.add(new SetCardInfo("Devouring Scarab", 80, Rarity.COMMON, mage.cards.d.DevouringScarab.class));
        //cards.add(new SetCardInfo("Disciple of the Lost Moon", 81, Rarity.COMMON, mage.cards.d.DiscipleOfTheLostMoon.class));
        cards.add(new SetCardInfo("Disentomb", 82, Rarity.COMMON, mage.cards.d.Disentomb.class));
        //cards.add(new SetCardInfo("Disturb the Dead", 83, Rarity.UNCOMMON, mage.cards.d.DisturbTheDead.class));
        //cards.add(new SetCardInfo("Duality of Ambition", 84, Rarity.RARE, mage.cards.d.DualityOfAmbition.class));
        //cards.add(new SetCardInfo("Embalmer's Renewal", 85, Rarity.COMMON, mage.cards.e.EmbalmersRenewal.class));
        //cards.add(new SetCardInfo("Etiolate", 86, Rarity.COMMON, mage.cards.e.Etiolate.class));
        //cards.add(new SetCardInfo("Final Answer", 87, Rarity.COMMON, mage.cards.f.FinalAnswer.class));
        //cards.add(new SetCardInfo("Flesh-Eating Scarabs", 88, Rarity.UNCOMMON, mage.cards.f.FleshEatingScarabs.class));
        cards.add(new SetCardInfo("Granary's Bane", 89, Rarity.COMMON, mage.cards.g.GranarysBane.class));
        //cards.add(new SetCardInfo("Griffin Mummy", 90, Rarity.UNCOMMON, mage.cards.g.GriffinMummy.class));
        //cards.add(new SetCardInfo("Infernal Apophis", 91, Rarity.COMMON, mage.cards.i.InfernalApophis.class));
        //cards.add(new SetCardInfo("Insatiable Ammit", 92, Rarity.UNCOMMON, mage.cards.i.InsatiableAmmit.class));
        //cards.add(new SetCardInfo("Lurking Mummy", 93, Rarity.COMMON, mage.cards.l.LurkingMummy.class));
        //cards.add(new SetCardInfo("Mass Decrypt", 94, Rarity.MYTHIC, mage.cards.m.MassDecrypt.class));
        //cards.add(new SetCardInfo("Mastaba Defiler", 95, Rarity.UNCOMMON, mage.cards.m.MastabaDefiler.class));
        //cards.add(new SetCardInfo("Mortician's Touch", 96, Rarity.COMMON, mage.cards.m.MorticiansTouch.class));
        //cards.add(new SetCardInfo("Mummify", 97, Rarity.RARE, mage.cards.m.Mummify.class));
        //cards.add(new SetCardInfo("Necropolis Seneschal", 98, Rarity.COMMON, mage.cards.n.NecropolisSeneschal.class));
        //cards.add(new SetCardInfo("Pendulum Trap", 99, Rarity.UNCOMMON, mage.cards.p.PendulumTrap.class));
        //cards.add(new SetCardInfo("Plaguetouch Mummy", 100, Rarity.UNCOMMON, mage.cards.p.PlaguetouchMummy.class));
        //cards.add(new SetCardInfo("Plea Bargain", 101, Rarity.UNCOMMON, mage.cards.p.PleaBargain.class));
        //cards.add(new SetCardInfo("Restless Mummy", 102, Rarity.COMMON, mage.cards.r.RestlessMummy.class));
        //cards.add(new SetCardInfo("Rotting Giraffe", 103, Rarity.COMMON, mage.cards.r.RottingGiraffe.class));
        //cards.add(new SetCardInfo("Sentesh, God of Secrets", 104, Rarity.MYTHIC, mage.cards.s.SenteshGodOfSecrets.class));
        //cards.add(new SetCardInfo("Sentesh's Rattlesnake", 105, Rarity.COMMON, mage.cards.s.SenteshsRattlesnake.class));
        //cards.add(new SetCardInfo("Servant of Erises", 106, Rarity.COMMON, mage.cards.s.ServantOfErises.class));
        //cards.add(new SetCardInfo("Sesmu of Enslavement", 107, Rarity.RARE, mage.cards.s.SesmuOfEnslavement.class));
        //cards.add(new SetCardInfo("Shadow", 108, Rarity.UNCOMMON, mage.cards.s.Shadow.class));
        //cards.add(new SetCardInfo("Slumbering Pharaoh", 109, Rarity.COMMON, mage.cards.s.SlumberingPharaoh.class));
        cards.add(new SetCardInfo("Vengeful Pharaoh", 110, Rarity.RARE, mage.cards.v.VengefulPharaoh.class));
        //cards.add(new SetCardInfo("Water to Blood", 111, Rarity.COMMON, mage.cards.w.WaterToBlood.class));
        //cards.add(new SetCardInfo("Acid Spray Trap", 112, Rarity.UNCOMMON, mage.cards.a.AcidSprayTrap.class));
        //cards.add(new SetCardInfo("Act of Betrayal", 113, Rarity.COMMON, mage.cards.a.ActOfBetrayal.class));
        //cards.add(new SetCardInfo("Adorned Dragon", 114, Rarity.RARE, mage.cards.a.AdornedDragon.class));
        //cards.add(new SetCardInfo("Ainok Browbeater", 115, Rarity.UNCOMMON, mage.cards.a.AinokBrowbeater.class));
        //cards.add(new SetCardInfo("Apostate Thug", 116, Rarity.COMMON, mage.cards.a.ApostateThug.class));
        //cards.add(new SetCardInfo("Ash Akhu", 117, Rarity.UNCOMMON, mage.cards.a.AshAkhu.class));
        //cards.add(new SetCardInfo("Careless Archaeologist", 118, Rarity.COMMON, mage.cards.c.CarelessArchaeologist.class));
        //cards.add(new SetCardInfo("Cave-In Trap", 119, Rarity.COMMON, mage.cards.c.CaveInTrap.class));
        cards.add(new SetCardInfo("Cone of Flame", 120, Rarity.UNCOMMON, mage.cards.c.ConeOfFlame.class));
        //cards.add(new SetCardInfo("Dack's Trickery", 121, Rarity.UNCOMMON, mage.cards.d.DacksTrickery.class));
        cards.add(new SetCardInfo("Demolish", 122, Rarity.COMMON, mage.cards.d.Demolish.class));
        //cards.add(new SetCardInfo("Desert Colossus", 123, Rarity.COMMON, mage.cards.d.DesertColossus.class));
        //cards.add(new SetCardInfo("Disciple of Hesaret", 124, Rarity.UNCOMMON, mage.cards.d.DiscipleOfHesaret.class));
        //cards.add(new SetCardInfo("Duality of Passion", 125, Rarity.RARE, mage.cards.d.DualityOfPassion.class));
        //cards.add(new SetCardInfo("Eager Ainok", 126, Rarity.COMMON, mage.cards.e.EagerAinok.class));
        //cards.add(new SetCardInfo("Firehollow Phoenix", 127, Rarity.RARE, mage.cards.f.FirehollowPhoenix.class));
        //cards.add(new SetCardInfo("Flame's Renewal", 128, Rarity.COMMON, mage.cards.f.FlamesRenewal.class));
        //cards.add(new SetCardInfo("Foretell with Fire", 129, Rarity.COMMON, mage.cards.f.ForetellWithFire.class));
        cards.add(new SetCardInfo("Harness the Storm", 130, Rarity.RARE, mage.cards.h.HarnessTheStorm.class));
        //cards.add(new SetCardInfo("Heart", 131, Rarity.UNCOMMON, mage.cards.h.Heart.class));
        //cards.add(new SetCardInfo("Hesaret, God of Inspiration", 132, Rarity.MYTHIC, mage.cards.h.HesaretGodOfInspiration.class));
        //cards.add(new SetCardInfo("Hesaret's Alacrity", 133, Rarity.COMMON, mage.cards.h.HesaretsAlacrity.class));
        //cards.add(new SetCardInfo("Horned Heartstoker", 134, Rarity.COMMON, mage.cards.h.HornedHeartstoker.class));
        //cards.add(new SetCardInfo("Incandescent Hieroglyphs", 135, Rarity.COMMON, mage.cards.i.IncandescentHieroglyphs.class));
        //cards.add(new SetCardInfo("Iun, World Reborn", 136, Rarity.MYTHIC, mage.cards.i.IunWorldReborn.class));
        //cards.add(new SetCardInfo("Iun's Flameweaver", 137, Rarity.UNCOMMON, mage.cards.i.IunsFlameweaver.class));
        //cards.add(new SetCardInfo("Lawmage of Kismut", 138, Rarity.COMMON, mage.cards.l.LawmageOfKismut.class));
        //cards.add(new SetCardInfo("Lightning Effigy", 139, Rarity.UNCOMMON, mage.cards.l.LightningEffigy.class));
        //cards.add(new SetCardInfo("Papyrus Archivist", 140, Rarity.UNCOMMON, mage.cards.p.PapyrusArchivist.class));
        //cards.add(new SetCardInfo("Phoenix-Flame Ritual", 141, Rarity.COMMON, mage.cards.p.PhoenixFlameRitual.class));
        //cards.add(new SetCardInfo("Rejanak's Familiar", 142, Rarity.COMMON, mage.cards.r.RejanaksFamiliar.class));
        //cards.add(new SetCardInfo("Stoneball Trap", 143, Rarity.RARE, mage.cards.s.StoneballTrap.class));
        //cards.add(new SetCardInfo("Sun God's Ire", 144, Rarity.RARE, mage.cards.s.SunGodsIre.class));
        //cards.add(new SetCardInfo("Tomb Robbers", 145, Rarity.COMMON, mage.cards.t.TombRobbers.class));
        //cards.add(new SetCardInfo("Trapmaker's Detonator", 146, Rarity.UNCOMMON, mage.cards.t.TrapmakersDetonator.class));
        //cards.add(new SetCardInfo("Undead Ainok", 147, Rarity.COMMON, mage.cards.u.UndeadAinok.class));
        cards.add(new SetCardInfo("Zebra Behemoth", 148, Rarity.COMMON, mage.cards.z.ZebraBehemoth.class));
        //cards.add(new SetCardInfo("Acolyte of Coils", 149, Rarity.UNCOMMON, mage.cards.a.AcolyteOfCoils.class));
        cards.add(new SetCardInfo("Cobra Trap", 150, Rarity.UNCOMMON, mage.cards.c.CobraTrap.class));
        //cards.add(new SetCardInfo("Colossal Dunewurm", 151, Rarity.COMMON, mage.cards.c.ColossalDunewurm.class));
        //cards.add(new SetCardInfo("Continual Sandstorm", 152, Rarity.UNCOMMON, mage.cards.c.ContinualSandstorm.class));
        //cards.add(new SetCardInfo("Desert Guide", 153, Rarity.COMMON, mage.cards.d.DesertGuide.class));
        //cards.add(new SetCardInfo("Dreamscale Hydra", 154, Rarity.RARE, mage.cards.d.DreamscaleHydra.class));
        //cards.add(new SetCardInfo("Duality of Destiny", 155, Rarity.RARE, mage.cards.d.DualityOfDestiny.class));
        //cards.add(new SetCardInfo("Essence", 156, Rarity.UNCOMMON, mage.cards.e.Essence.class));
        //cards.add(new SetCardInfo("Excavate", 157, Rarity.UNCOMMON, mage.cards.e.Excavate.class));
        cards.add(new SetCardInfo("Fade into Antiquity", 158, Rarity.COMMON, mage.cards.f.FadeIntoAntiquity.class));
        cards.add(new SetCardInfo("Giant Growth", 159, Rarity.COMMON, mage.cards.g.GiantGrowth.class));
        //cards.add(new SetCardInfo("Glintsand Cloak", 160, Rarity.COMMON, mage.cards.g.GlintsandCloak.class));
        //cards.add(new SetCardInfo("Gods' Gift", 161, Rarity.COMMON, mage.cards.g.GodsGift.class));
        //cards.add(new SetCardInfo("Hunter's Triumph", 162, Rarity.COMMON, mage.cards.h.HuntersTriumph.class));
        //cards.add(new SetCardInfo("Indomitable Elephant", 163, Rarity.UNCOMMON, mage.cards.i.IndomitableElephant.class));
        //cards.add(new SetCardInfo("Living Sandstorm", 164, Rarity.COMMON, mage.cards.l.LivingSandstorm.class));
        cards.add(new SetCardInfo("Ma'at, God of Harmony", 165, Rarity.MYTHIC, mage.cards.m.MaatGodOfHarmony.class));
        //cards.add(new SetCardInfo("Merchant Caravan", 166, Rarity.COMMON, mage.cards.m.MerchantCaravan.class));
        //cards.add(new SetCardInfo("Mirror Mirage", 167, Rarity.RARE, mage.cards.m.MirrorMirage.class));
        //cards.add(new SetCardInfo("Nabuto Cavalry", 168, Rarity.COMMON, mage.cards.n.NabutoCavalry.class));
        //cards.add(new SetCardInfo("Nomad's Renewal", 169, Rarity.COMMON, mage.cards.n.NomadsRenewal.class));
        //cards.add(new SetCardInfo("Pharaonic Proportions", 170, Rarity.UNCOMMON, mage.cards.p.PharaonicProportions.class));
        //cards.add(new SetCardInfo("Plague of Locusts", 171, Rarity.UNCOMMON, mage.cards.p.PlagueOfLocusts.class));
        //cards.add(new SetCardInfo("Planar Lockdown", 172, Rarity.RARE, mage.cards.p.PlanarLockdown.class));
        //cards.add(new SetCardInfo("Sandbreeder", 173, Rarity.RARE, mage.cards.s.Sandbreeder.class));
        cards.add(new SetCardInfo("Savage Hippo", 174, Rarity.COMMON, mage.cards.s.SavageHippo.class));
        cards.add(new SetCardInfo("Scapeshift", 175, Rarity.RARE, mage.cards.s.Scapeshift.class));
        //cards.add(new SetCardInfo("Scavenging Petsuchos", 176, Rarity.COMMON, mage.cards.s.ScavengingPetsuchos.class));
        //cards.add(new SetCardInfo("Shortcut", 177, Rarity.COMMON, mage.cards.s.Shortcut.class));
        //cards.add(new SetCardInfo("Sobki, World Severer", 178, Rarity.MYTHIC, mage.cards.s.SobkiWorldSeverer.class));
        //cards.add(new SetCardInfo("Sobki's Ambusher", 179, Rarity.UNCOMMON, mage.cards.s.SobkisAmbusher.class));
        //cards.add(new SetCardInfo("Tiphsu's Emissary", 180, Rarity.COMMON, mage.cards.t.TiphsusEmissary.class));
        //cards.add(new SetCardInfo("Venerable Explorer", 181, Rarity.UNCOMMON, mage.cards.v.VenerableExplorer.class));
        //cards.add(new SetCardInfo("Warden of Life", 182, Rarity.COMMON, mage.cards.w.WardenOfLife.class));
        //cards.add(new SetCardInfo("Wayfarer Giant", 183, Rarity.UNCOMMON, mage.cards.w.WayfarerGiant.class));
        //cards.add(new SetCardInfo("Weaver of Seasons", 184, Rarity.COMMON, mage.cards.w.WeaverOfSeasons.class));
        cards.add(new SetCardInfo("Wild Camelicorn", 185, Rarity.COMMON, mage.cards.w.WildCamelicorn.class));
        //cards.add(new SetCardInfo("Ainok General", 186, Rarity.UNCOMMON, mage.cards.a.AinokGeneral.class));
        //cards.add(new SetCardInfo("Beseecher of Mortals", 187, Rarity.RARE, mage.cards.b.BeseecherOfMortals.class));
        //cards.add(new SetCardInfo("Cartographer of Kariro", 188, Rarity.UNCOMMON, mage.cards.c.CartographerOfKariro.class));
        //cards.add(new SetCardInfo("Cryptic Reversal", 189, Rarity.UNCOMMON, mage.cards.c.CrypticReversal.class));
        //cards.add(new SetCardInfo("Dack, Tomb Raider", 190, Rarity.MYTHIC, mage.cards.d.DackTombRaider.class));
        //cards.add(new SetCardInfo("Desert Tornado", 191, Rarity.RARE, mage.cards.d.DesertTornado.class));
        //cards.add(new SetCardInfo("Dune Enchantress", 192, Rarity.RARE, mage.cards.d.DuneEnchantress.class));
        //cards.add(new SetCardInfo("Electrify the Soul", 193, Rarity.UNCOMMON, mage.cards.e.ElectrifyTheSoul.class));
        //cards.add(new SetCardInfo("Firstborn's Demise", 194, Rarity.RARE, mage.cards.f.FirstbornsDemise.class));
        //cards.add(new SetCardInfo("Glintsand Gatherer", 195, Rarity.UNCOMMON, mage.cards.g.GlintsandGatherer.class));
        //cards.add(new SetCardInfo("Grand Finale", 196, Rarity.RARE, mage.cards.g.GrandFinale.class));
        //cards.add(new SetCardInfo("Hatseket, Great Archivist", 197, Rarity.RARE, mage.cards.h.HatseketGreatArchivist.class));
        //cards.add(new SetCardInfo("Mummified Mortician", 198, Rarity.UNCOMMON, mage.cards.m.MummifiedMortician.class));
        //cards.add(new SetCardInfo("Nutkeb's Titan", 199, Rarity.UNCOMMON, mage.cards.n.NutkebsTitan.class));
        //cards.add(new SetCardInfo("Origin of Life", 200, Rarity.UNCOMMON, mage.cards.o.OriginOfLife.class));
        //cards.add(new SetCardInfo("Reimagine", 201, Rarity.RARE, mage.cards.r.Reimagine.class));
        cards.add(new SetCardInfo("The Scorpion King", 202, Rarity.RARE, mage.cards.t.TheScorpionKing.class));
        //cards.add(new SetCardInfo("Sphere of Faith", 203, Rarity.UNCOMMON, mage.cards.s.SphereOfFaith.class));
        //cards.add(new SetCardInfo("Sphincolich Loremaster", 204, Rarity.RARE, mage.cards.s.SphincolichLoremaster.class));
        cards.add(new SetCardInfo("Sphinx's Revelation", 205, Rarity.MYTHIC, mage.cards.s.SphinxsRevelation.class));
        //cards.add(new SetCardInfo("Travelling Stargazer", 206, Rarity.MYTHIC, mage.cards.t.TravellingStargazer.class));
        //cards.add(new SetCardInfo("Underworld Escort", 207, Rarity.UNCOMMON, mage.cards.u.UnderworldEscort.class));
        //cards.add(new SetCardInfo("Warlord Rejanak", 208, Rarity.RARE, mage.cards.w.WarlordRejanak.class));
        //cards.add(new SetCardInfo("Archaic Remnant", 209, Rarity.UNCOMMON, mage.cards.a.ArchaicRemnant.class));
        //cards.add(new SetCardInfo("Ark of Extinction", 210, Rarity.RARE, mage.cards.a.ArkOfExtinction.class));
        //cards.add(new SetCardInfo("Brass-Sting Guardian", 211, Rarity.UNCOMMON, mage.cards.b.BrassStingGuardian.class));
        //cards.add(new SetCardInfo("Bronze Khopesh", 212, Rarity.COMMON, mage.cards.b.BronzeKhopesh.class));
        //cards.add(new SetCardInfo("Dreamfire Bow", 213, Rarity.UNCOMMON, mage.cards.d.DreamfireBow.class));
        //cards.add(new SetCardInfo("Electrum-Gilded Swarm", 214, Rarity.RARE, mage.cards.e.ElectrumGildedSwarm.class));
        cards.add(new SetCardInfo("Expedition Map", 215, Rarity.COMMON, mage.cards.e.ExpeditionMap.class));
        //cards.add(new SetCardInfo("Game of Passing", 216, Rarity.UNCOMMON, mage.cards.g.GameOfPassing.class));
        //cards.add(new SetCardInfo("Godsent Ankh", 217, Rarity.UNCOMMON, mage.cards.g.GodsentAnkh.class));
        //cards.add(new SetCardInfo("Heart of Erises", 218, Rarity.RARE, mage.cards.h.HeartOfErises.class));
        //cards.add(new SetCardInfo("Piece of Erises", 219, Rarity.UNCOMMON, mage.cards.p.PieceOfErises.class));
        cards.add(new SetCardInfo("Pilgrim's Eye", 220, Rarity.UNCOMMON, mage.cards.p.PilgrimsEye.class));
        //cards.add(new SetCardInfo("Scales of Composure", 221, Rarity.MYTHIC, mage.cards.s.ScalesOfComposure.class));
        //cards.add(new SetCardInfo("Scribe's Fetich", 222, Rarity.UNCOMMON, mage.cards.s.ScribesFetich.class));
        //cards.add(new SetCardInfo("Sky Barge", 223, Rarity.COMMON, mage.cards.s.SkyBarge.class));
        //cards.add(new SetCardInfo("Sleeping Guardian", 224, Rarity.COMMON, mage.cards.s.SleepingGuardian.class));
        //cards.add(new SetCardInfo("Soulcatcher Obelisk", 225, Rarity.RARE, mage.cards.s.SoulcatcherObelisk.class));
        //cards.add(new SetCardInfo("Stone of Tongues", 226, Rarity.RARE, mage.cards.s.StoneOfTongues.class));
        //cards.add(new SetCardInfo("Stonewrought Companion", 227, Rarity.COMMON, mage.cards.s.StonewroughtCompanion.class));
        cards.add(new SetCardInfo("Archive of Kariro", 228, Rarity.MYTHIC, mage.cards.a.ArchiveOfKariro.class));
        //cards.add(new SetCardInfo("Bloodstone Oasis", 229, Rarity.UNCOMMON, mage.cards.b.BloodstoneOasis.class));
        //cards.add(new SetCardInfo("Burial Chamber", 230, Rarity.COMMON, mage.cards.b.BurialChamber.class));
        //cards.add(new SetCardInfo("Collapsing Underworld", 231, Rarity.RARE, mage.cards.c.CollapsingUnderworld.class));
        //cards.add(new SetCardInfo("Crossroads Sands", 232, Rarity.COMMON, mage.cards.c.CrossroadsSands.class));
        cards.add(new SetCardInfo("Crumbling Vestige", 233, Rarity.COMMON, mage.cards.c.CrumblingVestige.class));
        //cards.add(new SetCardInfo("Desert Temple", 234, Rarity.COMMON, mage.cards.d.DesertTemple.class));
        cards.add(new SetCardInfo("Desolate Lighthouse", 235, Rarity.RARE, mage.cards.d.DesolateLighthouse.class));
        //cards.add(new SetCardInfo("Forgotten Necropolis", 236, Rarity.RARE, mage.cards.f.ForgottenNecropolis.class));
        //cards.add(new SetCardInfo("Garden Oasis", 237, Rarity.UNCOMMON, mage.cards.g.GardenOasis.class));
        //cards.add(new SetCardInfo("Gelid Pyramids", 238, Rarity.RARE, mage.cards.g.GelidPyramids.class));
        cards.add(new SetCardInfo("Mana Confluence", 239, Rarity.RARE, mage.cards.m.ManaConfluence.class));
        //cards.add(new SetCardInfo("Memory Lane", 240, Rarity.RARE, mage.cards.m.MemoryLane.class));
        //cards.add(new SetCardInfo("Rotting Oasis", 241, Rarity.UNCOMMON, mage.cards.r.RottingOasis.class));
        //cards.add(new SetCardInfo("Sanctified Oasis", 242, Rarity.UNCOMMON, mage.cards.s.SanctifiedOasis.class));
        //cards.add(new SetCardInfo("Stonekeep Sphinx", 243, Rarity.UNCOMMON, mage.cards.s.StonekeepSphinx.class));
        //cards.add(new SetCardInfo("Sunset Pyramids", 244, Rarity.COMMON, mage.cards.s.SunsetPyramids.class));
        //cards.add(new SetCardInfo("Temephis Promenade", 245, Rarity.RARE, mage.cards.t.TemephisPromenade.class));
        //cards.add(new SetCardInfo("Tranquil Oasis", 246, Rarity.UNCOMMON, mage.cards.t.TranquilOasis.class));
        //cards.add(new SetCardInfo("Treasure Room of Akhamesses", 247, Rarity.RARE, mage.cards.t.TreasureRoomOfAkhamesses.class));
        cards.add(new SetCardInfo("Unknown Shores", 248, Rarity.COMMON, mage.cards.u.UnknownShores.class));
        //cards.add(new SetCardInfo("Valley of Pyramids", 249, Rarity.UNCOMMON, mage.cards.v.ValleyOfPyramids.class));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 251, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 252, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 253, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 254, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 255, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 256, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 257, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 258, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 259, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 260, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 261, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 262, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 263, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 264, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
    }
}
