package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class Eralou extends ExpansionSet {
    private static final Eralou instance = new Eralou();

    public static Eralou getInstance() { return instance; }

    private Eralou() {
        super("Eralou", "EAU", ExpansionSet.buildDate(2019, 2, 8), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Acclaimed Leadership", 1, Rarity.UNCOMMON, mage.cards.a.AcclaimedLeadership.class));
        //cards.add(new SetCardInfo("Aven Traveller", 2, Rarity.COMMON, mage.cards.a.AvenTraveller.class));
        //cards.add(new SetCardInfo("Beautiful Crescendo", 3, Rarity.UNCOMMON, mage.cards.b.BeautifulCrescendo.class));
        //cards.add(new SetCardInfo("Blessings of the Parish", 4, Rarity.COMMON, mage.cards.b.BlessingsOfTheParish.class));
        cards.add(new SetCardInfo("Containment Priest", 5, Rarity.RARE, mage.cards.c.ContainmentPriest.class));
        //cards.add(new SetCardInfo("Faradia, Honored Sovereign", 6, Rarity.MYTHIC, mage.cards.f.FaradiaHonoredSovereign.class));
        //cards.add(new SetCardInfo("Faradia's Collector", 7, Rarity.UNCOMMON, mage.cards.f.FaradiasCollector.class));
        //cards.add(new SetCardInfo("Faradia's Grace", 8, Rarity.RARE, mage.cards.f.FaradiasGrace.class));
        //cards.add(new SetCardInfo("Festival Songstress", 9, Rarity.UNCOMMON, mage.cards.f.FestivalSongstress.class));
        //cards.add(new SetCardInfo("Glamorous Festivities", 10, Rarity.RARE, mage.cards.g.GlamorousFestivities.class));
        //cards.add(new SetCardInfo("Gleaming Gallant", 11, Rarity.COMMON, mage.cards.g.GleamingGallant.class));
        //cards.add(new SetCardInfo("Glorious Celebration", 12, Rarity.COMMON, mage.cards.g.GloriousCelebration.class));
        //cards.add(new SetCardInfo("Helena, the Awakener", 13, Rarity.MYTHIC, mage.cards.h.HelenaTheAwakener.class));
        //cards.add(new SetCardInfo("Helena's Exaltation", 14, Rarity.COMMON, mage.cards.h.HelenasExaltation.class));
        //cards.add(new SetCardInfo("Helena's Rebuff", 15, Rarity.RARE, mage.cards.h.HelenasRebuff.class));
        //cards.add(new SetCardInfo("Heroic Crusader", "16a", Rarity.RARE, mage.cards.h.HeroicCrusader.class));
        //cards.add(new SetCardInfo("Faradia's Ascendant", "16b", Rarity.RARE, mage.cards.f.FaradiasAscendant.class));
        //cards.add(new SetCardInfo("Inspiring Band", 17, Rarity.COMMON, mage.cards.i.InspiringBand.class));
        //cards.add(new SetCardInfo("Kantra of Healing", 18, Rarity.UNCOMMON, mage.cards.k.KantraOfHealing.class));
        //cards.add(new SetCardInfo("New Alores Charmer", 19, Rarity.COMMON, mage.cards.n.NewAloresCharmer.class));
        //cards.add(new SetCardInfo("New Alores Fiddler", 20, Rarity.COMMON, mage.cards.n.NewAloresFiddler.class));
        //cards.add(new SetCardInfo("Nimbus Glider", 21, Rarity.COMMON, mage.cards.n.NimbusGlider.class));
        //cards.add(new SetCardInfo("Ontarachie Vagabond", 22, Rarity.RARE, mage.cards.o.OntarachieVagabond.class));
        //cards.add(new SetCardInfo("Overgrowth Guardian", 23, Rarity.COMMON, mage.cards.o.OvergrowthGuardian.class));
        //cards.add(new SetCardInfo("Parish Paragon", 24, Rarity.RARE, mage.cards.p.ParishParagon.class));
        //cards.add(new SetCardInfo("Parish's Command", 25, Rarity.UNCOMMON, mage.cards.p.ParishsCommand.class));
        //cards.add(new SetCardInfo("Pretentious Performer", 26, Rarity.RARE, mage.cards.p.PretentiousPerformer.class));
        //cards.add(new SetCardInfo("Proselytize", 27, Rarity.COMMON, mage.cards.p.Proselytize.class));
        //cards.add(new SetCardInfo("Rejoicing Aristocrats", 28, Rarity.RARE, mage.cards.r.RejoicingAristocrats.class));
        cards.add(new SetCardInfo("Smite the Monstrous", 29, Rarity.COMMON, mage.cards.s.SmiteTheMonstrous.class));
        cards.add(new SetCardInfo("Solemn Offering", 30, Rarity.UNCOMMON, mage.cards.s.SolemnOffering.class));
        //cards.add(new SetCardInfo("Splendid Leap", 31, Rarity.UNCOMMON, mage.cards.s.SplendidLeap.class));
        //cards.add(new SetCardInfo("Sporecrafter's Gift", 32, Rarity.COMMON, mage.cards.s.SporecraftersGift.class));
        //cards.add(new SetCardInfo("Sporeflow Mantle", 33, Rarity.COMMON, mage.cards.s.SporeflowMantle.class));
        //cards.add(new SetCardInfo("Sporeflow Propagator", 34, Rarity.UNCOMMON, mage.cards.s.SporeflowPropagator.class));
        //cards.add(new SetCardInfo("Sporeflow Repulsion", 35, Rarity.COMMON, mage.cards.s.SporeflowRepulsion.class));
        //cards.add(new SetCardInfo("Stratusform Seraph", 36, Rarity.COMMON, mage.cards.s.StratusformSeraph.class));
        //cards.add(new SetCardInfo("Thespian Soldier", 37, Rarity.COMMON, mage.cards.t.ThespianSoldier.class));
        //cards.add(new SetCardInfo("Tomb Keeper", 38, Rarity.UNCOMMON, mage.cards.t.TombKeeper.class));
        //cards.add(new SetCardInfo("Turtleback Guide", 39, Rarity.COMMON, mage.cards.t.TurtlebackGuide.class));
        //cards.add(new SetCardInfo("Woopip Chef", 40, Rarity.UNCOMMON, mage.cards.w.WoopipChef.class));
        //cards.add(new SetCardInfo("Woopip Sproutling", 41, Rarity.COMMON, mage.cards.w.WoopipSproutling.class));
        //cards.add(new SetCardInfo("Aetherdrain", 42, Rarity.UNCOMMON, mage.cards.a.Aetherdrain.class));
        //cards.add(new SetCardInfo("Aspiring Rascals", "43a", Rarity.RARE, mage.cards.a.AspiringRascals.class));
        //cards.add(new SetCardInfo("Marshback Knights", "43b", Rarity.RARE, mage.cards.m.MarshbackKnights.class));
        //cards.add(new SetCardInfo("Aven Acoustimancer", 44, Rarity.UNCOMMON, mage.cards.a.AvenAcoustimancer.class));
        //cards.add(new SetCardInfo("Belittle", 45, Rarity.COMMON, mage.cards.b.Belittle.class));
        //cards.add(new SetCardInfo("Bewildering Sight", 46, Rarity.COMMON, mage.cards.b.BewilderingSight.class));
        //cards.add(new SetCardInfo("Bogsnatcher Drake", 47, Rarity.COMMON, mage.cards.b.BogsnatcherDrake.class));
        //cards.add(new SetCardInfo("Book Return", 48, Rarity.COMMON, mage.cards.b.BookReturn.class));
        //cards.add(new SetCardInfo("Captivating Jester", 49, Rarity.UNCOMMON, mage.cards.c.CaptivatingJester.class));
        //cards.add(new SetCardInfo("Chilling Musician", 50, Rarity.COMMON, mage.cards.c.ChillingMusician.class));
        //cards.add(new SetCardInfo("Coordinated Commotion", 51, Rarity.COMMON, mage.cards.c.CoordinatedCommotion.class));
        cards.add(new SetCardInfo("Coveted Stallion", 52, Rarity.COMMON, mage.cards.c.CovetedStallion.class));
        //cards.add(new SetCardInfo("Creeping Pianist", 53, Rarity.COMMON, mage.cards.c.CreepingPianist.class));
        //cards.add(new SetCardInfo("Curse of Impotence", 54, Rarity.UNCOMMON, mage.cards.c.CurseOfImpotence.class));
        cards.add(new SetCardInfo("Divination", 55, Rarity.COMMON, mage.cards.d.Divination.class));
        //cards.add(new SetCardInfo("Elaborate Transportation", 56, Rarity.COMMON, mage.cards.e.ElaborateTransportation.class));
        //cards.add(new SetCardInfo("Enthralling Actor", 57, Rarity.RARE, mage.cards.e.EnthrallingActor.class));
        //cards.add(new SetCardInfo("Glamorous Aerialist", 58, Rarity.COMMON, mage.cards.g.GlamorousAerialist.class));
        //cards.add(new SetCardInfo("Hunter's Mark", 59, Rarity.RARE, mage.cards.h.HuntersMark.class));
        //cards.add(new SetCardInfo("Kantra of the Third Eye", 60, Rarity.RARE, mage.cards.k.KantraOfTheThirdEye.class));
        //cards.add(new SetCardInfo("Lazaire's Conjuring", 61, Rarity.MYTHIC, mage.cards.l.LazairesConjuring.class));
        //cards.add(new SetCardInfo("Lost in Admiration", 62, Rarity.COMMON, mage.cards.l.LostInAdmiration.class));
        //cards.add(new SetCardInfo("Lotus Debutante", 63, Rarity.UNCOMMON, mage.cards.l.LotusDebutante.class));
        //cards.add(new SetCardInfo("Luminescent Croaker", 64, Rarity.COMMON, mage.cards.l.LuminescentCroaker.class));
        //cards.add(new SetCardInfo("Mark of the Scaleblight", 65, Rarity.RARE, mage.cards.m.MarkOfTheScaleblight.class));
        //cards.add(new SetCardInfo("Marshcroaker Coaching", 66, Rarity.RARE, mage.cards.m.MarshcroakerCoaching.class));
        cards.add(new SetCardInfo("Marshcroaker Drake", 67, Rarity.UNCOMMON, mage.cards.m.MarshcroakerDrake.class));
        cards.add(new SetCardInfo("Negate", 68, Rarity.COMMON, mage.cards.n.Negate.class));
        cards.add(new SetCardInfo("Opt", 69, Rarity.COMMON, mage.cards.o.Opt.class));
        //cards.add(new SetCardInfo("Planar Traversal", 70, Rarity.MYTHIC, mage.cards.p.PlanarTraversal.class));
        //cards.add(new SetCardInfo("Portside Smuggler", 71, Rarity.COMMON, mage.cards.p.PortsideSmuggler.class));
        //cards.add(new SetCardInfo("Ranidaphobia", 72, Rarity.COMMON, mage.cards.r.Ranidaphobia.class));
        //cards.add(new SetCardInfo("River Dabbler", 73, Rarity.COMMON, mage.cards.r.RiverDabbler.class));
        //cards.add(new SetCardInfo("Riverguide Harpist", 74, Rarity.UNCOMMON, mage.cards.r.RiverguideHarpist.class));
        //cards.add(new SetCardInfo("Sensational Festivities", 75, Rarity.RARE, mage.cards.s.SensationalFestivities.class));
        //cards.add(new SetCardInfo("Soul Trapper", 76, Rarity.UNCOMMON, mage.cards.s.SoulTrapper.class));
        //cards.add(new SetCardInfo("Tempted by Lotuses", 77, Rarity.UNCOMMON, mage.cards.t.TemptedByLotuses.class));
        //cards.add(new SetCardInfo("Wade Through", 78, Rarity.RARE, mage.cards.w.WadeThrough.class));
        //cards.add(new SetCardInfo("Witch of Shifting Waters", 79, Rarity.RARE, mage.cards.w.WitchOfShiftingWaters.class));
        //cards.add(new SetCardInfo("Witch's Invocation", 80, Rarity.RARE, mage.cards.w.WitchsInvocation.class));
        //cards.add(new SetCardInfo("Zoulev Envoy", 81, Rarity.COMMON, mage.cards.z.ZoulevEnvoy.class));
        //cards.add(new SetCardInfo("Zoulev Offering", 82, Rarity.UNCOMMON, mage.cards.z.ZoulevOffering.class));
        //cards.add(new SetCardInfo("Zoulev Rebuff", 83, Rarity.UNCOMMON, mage.cards.z.ZoulevRebuff.class));
        //cards.add(new SetCardInfo("Ancestor's Calling", 84, Rarity.COMMON, mage.cards.a.AncestorsCalling.class));
        //cards.add(new SetCardInfo("Banish", 85, Rarity.RARE, mage.cards.b.Banish.class));
        //cards.add(new SetCardInfo("Bayou Courier", 86, Rarity.UNCOMMON, mage.cards.b.BayouCourier.class));
        //cards.add(new SetCardInfo("Bitterheart Bokor", 87, Rarity.UNCOMMON, mage.cards.b.BitterheartBokor.class));
        //cards.add(new SetCardInfo("Bog Rebirth", 88, Rarity.COMMON, mage.cards.b.BogRebirth.class));
        //cards.add(new SetCardInfo("Boghex Witch", 89, Rarity.MYTHIC, mage.cards.b.BoghexWitch.class));
        //cards.add(new SetCardInfo("Bokor's Recruitment", 90, Rarity.COMMON, mage.cards.b.BokorsRecruitment.class));
        //cards.add(new SetCardInfo("Curse of Bleeding", 91, Rarity.RARE, mage.cards.c.CurseOfBleeding.class));
        //cards.add(new SetCardInfo("Curse of Haunting", 92, Rarity.COMMON, mage.cards.c.CurseOfHaunting.class));
        //cards.add(new SetCardInfo("Curse of Waning Wealth", 93, Rarity.UNCOMMON, mage.cards.c.CurseOfWaningWealth.class));
        //cards.add(new SetCardInfo("Explorer's Fate", 94, Rarity.RARE, mage.cards.e.ExplorersFate.class));
        //cards.add(new SetCardInfo("Greater Swooprat", 95, Rarity.UNCOMMON, mage.cards.g.GreaterSwooprat.class));
        //cards.add(new SetCardInfo("Grim Festivities", 96, Rarity.RARE, mage.cards.g.GrimFestivities.class));
        //cards.add(new SetCardInfo("Grisly Hunger", 97, Rarity.RARE, mage.cards.g.GrislyHunger.class));
        //cards.add(new SetCardInfo("Kantra of Avarice", 98, Rarity.UNCOMMON, mage.cards.k.KantraOfAvarice.class));
        //cards.add(new SetCardInfo("Kantra of Plagues", 99, Rarity.MYTHIC, mage.cards.k.KantraOfPlagues.class));
        //cards.add(new SetCardInfo("Lazaire's Altar", 100, Rarity.RARE, mage.cards.l.LazairesAltar.class));
        //cards.add(new SetCardInfo("Murmurs of the Bayou", 101, Rarity.COMMON, mage.cards.m.MurmursOfTheBayou.class));
        //cards.add(new SetCardInfo("Occult Tutor", 102, Rarity.RARE, mage.cards.o.OccultTutor.class));
        //cards.add(new SetCardInfo("Ontarachie Hunter", "103a", Rarity.RARE, mage.cards.o.OntarachieHunter.class));
        //cards.add(new SetCardInfo("Scaleblight Cutthroat", "103b", Rarity.RARE, mage.cards.s.ScaleblightCutthroat.class));
        //cards.add(new SetCardInfo("Oracle's Ploy", 104, Rarity.UNCOMMON, mage.cards.o.OraclesPloy.class));
        //cards.add(new SetCardInfo("Overwhelming Guilt", 105, Rarity.COMMON, mage.cards.o.OverwhelmingGuilt.class));
        //cards.add(new SetCardInfo("Parish Custodian", 106, Rarity.COMMON, mage.cards.p.ParishCustodian.class));
        //cards.add(new SetCardInfo("Reclaim the Devout", 107, Rarity.UNCOMMON, mage.cards.r.ReclaimTheDevout.class));
        //cards.add(new SetCardInfo("Returned Bokor", 108, Rarity.RARE, mage.cards.r.ReturnedBokor.class));
        //cards.add(new SetCardInfo("Scaleblight Warrior", 109, Rarity.COMMON, mage.cards.s.ScaleblightWarrior.class));
        //cards.add(new SetCardInfo("Shaman of the First Pact", 110, Rarity.RARE, mage.cards.s.ShamanOfTheFirstPact.class));
        //cards.add(new SetCardInfo("Sin Broker", 111, Rarity.UNCOMMON, mage.cards.s.SinBroker.class));
        //cards.add(new SetCardInfo("Souldebt Collector", 112, Rarity.COMMON, mage.cards.s.SouldebtCollector.class));
        //cards.add(new SetCardInfo("Spite Caster", 113, Rarity.COMMON, mage.cards.s.SpiteCaster.class));
        //cards.add(new SetCardInfo("Sporegraft", 114, Rarity.COMMON, mage.cards.s.Sporegraft.class));
        //cards.add(new SetCardInfo("Starving Swooprat", 115, Rarity.COMMON, mage.cards.s.StarvingSwooprat.class));
        //cards.add(new SetCardInfo("Stinghopper", 116, Rarity.COMMON, mage.cards.s.Stinghopper.class));
        //cards.add(new SetCardInfo("Tear to Shreds", 117, Rarity.COMMON, mage.cards.t.TearToShreds.class));
        //cards.add(new SetCardInfo("Terror of the Ontarachie", 118, Rarity.UNCOMMON, mage.cards.t.TerrorOfTheOntarachie.class));
        //cards.add(new SetCardInfo("Undying Watcher", 119, Rarity.COMMON, mage.cards.u.UndyingWatcher.class));
        //cards.add(new SetCardInfo("Vibrant Rapture", 120, Rarity.RARE, mage.cards.v.VibrantRapture.class));
        //cards.add(new SetCardInfo("Vindictive Abbot", 121, Rarity.COMMON, mage.cards.v.VindictiveAbbot.class));
        //cards.add(new SetCardInfo("Wailing Chorus", 122, Rarity.COMMON, mage.cards.w.WailingChorus.class));
        cards.add(new SetCardInfo("Wanderspore Terrapin", 123, Rarity.COMMON, mage.cards.w.WandersporeTerrapin.class));
        //cards.add(new SetCardInfo("Whispers of the Ontarachie", 124, Rarity.UNCOMMON, mage.cards.w.WhispersOfTheOntarachie.class));
        //cards.add(new SetCardInfo("Woopip Decomposition", 125, Rarity.COMMON, mage.cards.w.WoopipDecomposition.class));
        //cards.add(new SetCardInfo("Young Swooprat", 126, Rarity.UNCOMMON, mage.cards.y.YoungSwooprat.class));
        //cards.add(new SetCardInfo("Balloon Dragoon", 127, Rarity.COMMON, mage.cards.b.BalloonDragoon.class));
        //cards.add(new SetCardInfo("Band of Irregulars", 128, Rarity.UNCOMMON, mage.cards.b.BandOfIrregulars.class));
        cards.add(new SetCardInfo("Blazing Volley", 129, Rarity.COMMON, mage.cards.b.BlazingVolley.class));
        //cards.add(new SetCardInfo("Bogborn Charger", 130, Rarity.RARE, mage.cards.b.BogbornCharger.class));
        //cards.add(new SetCardInfo("Bogborn Exorcist", 131, Rarity.RARE, mage.cards.b.BogbornExorcist.class));
        //cards.add(new SetCardInfo("Bogstalker Snake", 132, Rarity.COMMON, mage.cards.b.BogstalkerSnake.class));
        //cards.add(new SetCardInfo("Bouquet Singer", 133, Rarity.UNCOMMON, mage.cards.b.BouquetSinger.class));
        //cards.add(new SetCardInfo("Brash Hunter", "134a", Rarity.RARE, mage.cards.b.BrashHunter.class));
        //cards.add(new SetCardInfo("Grisly Rougarou", "134b", Rarity.RARE, mage.cards.g.GrislyRougarou.class));
        //cards.add(new SetCardInfo("Burning Revelations", 135, Rarity.RARE, mage.cards.b.BurningRevelations.class));
        //cards.add(new SetCardInfo("Cataclysmic Preacher", 136, Rarity.COMMON, mage.cards.c.CataclysmicPreacher.class));
        //cards.add(new SetCardInfo("Curse of Uncertainty", 137, Rarity.RARE, mage.cards.c.CurseOfUncertainty.class));
        //cards.add(new SetCardInfo("Damning Flames", 138, Rarity.COMMON, mage.cards.d.DamningFlames.class));
        //cards.add(new SetCardInfo("Dazzling Festivities", 139, Rarity.RARE, mage.cards.d.DazzlingFestivities.class));
        //cards.add(new SetCardInfo("Disrupting Storms", 140, Rarity.COMMON, mage.cards.d.DisruptingStorms.class));
        //cards.add(new SetCardInfo("Elegant Strike", 141, Rarity.COMMON, mage.cards.e.ElegantStrike.class));
        //cards.add(new SetCardInfo("Encore of the Phoenix", 142, Rarity.MYTHIC, mage.cards.e.EncoreOfThePhoenix.class));
        //cards.add(new SetCardInfo("Exciting Band", 143, Rarity.RARE, mage.cards.e.ExcitingBand.class));
        //cards.add(new SetCardInfo("Faradia's Outrage", 144, Rarity.UNCOMMON, mage.cards.f.FaradiasOutrage.class));
        cards.add(new SetCardInfo("Fervent Strike", 145, Rarity.COMMON, mage.cards.f.FerventStrike.class));
        //cards.add(new SetCardInfo("Festival Rioters", 146, Rarity.COMMON, mage.cards.f.FestivalRioters.class));
        //cards.add(new SetCardInfo("Fool's Errand", 147, Rarity.UNCOMMON, mage.cards.f.FoolsErrand.class));
        //cards.add(new SetCardInfo("Gift of the Phoenix", 148, Rarity.COMMON, mage.cards.g.GiftOfThePhoenix.class));
        //cards.add(new SetCardInfo("Herald of Festivities", 149, Rarity.MYTHIC, mage.cards.h.HeraldOfFestivities.class));
        //cards.add(new SetCardInfo("Intoxicating Melody", 150, Rarity.COMMON, mage.cards.i.IntoxicatingMelody.class));
        //cards.add(new SetCardInfo("Lonely Devil", 151, Rarity.COMMON, mage.cards.l.LonelyDevil.class));
        //cards.add(new SetCardInfo("Lord's Voyage", 152, Rarity.UNCOMMON, mage.cards.l.LordsVoyage.class));
        //cards.add(new SetCardInfo("Lotus Studies", 153, Rarity.COMMON, mage.cards.l.LotusStudies.class));
        //cards.add(new SetCardInfo("Minister of Zealots", 154, Rarity.RARE, mage.cards.m.MinisterOfZealots.class));
        //cards.add(new SetCardInfo("Ontarachie Apex", 155, Rarity.RARE, mage.cards.o.OntarachieApex.class));
        //cards.add(new SetCardInfo("Passionate Congregation", 156, Rarity.COMMON, mage.cards.p.PassionateCongregation.class));
        //cards.add(new SetCardInfo("Pyrodancer", 157, Rarity.COMMON, mage.cards.p.Pyrodancer.class));
        //cards.add(new SetCardInfo("Radiant Outburst", 158, Rarity.UNCOMMON, mage.cards.r.RadiantOutburst.class));
        //cards.add(new SetCardInfo("Rallying Rector", 159, Rarity.COMMON, mage.cards.r.RallyingRector.class));
        cards.add(new SetCardInfo("Reformed Devil", 160, Rarity.COMMON, mage.cards.r.ReformedDevil.class));
        //cards.add(new SetCardInfo("Scuttling Bogbuster", 161, Rarity.UNCOMMON, mage.cards.s.ScuttlingBogbuster.class));
        //cards.add(new SetCardInfo("Shock and Awe", 162, Rarity.COMMON, mage.cards.s.ShockAndAwe.class));
        //cards.add(new SetCardInfo("Storehouse Collapse", 163, Rarity.UNCOMMON, mage.cards.s.StorehouseCollapse.class));
        //cards.add(new SetCardInfo("Streetside Entertainer", 164, Rarity.COMMON, mage.cards.s.StreetsideEntertainer.class));
        //cards.add(new SetCardInfo("Sudden Conversion", 165, Rarity.UNCOMMON, mage.cards.s.SuddenConversion.class));
        //cards.add(new SetCardInfo("Twirling Duet", 166, Rarity.UNCOMMON, mage.cards.t.TwirlingDuet.class));
        //cards.add(new SetCardInfo("Vivid March", 167, Rarity.RARE, mage.cards.v.VividMarch.class));
        //cards.add(new SetCardInfo("Zealous Scaleblight", 168, Rarity.UNCOMMON, mage.cards.z.ZealousScaleblight.class));
        //cards.add(new SetCardInfo("Ambushing Alligator", 169, Rarity.UNCOMMON, mage.cards.a.AmbushingAlligator.class));
        cards.add(new SetCardInfo("Artisan's Sorrow", 170, Rarity.COMMON, mage.cards.a.ArtisansSorrow.class));
        //cards.add(new SetCardInfo("Avatar of Plume de Val", 171, Rarity.MYTHIC, mage.cards.a.AvatarOfPlumeDeVal.class));
        //cards.add(new SetCardInfo("Bloomcrawler", 172, Rarity.COMMON, mage.cards.b.Bloomcrawler.class));
        //cards.add(new SetCardInfo("Coat in Petals", 173, Rarity.COMMON, mage.cards.c.CoatInPetals.class));
        //cards.add(new SetCardInfo("Commune with Kantra", 174, Rarity.COMMON, mage.cards.c.CommuneWithKantra.class));
        //cards.add(new SetCardInfo("Croakfolk Troubadour", 175, Rarity.COMMON, mage.cards.c.CroakfolkTroubadour.class));
        //cards.add(new SetCardInfo("Crown of Spores", 176, Rarity.COMMON, mage.cards.c.CrownOfSpores.class));
        //cards.add(new SetCardInfo("Curse of Encroaching Waters", 177, Rarity.UNCOMMON, mage.cards.c.CurseOfEncroachingWaters.class));
        //cards.add(new SetCardInfo("Curse of the Petrified", 178, Rarity.UNCOMMON, mage.cards.c.CurseOfThePetrified.class));
        //cards.add(new SetCardInfo("Curse of Tracking", 179, Rarity.RARE, mage.cards.c.CurseOfTracking.class));
        //cards.add(new SetCardInfo("Curse of Vulnerability", 180, Rarity.UNCOMMON, mage.cards.c.CurseOfVulnerability.class));
        //cards.add(new SetCardInfo("Cypress, the Wayfarer", 181, Rarity.MYTHIC, mage.cards.c.CypressTheWayfarer.class));
        //cards.add(new SetCardInfo("Fungal Whomper", 182, Rarity.RARE, mage.cards.f.FungalWhomper.class));
        //cards.add(new SetCardInfo("Jeama, Zoulev Queen", 183, Rarity.RARE, mage.cards.j.JeamaZoulevQueen.class));
        //cards.add(new SetCardInfo("Kantra of Bounty", 184, Rarity.MYTHIC, mage.cards.k.KantraOfBounty.class));
        //cards.add(new SetCardInfo("Kantra of Fortitude", 185, Rarity.COMMON, mage.cards.k.KantraOfFortitude.class));
        //cards.add(new SetCardInfo("Kantra of Old Majik", 186, Rarity.RARE, mage.cards.k.KantraOfOldMajik.class));
        //cards.add(new SetCardInfo("Kantra's Envoy", 187, Rarity.COMMON, mage.cards.k.KantrasEnvoy.class));
        //cards.add(new SetCardInfo("Lotus Feaster", 188, Rarity.COMMON, mage.cards.l.LotusFeaster.class));
        //cards.add(new SetCardInfo("Marsh's Veil", 189, Rarity.COMMON, mage.cards.m.MarshsVeil.class));
        //cards.add(new SetCardInfo("Mushroom Merchant", "190a", Rarity.RARE, mage.cards.m.MushroomMerchant.class));
        //cards.add(new SetCardInfo("Overgrowth Host", "190b", Rarity.RARE, mage.cards.o.OvergrowthHost.class));
        //cards.add(new SetCardInfo("Ontarachie Bushwhack", 191, Rarity.COMMON, mage.cards.o.OntarachieBushwhack.class));
        //cards.add(new SetCardInfo("Ontarachie Dryad", 192, Rarity.RARE, mage.cards.o.OntarachieDryad.class));
        //cards.add(new SetCardInfo("Ontarachie Emissary", 193, Rarity.UNCOMMON, mage.cards.o.OntarachieEmissary.class));
        //cards.add(new SetCardInfo("Ontarachie Forager", 194, Rarity.COMMON, mage.cards.o.OntarachieForager.class));
        //cards.add(new SetCardInfo("Overgrowth Instigator", 195, Rarity.UNCOMMON, mage.cards.o.OvergrowthInstigator.class));
        //cards.add(new SetCardInfo("Prized Marshcroaker", 196, Rarity.UNCOMMON, mage.cards.p.PrizedMarshcroaker.class));
        //cards.add(new SetCardInfo("Remarkable Hunter", 197, Rarity.COMMON, mage.cards.r.RemarkableHunter.class));
        //cards.add(new SetCardInfo("Serpentdancer Kantra", 198, Rarity.UNCOMMON, mage.cards.s.SerpentdancerKantra.class));
        cards.add(new SetCardInfo("Shelled Muckdweller", 199, Rarity.COMMON, mage.cards.s.ShelledMuckdweller.class));
        //cards.add(new SetCardInfo("Sporeflow Protector", 200, Rarity.RARE, mage.cards.s.SporeflowProtector.class));
        //cards.add(new SetCardInfo("Strike Down", 201, Rarity.COMMON, mage.cards.s.StrikeDown.class));
        //cards.add(new SetCardInfo("Tenacious Brawler", 202, Rarity.UNCOMMON, mage.cards.t.TenaciousBrawler.class));
        //cards.add(new SetCardInfo("Trufflefrog", 203, Rarity.COMMON, mage.cards.t.Trufflefrog.class));
        //cards.add(new SetCardInfo("Uncouth Ancestor", 204, Rarity.COMMON, mage.cards.u.UncouthAncestor.class));
        //cards.add(new SetCardInfo("Wild Festivities", 205, Rarity.RARE, mage.cards.w.WildFestivities.class));
        cards.add(new SetCardInfo("Wild Instincts", 206, Rarity.COMMON, mage.cards.w.WildInstincts.class));
        //cards.add(new SetCardInfo("Woopip Elder", 207, Rarity.COMMON, mage.cards.w.WoopipElder.class));
        //cards.add(new SetCardInfo("Woopip Wanderer", 208, Rarity.UNCOMMON, mage.cards.w.WoopipWanderer.class));
        //cards.add(new SetCardInfo("Zoulev Rites", 209, Rarity.RARE, mage.cards.z.ZoulevRites.class));
        //cards.add(new SetCardInfo("Zoulev Ritualist", 210, Rarity.UNCOMMON, mage.cards.z.ZoulevRitualist.class));
        //cards.add(new SetCardInfo("Adavene, Dean of the Arts", 211, Rarity.MYTHIC, mage.cards.a.AdaveneDeanOfTheArts.class));
        //cards.add(new SetCardInfo("Antonin Lazaire", 212, Rarity.MYTHIC, mage.cards.a.AntoninLazaire.class));
        //cards.add(new SetCardInfo("Determined Evangelist", 213, Rarity.UNCOMMON, mage.cards.d.DeterminedEvangelist.class));
        //cards.add(new SetCardInfo("Dramatic Artist", 214, Rarity.UNCOMMON, mage.cards.d.DramaticArtist.class));
        cards.add(new SetCardInfo("Erollin, Eccentric Collector", 215, Rarity.MYTHIC, mage.cards.e.ErollinEccentricCollector.class));
        //cards.add(new SetCardInfo("Faradia's Favored", 216, Rarity.UNCOMMON, mage.cards.f.FaradiasFavored.class));
        //cards.add(new SetCardInfo("Gift of the Bayou", 217, Rarity.UNCOMMON, mage.cards.g.GiftOfTheBayou.class));
        //cards.add(new SetCardInfo("Grindlesnap", 218, Rarity.RARE, mage.cards.g.Grindlesnap.class));
        //cards.add(new SetCardInfo("Irrigation Trawler", 219, Rarity.UNCOMMON, mage.cards.i.IrrigationTrawler.class));
        //cards.add(new SetCardInfo("Manhunter Kantra", 220, Rarity.UNCOMMON, mage.cards.m.ManhunterKantra.class));
        //cards.add(new SetCardInfo("Plume de Val Singer", 221, Rarity.UNCOMMON, mage.cards.p.PlumeDeValSinger.class));
        //cards.add(new SetCardInfo("Riverboat Assault", 222, Rarity.UNCOMMON, mage.cards.r.RiverboatAssault.class));
        //cards.add(new SetCardInfo("Smooth Musician", 223, Rarity.UNCOMMON, mage.cards.s.SmoothMusician.class));
        //cards.add(new SetCardInfo("Woopip Bruiser", 224, Rarity.UNCOMMON, mage.cards.w.WoopipBruiser.class));
        //cards.add(new SetCardInfo("Arcane Saxophone", 225, Rarity.UNCOMMON, mage.cards.a.ArcaneSaxophone.class));
        //cards.add(new SetCardInfo("Artisan's Fountain", 226, Rarity.UNCOMMON, mage.cards.a.ArtisansFountain.class));
        //cards.add(new SetCardInfo("Automated Maestromancer", 227, Rarity.RARE, mage.cards.a.AutomatedMaestromancer.class));
        //cards.add(new SetCardInfo("Bogchomper Juggernaut", 228, Rarity.COMMON, mage.cards.b.BogchomperJuggernaut.class));
        //cards.add(new SetCardInfo("Bogsworn Club", 229, Rarity.COMMON, mage.cards.b.BogswornClub.class));
        //cards.add(new SetCardInfo("Fleshcarver Knife", 230, Rarity.COMMON, mage.cards.f.FleshcarverKnife.class));
        cards.add(new SetCardInfo("Gilded Lotus", 231, Rarity.RARE, mage.cards.g.GildedLotus.class));
        //cards.add(new SetCardInfo("Improvising Automaton", 232, Rarity.COMMON, mage.cards.i.ImprovisingAutomaton.class));
        //cards.add(new SetCardInfo("Ornate Incense", 233, Rarity.COMMON, mage.cards.o.OrnateIncense.class));
        cards.add(new SetCardInfo("Prophetic Prism", 234, Rarity.COMMON, mage.cards.p.PropheticPrism.class));
        //cards.add(new SetCardInfo("Soul of New Alores", 235, Rarity.MYTHIC, mage.cards.s.SoulOfNewAlores.class));
        //cards.add(new SetCardInfo("Unicorn of the Vale", 236, Rarity.UNCOMMON, mage.cards.u.UnicornOfTheVale.class));
        //cards.add(new SetCardInfo("Zoulev Altar", 237, Rarity.UNCOMMON, mage.cards.z.ZoulevAltar.class));
        //cards.add(new SetCardInfo("Art Studio", 238, Rarity.UNCOMMON, mage.cards.a.ArtStudio.class));
        cards.add(new SetCardInfo("Blessed Mausoleum", 239, Rarity.UNCOMMON, mage.cards.b.BlessedMausoleum.class));
        cards.add(new SetCardInfo("Dangerous Territory", 240, Rarity.UNCOMMON, mage.cards.d.DangerousTerritory.class));
        cards.add(new SetCardInfo("Eerie Bayou", 241, Rarity.UNCOMMON, mage.cards.e.EerieBayou.class));
        cards.add(new SetCardInfo("Forlorn Ruin", 242, Rarity.UNCOMMON, mage.cards.f.ForlornRuin.class));
        cards.add(new SetCardInfo("Lakeside Park", 243, Rarity.UNCOMMON, mage.cards.l.LakesidePark.class));
        cards.add(new SetCardInfo("Mushroom Lagoon", 244, Rarity.UNCOMMON, mage.cards.m.MushroomLagoon.class));
        cards.add(new SetCardInfo("Prayer Hall", 245, Rarity.UNCOMMON, mage.cards.p.PrayerHall.class));
        cards.add(new SetCardInfo("Ritzy Parlor", 246, Rarity.UNCOMMON, mage.cards.r.RitzyParlor.class));
        cards.add(new SetCardInfo("Royal Domain", 247, Rarity.RARE, mage.cards.r.RoyalDomain.class));
        cards.add(new SetCardInfo("Sunlit Plaza", 248, Rarity.UNCOMMON, mage.cards.s.SunlitPlaza.class));
        cards.add(new SetCardInfo("Vacated Bar", 249, Rarity.UNCOMMON, mage.cards.v.VacatedBar.class));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class));
        cards.add(new SetCardInfo("Island", 251, Rarity.LAND, mage.cards.basiclands.Island.class));
        cards.add(new SetCardInfo("Swamp", 252, Rarity.LAND, mage.cards.basiclands.Swamp.class));
        cards.add(new SetCardInfo("Mountain", 253, Rarity.LAND, mage.cards.basiclands.Mountain.class));
        cards.add(new SetCardInfo("Forest", 254, Rarity.LAND, mage.cards.basiclands.Forest.class));
    }
}
