package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class HollowsOfLordran extends ExpansionSet {
    private static final HollowsOfLordran instance = new HollowsOfLordran();

    public static HollowsOfLordran getInstance() { return instance; }

    private HollowsOfLordran() {
        super("Hollows of Lordran", "HLW", ExpansionSet.buildDate(2018, 1, 21), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        cards.add(new SetCardInfo("Arrest", 1, Rarity.COMMON, mage.cards.a.Arrest.class));
        //cards.add(new SetCardInfo("Astora Elite", 2, Rarity.COMMON, mage.cards.a.AstoraElite.class));
        //cards.add(new SetCardInfo("Astora Outcast", 3, Rarity.UNCOMMON, mage.cards.a.AstoraOutcast.class));
        //cards.add(new SetCardInfo("Balder Knight", 4, Rarity.COMMON, mage.cards.b.BalderKnight.class));
        //cards.add(new SetCardInfo("Bell Gargoyles", 5, Rarity.COMMON, mage.cards.b.BellGargoyles.class));
        //cards.add(new SetCardInfo("Bonfire Keeper", 6, Rarity.COMMON, mage.cards.b.BonfireKeeper.class));
        //cards.add(new SetCardInfo("Brilliant Phantom", 7, Rarity.UNCOMMON, mage.cards.b.BrilliantPhantom.class));
        //cards.add(new SetCardInfo("Chosen by the Lords", 8, Rarity.RARE, mage.cards.c.ChosenByTheLords.class));
        //cards.add(new SetCardInfo("Darkbreaker Angel", 9, Rarity.MYTHIC, mage.cards.d.DarkbreakerAngel.class));
        //cards.add(new SetCardInfo("Darkmoon Deterrence", 10, Rarity.UNCOMMON, mage.cards.d.DarkmoonDeterrence.class));
        //cards.add(new SetCardInfo("Doomed Pilgrim", 11, Rarity.RARE, mage.cards.d.DoomedPilgrim.class));
        //cards.add(new SetCardInfo("Dull Defender", 12, Rarity.UNCOMMON, mage.cards.d.DullDefender.class));
        //cards.add(new SetCardInfo("Endless Encounters", 13, Rarity.RARE, mage.cards.e.EndlessEncounters.class));
        //cards.add(new SetCardInfo("Exiled Priestess", 14, Rarity.UNCOMMON, mage.cards.e.ExiledPriestess.class));
        //cards.add(new SetCardInfo("Expendable's Vigil", 15, Rarity.UNCOMMON, mage.cards.e.ExpendablesVigil.class));
        //cards.add(new SetCardInfo("Face the Impossible", 16, Rarity.COMMON, mage.cards.f.FaceTheImpossible.class));
        //cards.add(new SetCardInfo("Fade to Ash", 17, Rarity.COMMON, mage.cards.f.FadeToAsh.class));
        //cards.add(new SetCardInfo("Fallen Steed", 18, Rarity.COMMON, mage.cards.f.FallenSteed.class));
        //cards.add(new SetCardInfo("Gargoyle Helm", 19, Rarity.COMMON, mage.cards.g.GargoyleHelm.class));
        //cards.add(new SetCardInfo("Gwynevere's Benediction", 20, Rarity.UNCOMMON, mage.cards.g.GwyneveresBenediction.class));
        //cards.add(new SetCardInfo("Gwyn's Last Hope", 21, Rarity.RARE, mage.cards.g.GwynsLastHope.class));
        //cards.add(new SetCardInfo("Gwyn's Silver Knight", 22, Rarity.UNCOMMON, mage.cards.g.GwynsSilverKnight.class));
        //cards.add(new SetCardInfo("Havel, the Rock", 23, Rarity.MYTHIC, mage.cards.h.HavelTheRock.class));
        //cards.add(new SetCardInfo("Heavy Iron Armor", 24, Rarity.UNCOMMON, mage.cards.h.HeavyIronArmor.class));
        //cards.add(new SetCardInfo("Hollowed Hero", 25, Rarity.COMMON, mage.cards.h.HollowedHero.class));
        cards.add(new SetCardInfo("Imprisoned Hollow", 26, Rarity.COMMON, mage.cards.i.ImprisonedHollow.class));
        //cards.add(new SetCardInfo("Injured Paladin", 27, Rarity.COMMON, mage.cards.i.InjuredPaladin.class));
        //cards.add(new SetCardInfo("A Knight's Protection", 28, Rarity.UNCOMMON, mage.cards.a.AKnightsProtection.class));
        //cards.add(new SetCardInfo("Overcome the Odds", 29, Rarity.UNCOMMON, mage.cards.o.OvercomeTheOdds.class));
        //cards.add(new SetCardInfo("Paladin of Holy Relics", 30, Rarity.UNCOMMON, mage.cards.p.PaladinOfHolyRelics.class));
        //cards.add(new SetCardInfo("Pilgrim Phantom", 31, Rarity.COMMON, mage.cards.p.PilgrimPhantom.class));
        //cards.add(new SetCardInfo("Seeker of the Cure", 32, Rarity.COMMON, mage.cards.s.SeekerOfTheCure.class));
        //cards.add(new SetCardInfo("Sen's Iron Golem", 33, Rarity.RARE, mage.cards.s.SensIronGolem.class));
        //cards.add(new SetCardInfo("Solaire's Talisman", 34, Rarity.RARE, mage.cards.s.SolairesTalisman.class));
        //cards.add(new SetCardInfo("Soothing Sunlight", 35, Rarity.COMMON, mage.cards.s.SoothingSunlight.class));
        //cards.add(new SetCardInfo("Sunlight Paragon", 36, Rarity.RARE, mage.cards.s.SunlightParagon.class));
        //cards.add(new SetCardInfo("Sunlight Phantom", 37, Rarity.COMMON, mage.cards.s.SunlightPhantom.class));
        //cards.add(new SetCardInfo("Undead-Burg Guard", 38, Rarity.UNCOMMON, mage.cards.u.UndeadBurgGuard.class));
        //cards.add(new SetCardInfo("Velka's Justice", 39, Rarity.COMMON, mage.cards.v.VelkasJustice.class));
        //cards.add(new SetCardInfo("Velka's Missionary", 40, Rarity.COMMON, mage.cards.v.VelkasMissionary.class));
        //cards.add(new SetCardInfo("Victory In Numbers", 41, Rarity.COMMON, mage.cards.v.VictoryInNumbers.class));
        //cards.add(new SetCardInfo("Wondrous Incandescence", 42, Rarity.RARE, mage.cards.w.WondrousIncandescence.class));
        //cards.add(new SetCardInfo("Absorbed In Thought", 43, Rarity.COMMON, mage.cards.a.AbsorbedInThought.class));
        //cards.add(new SetCardInfo("Banish to the Painting", 44, Rarity.COMMON, mage.cards.b.BanishToThePainting.class));
        //cards.add(new SetCardInfo("Betrayer's Legacy", 45, Rarity.RARE, mage.cards.b.BetrayersLegacy.class));
        cards.add(new SetCardInfo("Big Hat Logan", 46, Rarity.RARE, mage.cards.b.BigHatLogan.class));
        //cards.add(new SetCardInfo("Blue Crystal Golem", 47, Rarity.COMMON, mage.cards.b.BlueCrystalGolem.class));
        cards.add(new SetCardInfo("Cancel", 48, Rarity.COMMON, mage.cards.c.Cancel.class));
        //cards.add(new SetCardInfo("Ciaran's Obsession", 49, Rarity.COMMON, mage.cards.c.CiaransObsession.class));
        //cards.add(new SetCardInfo("A Cold and Gentle Place", 50, Rarity.UNCOMMON, mage.cards.a.AColdAndGentlePlace.class));
        //cards.add(new SetCardInfo("Crossing the Fog", 51, Rarity.RARE, mage.cards.c.CrossingTheFog.class));
        //cards.add(new SetCardInfo("Crystalline Armor", 52, Rarity.UNCOMMON, mage.cards.c.CrystallineArmor.class));
        cards.add(new SetCardInfo("Crystallized Soldier", 53, Rarity.COMMON, mage.cards.c.CrystallizedSoldier.class));
        //cards.add(new SetCardInfo("Darkmoon Bow", 54, Rarity.RARE, mage.cards.d.DarkmoonBow.class));
        //cards.add(new SetCardInfo("Darkmoon Favor", 55, Rarity.UNCOMMON, mage.cards.d.DarkmoonFavor.class));
        //cards.add(new SetCardInfo("Darkroot Explorer", 56, Rarity.COMMON, mage.cards.d.DarkrootExplorer.class));
        //cards.add(new SetCardInfo("Darkroot Sorcerer", 57, Rarity.COMMON, mage.cards.d.DarkrootSorcerer.class));
        //cards.add(new SetCardInfo("Darkroot Spellguard", 58, Rarity.UNCOMMON, mage.cards.d.DarkrootSpellguard.class));
        //cards.add(new SetCardInfo("Demented Sorcerer", 59, Rarity.UNCOMMON, mage.cards.d.DementedSorcerer.class));
        //cards.add(new SetCardInfo("Dour Vagrant", 60, Rarity.RARE, mage.cards.d.DourVagrant.class));
        cards.add(new SetCardInfo("Essence Scatter", 61, Rarity.COMMON, mage.cards.e.EssenceScatter.class));
        //cards.add(new SetCardInfo("Eyes of the Darkmoon", 62, Rarity.UNCOMMON, mage.cards.e.EyesOfTheDarkmoon.class));
        //cards.add(new SetCardInfo("Flooding of New Londo", 63, Rarity.RARE, mage.cards.f.FloodingOfNewLondo.class));
        //cards.add(new SetCardInfo("Gwyndolin's Rebuke", 64, Rarity.UNCOMMON, mage.cards.g.GwyndolinsRebuke.class));
        //cards.add(new SetCardInfo("Logan's Isolation", 65, Rarity.RARE, mage.cards.l.LogansIsolation.class));
        //cards.add(new SetCardInfo("Masked Illusion", 66, Rarity.COMMON, mage.cards.m.MaskedIllusion.class));
        //cards.add(new SetCardInfo("Moonlight Butterfly", 67, Rarity.RARE, mage.cards.m.MoonlightButterfly.class));
        //cards.add(new SetCardInfo("Overwhelming Burden", 68, Rarity.COMMON, mage.cards.o.OverwhelmingBurden.class));
        //cards.add(new SetCardInfo("Pale Dragonoid", 69, Rarity.COMMON, mage.cards.p.PaleDragonoid.class));
        //cards.add(new SetCardInfo("Path of Brilliance", 70, Rarity.UNCOMMON, mage.cards.p.PathOfBrilliance.class));
        //cards.add(new SetCardInfo("Petrification Curse", 71, Rarity.UNCOMMON, mage.cards.p.PetrificationCurse.class));
        //cards.add(new SetCardInfo("Ring Collector", 72, Rarity.MYTHIC, mage.cards.r.RingCollector.class));
        //cards.add(new SetCardInfo("Ruin Haunt", 73, Rarity.COMMON, mage.cards.r.RuinHaunt.class));
        //cards.add(new SetCardInfo("Scholar's Catalyst", 74, Rarity.COMMON, mage.cards.s.ScholarsCatalyst.class));
        //cards.add(new SetCardInfo("Sealed Spirit", 75, Rarity.COMMON, mage.cards.s.SealedSpirit.class));
        //cards.add(new SetCardInfo("Seath, Scaleless Betrayer", 76, Rarity.MYTHIC, mage.cards.s.SeathScalelessBetrayer.class));
        //cards.add(new SetCardInfo("Seek the Past", 77, Rarity.UNCOMMON, mage.cards.s.SeekThePast.class));
        //cards.add(new SetCardInfo("Sidetracked", 78, Rarity.UNCOMMON, mage.cards.s.Sidetracked.class));
        //cards.add(new SetCardInfo("Soul Confluence", 79, Rarity.MYTHIC, mage.cards.s.SoulConfluence.class));
        //cards.add(new SetCardInfo("Soulmass Witch", 80, Rarity.COMMON, mage.cards.s.SoulmassWitch.class));
        //cards.add(new SetCardInfo("Time for Contemplation", 81, Rarity.COMMON, mage.cards.t.TimeForContemplation.class));
        //cards.add(new SetCardInfo("Traveler's Protection", 82, Rarity.COMMON, mage.cards.t.TravelersProtection.class));
        //cards.add(new SetCardInfo("Valley Drake", 83, Rarity.UNCOMMON, mage.cards.v.ValleyDrake.class));
        //cards.add(new SetCardInfo("Vinheim Agent", 84, Rarity.COMMON, mage.cards.v.VinheimAgent.class));
        //cards.add(new SetCardInfo("Vinheim Infiltrator", 85, Rarity.UNCOMMON, mage.cards.v.VinheimInfiltrator.class));
        //cards.add(new SetCardInfo("Artorias, the Abyss-Walker", 86, Rarity.RARE, mage.cards.a.ArtoriasTheAbyssWalker.class));
        //cards.add(new SetCardInfo("Artorias's Cursed Greatsword", 87, Rarity.RARE, mage.cards.a.ArtoriassCursedGreatsword.class));
        //cards.add(new SetCardInfo("Asylum Demon", 88, Rarity.COMMON, mage.cards.a.AsylumDemon.class));
        //cards.add(new SetCardInfo("Balder Captain", 89, Rarity.RARE, mage.cards.b.BalderCaptain.class));
        //cards.add(new SetCardInfo("Barbaric Cleric", 90, Rarity.COMMON, mage.cards.b.BarbaricCleric.class));
        //cards.add(new SetCardInfo("Barbed Blade", 91, Rarity.COMMON, mage.cards.b.BarbedBlade.class));
        //cards.add(new SetCardInfo("Black Knight Armor", 92, Rarity.UNCOMMON, mage.cards.b.BlackKnightArmor.class));
        //cards.add(new SetCardInfo("Centipede Demon", 93, Rarity.UNCOMMON, mage.cards.c.CentipedeDemon.class));
        //cards.add(new SetCardInfo("Consumed by the Abyss", 94, Rarity.COMMON, mage.cards.c.ConsumedByTheAbyss.class));
        //cards.add(new SetCardInfo("Countless Failures", 95, Rarity.UNCOMMON, mage.cards.c.CountlessFailures.class));
        //cards.add(new SetCardInfo("Darkwraith Captain", 96, Rarity.UNCOMMON, mage.cards.d.DarkwraithCaptain.class));
        //cards.add(new SetCardInfo("Deceitful Stab", 97, Rarity.COMMON, mage.cards.d.DeceitfulStab.class));
        cards.add(new SetCardInfo("Duress", 98, Rarity.COMMON, mage.cards.d.Duress.class));
        //cards.add(new SetCardInfo("Fall From Favor", 99, Rarity.RARE, mage.cards.f.FallFromFavor.class));
        //cards.add(new SetCardInfo("Fallen Champion", 100, Rarity.UNCOMMON, mage.cards.f.FallenChampion.class));
        //cards.add(new SetCardInfo("Fallen Farmer", 101, Rarity.UNCOMMON, mage.cards.f.FallenFarmer.class));
        //cards.add(new SetCardInfo("Forsaken Adventurer", 102, Rarity.COMMON, mage.cards.f.ForsakenAdventurer.class));
        //cards.add(new SetCardInfo("Futile Pursuit", 103, Rarity.RARE, mage.cards.f.FutilePursuit.class));
        //cards.add(new SetCardInfo("Grim Determination", 104, Rarity.COMMON, mage.cards.g.GrimDetermination.class));
        //cards.add(new SetCardInfo("Gwyn's Black Knight", 105, Rarity.UNCOMMON, mage.cards.g.GwynsBlackKnight.class));
        //cards.add(new SetCardInfo("Hollow Victory", 106, Rarity.UNCOMMON, mage.cards.h.HollowVictory.class));
        //cards.add(new SetCardInfo("Humanity Hunter", 107, Rarity.COMMON, mage.cards.h.HumanityHunter.class));
        //cards.add(new SetCardInfo("Hungering Knight", 108, Rarity.COMMON, mage.cards.h.HungeringKnight.class));
        //cards.add(new SetCardInfo("Izalith's Ruination", 109, Rarity.UNCOMMON, mage.cards.i.IzalithsRuination.class));
        //cards.add(new SetCardInfo("Journey's End", 110, Rarity.UNCOMMON, mage.cards.j.JourneysEnd.class));
        //cards.add(new SetCardInfo("Kalameet's Grasp", 111, Rarity.COMMON, mage.cards.k.KalameetsGrasp.class));
        cards.add(new SetCardInfo("Mindless Hollow", 112, Rarity.COMMON, mage.cards.m.MindlessHollow.class));
        //cards.add(new SetCardInfo("Nito, the Gravelord", 113, Rarity.MYTHIC, mage.cards.n.NitoTheGravelord.class));
        //cards.add(new SetCardInfo("Nito's Miasma", 114, Rarity.UNCOMMON, mage.cards.n.NitosMiasma.class));
        //cards.add(new SetCardInfo("Offering of Humanity", 115, Rarity.COMMON, mage.cards.o.OfferingOfHumanity.class));
        //cards.add(new SetCardInfo("Parasitic Wallhugger", 116, Rarity.UNCOMMON, mage.cards.p.ParasiticWallhugger.class));
        //cards.add(new SetCardInfo("Reign of the Dark Lord", 117, Rarity.RARE, mage.cards.r.ReignOfTheDarkLord.class));
        //cards.add(new SetCardInfo("Ruin Delver", 118, Rarity.COMMON, mage.cards.r.RuinDelver.class));
        //cards.add(new SetCardInfo("Sanity Melt", 119, Rarity.COMMON, mage.cards.s.SanityMelt.class));
        //cards.add(new SetCardInfo("Sewer Nibbler", 120, Rarity.COMMON, mage.cards.s.SewerNibbler.class));
        //cards.add(new SetCardInfo("Sin Caller", 121, Rarity.RARE, mage.cards.s.SinCaller.class));
        //cards.add(new SetCardInfo("Sin Cultist", 122, Rarity.UNCOMMON, mage.cards.s.SinCultist.class));
        //cards.add(new SetCardInfo("Soul Pursuit", 123, Rarity.COMMON, mage.cards.s.SoulPursuit.class));
        //cards.add(new SetCardInfo("Soulcleaver", 124, Rarity.MYTHIC, mage.cards.s.Soulcleaver.class));
        //cards.add(new SetCardInfo("Titanite Demon", 125, Rarity.COMMON, mage.cards.t.TitaniteDemon.class));
        //cards.add(new SetCardInfo("Velka's Crow", 126, Rarity.COMMON, mage.cards.v.VelkasCrow.class));
        //cards.add(new SetCardInfo("Venomous Bandit", 127, Rarity.RARE, mage.cards.v.VenomousBandit.class));
        //cards.add(new SetCardInfo("Adventurer's Enthusiasm", 128, Rarity.COMMON, mage.cards.a.AdventurersEnthusiasm.class));
        //cards.add(new SetCardInfo("Batwing Demon", 129, Rarity.UNCOMMON, mage.cards.b.BatwingDemon.class));
        //cards.add(new SetCardInfo("Bloodied Shotel", 130, Rarity.UNCOMMON, mage.cards.b.BloodiedShotel.class));
        //cards.add(new SetCardInfo("Capra Demon", 131, Rarity.COMMON, mage.cards.c.CapraDemon.class));
        //cards.add(new SetCardInfo("Ceaseless Destruction", 132, Rarity.COMMON, mage.cards.c.CeaselessDestruction.class));
        //cards.add(new SetCardInfo("Ceaseless Discharge", 133, Rarity.MYTHIC, mage.cards.c.CeaselessDischarge.class));
        cards.add(new SetCardInfo("Crazed Butcher", 134, Rarity.COMMON, mage.cards.c.CrazedButcher.class));
        //cards.add(new SetCardInfo("Cruel Lunatic", 135, Rarity.RARE, mage.cards.c.CruelLunatic.class));
        //cards.add(new SetCardInfo("Daughter of Chaos", 136, Rarity.COMMON, mage.cards.d.DaughterOfChaos.class));
        //cards.add(new SetCardInfo("Demon Firesage", 137, Rarity.UNCOMMON, mage.cards.d.DemonFiresage.class));
        //cards.add(new SetCardInfo("Dragon-Path Daredevil", 138, Rarity.UNCOMMON, mage.cards.d.DragonPathDaredevil.class));
        //cards.add(new SetCardInfo("Dragon-Path Ravager", 139, Rarity.UNCOMMON, mage.cards.d.DragonPathRavager.class));
        //cards.add(new SetCardInfo("Dragonslayer's Strike", 140, Rarity.COMMON, mage.cards.d.DragonslayersStrike.class));
        //cards.add(new SetCardInfo("Ecstatic Prayer", 141, Rarity.COMMON, mage.cards.e.EcstaticPrayer.class));
        //cards.add(new SetCardInfo("Fire Orb", 142, Rarity.COMMON, mage.cards.f.FireOrb.class));
        //cards.add(new SetCardInfo("The First Flame", 143, Rarity.MYTHIC, mage.cards.t.TheFirstFlame.class));
        //cards.add(new SetCardInfo("Flame Storm", 144, Rarity.RARE, mage.cards.f.FlameStorm.class));
        //cards.add(new SetCardInfo("Gatekeeper Hellkite", 145, Rarity.RARE, mage.cards.g.GatekeeperHellkite.class));
        //cards.add(new SetCardInfo("Grim Mercenary", 146, Rarity.UNCOMMON, mage.cards.g.GrimMercenary.class));
        //cards.add(new SetCardInfo("Heir of Chaos", 147, Rarity.UNCOMMON, mage.cards.h.HeirOfChaos.class));
        //cards.add(new SetCardInfo("Jolly Cooperation", 148, Rarity.RARE, mage.cards.j.JollyCooperation.class));
        //cards.add(new SetCardInfo("Kalameet's Gaze", 149, Rarity.UNCOMMON, mage.cards.k.KalameetsGaze.class));
        //cards.add(new SetCardInfo("Lightning Spear", 150, Rarity.COMMON, mage.cards.l.LightningSpear.class));
        //cards.add(new SetCardInfo("Linking the Flame", 151, Rarity.RARE, mage.cards.l.LinkingTheFlame.class));
        //cards.add(new SetCardInfo("Magma Spider", 152, Rarity.COMMON, mage.cards.m.MagmaSpider.class));
        //cards.add(new SetCardInfo("Molten Fury", 153, Rarity.COMMON, mage.cards.m.MoltenFury.class));
        //cards.add(new SetCardInfo("Paragon Transformation", 154, Rarity.UNCOMMON, mage.cards.p.ParagonTransformation.class));
        //cards.add(new SetCardInfo("Path of Violence", 155, Rarity.UNCOMMON, mage.cards.p.PathOfViolence.class));
        cards.add(new SetCardInfo("Pillar of Flame", 156, Rarity.COMMON, mage.cards.p.PillarOfFlame.class));
        //cards.add(new SetCardInfo("Power Within", 157, Rarity.RARE, mage.cards.p.PowerWithin.class));
        //cards.add(new SetCardInfo("Pyromancer's Flame", 158, Rarity.COMMON, mage.cards.p.PyromancersFlame.class));
        //cards.add(new SetCardInfo("Pyromancer's Wisdom", 159, Rarity.UNCOMMON, mage.cards.p.PyromancersWisdom.class));
        cards.add(new SetCardInfo("Quelaag, Chaos Witch", 160, Rarity.RARE, mage.cards.q.QuelaagChaosWitch.class));
        //cards.add(new SetCardInfo("Quelaag's Furysword", 161, Rarity.RARE, mage.cards.q.QuelaagsFurysword.class));
        //cards.add(new SetCardInfo("Quelana's Pupil", 162, Rarity.COMMON, mage.cards.q.QuelanasPupil.class));
        //cards.add(new SetCardInfo("Rotting Hellhound", 163, Rarity.COMMON, mage.cards.r.RottingHellhound.class));
        //cards.add(new SetCardInfo("Solaire's Madness", 164, Rarity.UNCOMMON, mage.cards.s.SolairesMadness.class));
        //cards.add(new SetCardInfo("Student of the Dragon-Path", 165, Rarity.COMMON, mage.cards.s.StudentOfTheDragonPath.class));
        //cards.add(new SetCardInfo("Sunlight Spear", 166, Rarity.UNCOMMON, mage.cards.s.SunlightSpear.class));
        //cards.add(new SetCardInfo("Taurus Demon", 167, Rarity.COMMON, mage.cards.t.TaurusDemon.class));
        //cards.add(new SetCardInfo("Vinheim Disgrace", 168, Rarity.COMMON, mage.cards.v.VinheimDisgrace.class));
        //cards.add(new SetCardInfo("Wandering Doomsayer", 169, Rarity.COMMON, mage.cards.w.WanderingDoomsayer.class));
        //cards.add(new SetCardInfo("Adventurer's Rest", 170, Rarity.UNCOMMON, mage.cards.a.AdventurersRest.class));
        //cards.add(new SetCardInfo("Ancient Extinction", 171, Rarity.RARE, mage.cards.a.AncientExtinction.class));
        //cards.add(new SetCardInfo("Blight Hatching", 172, Rarity.RARE, mage.cards.b.BlightHatching.class));
        //cards.add(new SetCardInfo("Blight Slime", 173, Rarity.UNCOMMON, mage.cards.b.BlightSlime.class));
        cards.add(new SetCardInfo("Blighted Barbarian", 174, Rarity.COMMON, mage.cards.b.BlightedBarbarian.class));
        //cards.add(new SetCardInfo("Burrowing Rockwurm", 175, Rarity.UNCOMMON, mage.cards.b.BurrowingRockwurm.class));
        //cards.add(new SetCardInfo("Darkroot Ambusher", 176, Rarity.COMMON, mage.cards.d.DarkrootAmbusher.class));
        //cards.add(new SetCardInfo("Darkroot Hunt-Pack", 177, Rarity.RARE, mage.cards.d.DarkrootHuntPack.class));
        //cards.add(new SetCardInfo("Darkroot Mists", 178, Rarity.UNCOMMON, mage.cards.d.DarkrootMists.class));
        //cards.add(new SetCardInfo("Darkroot Tracker", 179, Rarity.UNCOMMON, mage.cards.d.DarkrootTracker.class));
        //cards.add(new SetCardInfo("Defend the Grave", 180, Rarity.COMMON, mage.cards.d.DefendTheGrave.class));
        //cards.add(new SetCardInfo("Degradation", 181, Rarity.COMMON, mage.cards.d.Degradation.class));
        //cards.add(new SetCardInfo("Dragon-Path Aspirant", 182, Rarity.COMMON, mage.cards.d.DragonPathAspirant.class));
        //cards.add(new SetCardInfo("Dragon-Path Corruptor", 183, Rarity.COMMON, mage.cards.d.DragonPathCorruptor.class));
        //cards.add(new SetCardInfo("Executioner's Hunger", 184, Rarity.COMMON, mage.cards.e.ExecutionersHunger.class));
        //cards.add(new SetCardInfo("Explorer's Reward", 185, Rarity.MYTHIC, mage.cards.e.ExplorersReward.class));
        //cards.add(new SetCardInfo("Fading Sage", 186, Rarity.COMMON, mage.cards.f.FadingSage.class));
        //cards.add(new SetCardInfo("Gaping Dragon", 187, Rarity.MYTHIC, mage.cards.g.GapingDragon.class));
        cards.add(new SetCardInfo("Giant Growth", 188, Rarity.COMMON, mage.cards.g.GiantGrowth.class));
        //cards.add(new SetCardInfo("Giant's Skills", 189, Rarity.UNCOMMON, mage.cards.g.GiantsSkills.class));
        //cards.add(new SetCardInfo("Gifter of Dragonscales", 190, Rarity.UNCOMMON, mage.cards.g.GifterOfDragonscales.class));
        //cards.add(new SetCardInfo("Gough, Hawk-Eye Hunter", 191, Rarity.RARE, mage.cards.g.GoughHawkEyeHunter.class));
        //cards.add(new SetCardInfo("Gough's Greatbow", 192, Rarity.RARE, mage.cards.g.GoughsGreatbow.class));
        //cards.add(new SetCardInfo("Great Hammer", 193, Rarity.COMMON, mage.cards.g.GreatHammer.class));
        //cards.add(new SetCardInfo("Gwynevere's Guidance", 194, Rarity.COMMON, mage.cards.g.GwyneveresGuidance.class));
        //cards.add(new SetCardInfo("Hunter Hydra", 195, Rarity.RARE, mage.cards.h.HunterHydra.class));
        //cards.add(new SetCardInfo("Intrepid Companions", 196, Rarity.COMMON, mage.cards.i.IntrepidCompanions.class));
        //cards.add(new SetCardInfo("Keeper of the Old Fire", 197, Rarity.RARE, mage.cards.k.KeeperOfTheOldFire.class));
        //cards.add(new SetCardInfo("Londo Showdown", 198, Rarity.UNCOMMON, mage.cards.l.LondoShowdown.class));
        //cards.add(new SetCardInfo("Masterless Boar", 199, Rarity.COMMON, mage.cards.m.MasterlessBoar.class));
        //cards.add(new SetCardInfo("Murakumo", 200, Rarity.UNCOMMON, mage.cards.m.Murakumo.class));
        cards.add(new SetCardInfo("Mushroom Family", 201, Rarity.UNCOMMON, mage.cards.m.MushroomFamily.class));
        //cards.add(new SetCardInfo("Oolacile Behemoth", 202, Rarity.COMMON, mage.cards.o.OolacileBehemoth.class));
        //cards.add(new SetCardInfo("Provoke the Primeval", 203, Rarity.UNCOMMON, mage.cards.p.ProvokeThePrimeval.class));
        //cards.add(new SetCardInfo("Pyromantic Shaman", 204, Rarity.COMMON, mage.cards.p.PyromanticShaman.class));
        //cards.add(new SetCardInfo("The Road Ahead", 205, Rarity.RARE, mage.cards.t.TheRoadAhead.class));
        //cards.add(new SetCardInfo("Search for Dusk", 206, Rarity.UNCOMMON, mage.cards.s.SearchForDusk.class));
        cards.add(new SetCardInfo("Sentinel Spider", 207, Rarity.COMMON, mage.cards.s.SentinelSpider.class));
        //cards.add(new SetCardInfo("Servant of the Fair Lady", 208, Rarity.COMMON, mage.cards.s.ServantOfTheFairLady.class));
        //cards.add(new SetCardInfo("Stranded Hydra", 209, Rarity.UNCOMMON, mage.cards.s.StrandedHydra.class));
        //cards.add(new SetCardInfo("Sudden Courage", 210, Rarity.COMMON, mage.cards.s.SuddenCourage.class));
        //cards.add(new SetCardInfo("Uncover the Lost", 211, Rarity.COMMON, mage.cards.u.UncoverTheLost.class));
        //cards.add(new SetCardInfo("Ciaran, Blade of the Lords", 212, Rarity.RARE, mage.cards.c.CiaranBladeOfTheLords.class));
        //cards.add(new SetCardInfo("Darkmoon Phantom", 213, Rarity.UNCOMMON, mage.cards.d.DarkmoonPhantom.class));
        //cards.add(new SetCardInfo("Draconic Traveler", 214, Rarity.UNCOMMON, mage.cards.d.DraconicTraveler.class));
        //cards.add(new SetCardInfo("Dusk, Princess of Oolacile", 215, Rarity.RARE, mage.cards.d.DuskPrincessOfOolacile.class));
        //cards.add(new SetCardInfo("The Fair Lady", 216, Rarity.RARE, mage.cards.t.TheFairLady.class));
        //cards.add(new SetCardInfo("Gwyn, Lord of Sunlight", 217, Rarity.MYTHIC, mage.cards.g.GwynLordOfSunlight.class));
        //cards.add(new SetCardInfo("Lautrec, the Embraced", 218, Rarity.RARE, mage.cards.l.LautrecTheEmbraced.class));
        //cards.add(new SetCardInfo("Manus, Father of the Abyss", 219, Rarity.MYTHIC, mage.cards.m.ManusFatherOfTheAbyss.class));
        //cards.add(new SetCardInfo("Moonlight Diviner", 220, Rarity.UNCOMMON, mage.cards.m.MoonlightDiviner.class));
        //cards.add(new SetCardInfo("Oscar, Undead Questant", 221, Rarity.RARE, mage.cards.o.OscarUndeadQuestant.class));
        //cards.add(new SetCardInfo("Pass On", 222, Rarity.UNCOMMON, mage.cards.p.PassOn.class));
        //cards.add(new SetCardInfo("Priest of Velka", 223, Rarity.UNCOMMON, mage.cards.p.PriestOfVelka.class));
        //cards.add(new SetCardInfo("Priscilla, Painting Protector", 224, Rarity.RARE, mage.cards.p.PriscillaPaintingProtector.class));
        cards.add(new SetCardInfo("Quelana, Mother of Pyromancy", 225, Rarity.RARE, mage.cards.q.QuelanaMotherOfPyromancy.class));
        //cards.add(new SetCardInfo("Relentless Marauder", 226, Rarity.UNCOMMON, mage.cards.r.RelentlessMarauder.class));
        //cards.add(new SetCardInfo("Sanctuary Manticore", 227, Rarity.UNCOMMON, mage.cards.s.SanctuaryManticore.class));
        //cards.add(new SetCardInfo("Shrewd Collectors", 228, Rarity.UNCOMMON, mage.cards.s.ShrewdCollectors.class));
        //cards.add(new SetCardInfo("Siegmeyer, Errant Ally", 229, Rarity.RARE, mage.cards.s.SiegmeyerErrantAlly.class));
        //cards.add(new SetCardInfo("Sif, Great Grey Wolf", 230, Rarity.RARE, mage.cards.s.SifGreatGreyWolf.class));
        //cards.add(new SetCardInfo("Solaire, Seeker of Sunlight", 231, Rarity.RARE, mage.cards.s.SolaireSeekerOfSunlight.class));
        //cards.add(new SetCardInfo("Stalking Phantom", 232, Rarity.UNCOMMON, mage.cards.s.StalkingPhantom.class));
        //cards.add(new SetCardInfo("Thorned Knight", 233, Rarity.UNCOMMON, mage.cards.t.ThornedKnight.class));
        //cards.add(new SetCardInfo("Trusty Patches", 234, Rarity.MYTHIC, mage.cards.t.TrustyPatches.class));
        //cards.add(new SetCardInfo("Crystal Lizard", 235, Rarity.COMMON, mage.cards.c.CrystalLizard.class));
        //cards.add(new SetCardInfo("Estus Flask", 236, Rarity.COMMON, mage.cards.e.EstusFlask.class));
        //cards.add(new SetCardInfo("Everlasting Dragon", 237, Rarity.MYTHIC, mage.cards.e.EverlastingDragon.class));
        //cards.add(new SetCardInfo("Firebomb", 238, Rarity.COMMON, mage.cards.f.Firebomb.class));
        //cards.add(new SetCardInfo("Havel's Dragon Tooth", 239, Rarity.RARE, mage.cards.h.HavelsDragonTooth.class));
        //cards.add(new SetCardInfo("Zweihander", 240, Rarity.COMMON, mage.cards.z.Zweihander.class));
        //cards.add(new SetCardInfo("Abandoned Bonfire", 241, Rarity.COMMON, mage.cards.a.AbandonedBonfire.class));
        //cards.add(new SetCardInfo("Decaying Domain", 242, Rarity.UNCOMMON, mage.cards.d.DecayingDomain.class));
        cards.add(new SetCardInfo("Evolving Wilds", 243, Rarity.COMMON, mage.cards.e.EvolvingWilds.class));
        //cards.add(new SetCardInfo("Firelink Shrine", 244, Rarity.RARE, mage.cards.f.FirelinkShrine.class));
        //cards.add(new SetCardInfo("Frosted Sanctuary", 245, Rarity.UNCOMMON, mage.cards.f.FrostedSanctuary.class));
        //cards.add(new SetCardInfo("Hero's Rest", 246, Rarity.UNCOMMON, mage.cards.h.HerosRest.class));
        //cards.add(new SetCardInfo("Lava Roots", 247, Rarity.UNCOMMON, mage.cards.l.LavaRoots.class));
        //cards.add(new SetCardInfo("Sinister Ruins", 248, Rarity.UNCOMMON, mage.cards.s.SinisterRuins.class));
        //cards.add(new SetCardInfo("Watery Depths", 249, Rarity.UNCOMMON, mage.cards.w.WateryDepths.class));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class));
        cards.add(new SetCardInfo("Island", 251, Rarity.LAND, mage.cards.basiclands.Island.class));
        cards.add(new SetCardInfo("Swamp", 252, Rarity.LAND, mage.cards.basiclands.Swamp.class));
        cards.add(new SetCardInfo("Mountain", 253, Rarity.LAND, mage.cards.basiclands.Mountain.class));
        cards.add(new SetCardInfo("Forest", 254, Rarity.LAND, mage.cards.basiclands.Forest.class));
    }
}
