package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class Jannada extends ExpansionSet {
    private static final Jannada instance = new Jannada();

    public static Jannada getInstance() { return instance; }

    private Jannada() {
        super("Jannada", "JAN", ExpansionSet.buildDate(2017, 11, 5), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Akugan Hookmaster", 1, Rarity.COMMON, mage.cards.a.AkuganHookmaster.class));
        //cards.add(new SetCardInfo("Akugan War-Priest", 2, Rarity.COMMON, mage.cards.a.AkuganWarPriest.class));
        //cards.add(new SetCardInfo("Ancestral Aid", 3, Rarity.UNCOMMON, mage.cards.a.AncestralAid.class));
        //cards.add(new SetCardInfo("Bond of Souls", 4, Rarity.UNCOMMON, mage.cards.b.BondOfSouls.class));
        //cards.add(new SetCardInfo("Command to Charge", 5, Rarity.COMMON, mage.cards.c.CommandToCharge.class));
        //cards.add(new SetCardInfo("Commander's Coup", 6, Rarity.MYTHIC, mage.cards.c.CommandersCoup.class));
        //cards.add(new SetCardInfo("Constitution", 7, Rarity.COMMON, mage.cards.c.Constitution.class));
        //cards.add(new SetCardInfo("Craft the Sands", 8, Rarity.COMMON, mage.cards.c.CraftTheSands.class));
        //cards.add(new SetCardInfo("Dance of Healing", 9, Rarity.UNCOMMON, mage.cards.d.DanceOfHealing.class));
        //cards.add(new SetCardInfo("Deflect", 10, Rarity.UNCOMMON, mage.cards.d.Deflect.class));
        //cards.add(new SetCardInfo("Divine Downfall", 11, Rarity.COMMON, mage.cards.d.DivineDownfall.class));
        //cards.add(new SetCardInfo("Duneshaper", 12, Rarity.UNCOMMON, mage.cards.d.Duneshaper.class));
        //cards.add(new SetCardInfo("Eshaha, Divine General", 13, Rarity.MYTHIC, mage.cards.e.EshahaDivineGeneral.class));
        //cards.add(new SetCardInfo("Felidar Noble", 14, Rarity.UNCOMMON, mage.cards.f.FelidarNoble.class));
        //cards.add(new SetCardInfo("Glare of the Nkisi", 15, Rarity.UNCOMMON, mage.cards.g.GlareOfTheNkisi.class));
        //cards.add(new SetCardInfo("Glory of Akuga", 16, Rarity.RARE, mage.cards.g.GloryOfAkuga.class));
        //cards.add(new SetCardInfo("Heralded Arrival", 17, Rarity.COMMON, mage.cards.h.HeraldedArrival.class));
        //cards.add(new SetCardInfo("Inaki Sage", 18, Rarity.COMMON, mage.cards.i.InakiSage.class));
        //cards.add(new SetCardInfo("Kelada Chieftan", 19, Rarity.COMMON, mage.cards.k.KeladaChieftan.class));
        //cards.add(new SetCardInfo("Ladder to the Heavens", 20, Rarity.RARE, mage.cards.l.LadderToTheHeavens.class));
        //cards.add(new SetCardInfo("Lightbearer Angel", 21, Rarity.RARE, mage.cards.l.LightbearerAngel.class));
        //cards.add(new SetCardInfo("Nimbus Hippo", 22, Rarity.UNCOMMON, mage.cards.n.NimbusHippo.class));
        //cards.add(new SetCardInfo("Noble Presence", 23, Rarity.COMMON, mage.cards.n.NoblePresence.class));
        //cards.add(new SetCardInfo("Nomad's Wanderings", 24, Rarity.COMMON, mage.cards.n.NomadsWanderings.class));
        //cards.add(new SetCardInfo("Prairie Tromper", 25, Rarity.RARE, mage.cards.p.PrairieTromper.class));
        //cards.add(new SetCardInfo("Radiant Dawn", 26, Rarity.RARE, mage.cards.r.RadiantDawn.class));
        //cards.add(new SetCardInfo("Sahai Awakening", 27, Rarity.RARE, mage.cards.s.SahaiAwakening.class));
        cards.add(new SetCardInfo("Sahai Nomad", 28, Rarity.COMMON, mage.cards.s.SahaiNomad.class));
        //cards.add(new SetCardInfo("Sand-Dune Sentinel", 29, Rarity.COMMON, mage.cards.s.SandDuneSentinel.class));
        //cards.add(new SetCardInfo("Scion of the Sahai", 30, Rarity.COMMON, mage.cards.s.ScionOfTheSahai.class));
        //cards.add(new SetCardInfo("Spectral Sonata", 31, Rarity.COMMON, mage.cards.s.SpectralSonata.class));
        //cards.add(new SetCardInfo("Sunstrider Blademaster", 32, Rarity.RARE, mage.cards.s.SunstriderBlademaster.class));
        //cards.add(new SetCardInfo("Sunstrider's Skill", 33, Rarity.COMMON, mage.cards.s.SunstridersSkill.class));
        //cards.add(new SetCardInfo("Tumbiri Elder", 34, Rarity.COMMON, mage.cards.t.TumbiriElder.class));
        //cards.add(new SetCardInfo("Tumbiri Venturer", 35, Rarity.COMMON, mage.cards.t.TumbiriVenturer.class));
        //cards.add(new SetCardInfo("Valorous Stand", 36, Rarity.COMMON, mage.cards.v.ValorousStand.class));
        //cards.add(new SetCardInfo("Warchant Champion", 37, Rarity.COMMON, mage.cards.w.WarchantChampion.class));
        //cards.add(new SetCardInfo("Wildebeest Herd", 38, Rarity.UNCOMMON, mage.cards.w.WildebeestHerd.class));
        //cards.add(new SetCardInfo("Apprentice Lunamancer", 39, Rarity.COMMON, mage.cards.a.ApprenticeLunamancer.class));
        //cards.add(new SetCardInfo("Arcane Reversal", 40, Rarity.UNCOMMON, mage.cards.a.ArcaneReversal.class));
        //cards.add(new SetCardInfo("Bazaar Illusionist", 41, Rarity.RARE, mage.cards.b.BazaarIllusionist.class));
        //cards.add(new SetCardInfo("Cirrus Winder", 42, Rarity.COMMON, mage.cards.c.CirrusWinder.class));
        //cards.add(new SetCardInfo("Devastating Sandstorm", 43, Rarity.RARE, mage.cards.d.DevastatingSandstorm.class));
        //cards.add(new SetCardInfo("Downpour Shaman", 44, Rarity.UNCOMMON, mage.cards.d.DownpourShaman.class));
        //cards.add(new SetCardInfo("Dream Plunderer", 45, Rarity.UNCOMMON, mage.cards.d.DreamPlunderer.class));
        //cards.add(new SetCardInfo("Effortless Denial", 46, Rarity.UNCOMMON, mage.cards.e.EffortlessDenial.class));
        //cards.add(new SetCardInfo("Eoncraft", 47, Rarity.MYTHIC, mage.cards.e.Eoncraft.class));
        //cards.add(new SetCardInfo("Erratic Shapeshifter", 48, Rarity.RARE, mage.cards.e.ErraticShapeshifter.class));
        //cards.add(new SetCardInfo("Exchange of Tales", 49, Rarity.COMMON, mage.cards.e.ExchangeOfTales.class));
        //cards.add(new SetCardInfo("Ferry Across", 50, Rarity.COMMON, mage.cards.f.FerryAcross.class));
        //cards.add(new SetCardInfo("Flash Flooding", 51, Rarity.UNCOMMON, mage.cards.f.FlashFlooding.class));
        //cards.add(new SetCardInfo("Fledgling Thunderbird", 52, Rarity.COMMON, mage.cards.f.FledglingThunderbird.class));
        //cards.add(new SetCardInfo("Forceful Rest", 53, Rarity.COMMON, mage.cards.f.ForcefulRest.class));
        //cards.add(new SetCardInfo("Induced Paralysis", 54, Rarity.COMMON, mage.cards.i.InducedParalysis.class));
        //cards.add(new SetCardInfo("Lost at Sea", 55, Rarity.COMMON, mage.cards.l.LostAtSea.class));
        //cards.add(new SetCardInfo("Make Way", 56, Rarity.UNCOMMON, mage.cards.m.MakeWay.class));
        //cards.add(new SetCardInfo("Monarch of Galaxies", 57, Rarity.MYTHIC, mage.cards.m.MonarchOfGalaxies.class));
        //cards.add(new SetCardInfo("Mystic Rebuttal", 58, Rarity.COMMON, mage.cards.m.MysticRebuttal.class));
        //cards.add(new SetCardInfo("Oracle's Sight", 59, Rarity.COMMON, mage.cards.o.OraclesSight.class));
        //cards.add(new SetCardInfo("Owlkeeper", 60, Rarity.COMMON, mage.cards.o.Owlkeeper.class));
        //cards.add(new SetCardInfo("Rainforest Sphinx", 61, Rarity.RARE, mage.cards.r.RainforestSphinx.class));
        //cards.add(new SetCardInfo("Reality Inversion", 62, Rarity.RARE, mage.cards.r.RealityInversion.class));
        //cards.add(new SetCardInfo("Rushriver Elemental", 63, Rarity.UNCOMMON, mage.cards.r.RushriverElemental.class));
        //cards.add(new SetCardInfo("Rushriver Hunter", 64, Rarity.COMMON, mage.cards.r.RushriverHunter.class));
        //cards.add(new SetCardInfo("Scion of Stars", 65, Rarity.COMMON, mage.cards.s.ScionOfStars.class));
        //cards.add(new SetCardInfo("Seek the Farworld", 66, Rarity.COMMON, mage.cards.s.SeekTheFarworld.class));
        //cards.add(new SetCardInfo("Skyroamer", 67, Rarity.UNCOMMON, mage.cards.s.Skyroamer.class));
        //cards.add(new SetCardInfo("Skyspan Thunderbird", 68, Rarity.RARE, mage.cards.s.SkyspanThunderbird.class));
        //cards.add(new SetCardInfo("Spellscale Drake", 69, Rarity.COMMON, mage.cards.s.SpellscaleDrake.class));
        //cards.add(new SetCardInfo("Spellscatter Hex", 70, Rarity.COMMON, mage.cards.s.SpellscatterHex.class));
        //cards.add(new SetCardInfo("Spellshroud Spirit", 71, Rarity.COMMON, mage.cards.s.SpellshroudSpirit.class));
        //cards.add(new SetCardInfo("Stargazing", 72, Rarity.COMMON, mage.cards.s.Stargazing.class));
        //cards.add(new SetCardInfo("Tikoloshe Warrior", 73, Rarity.UNCOMMON, mage.cards.t.TikolosheWarrior.class));
        //cards.add(new SetCardInfo("Trick Questions", 74, Rarity.RARE, mage.cards.t.TrickQuestions.class));
        //cards.add(new SetCardInfo("Unearthly Exchange", 75, Rarity.COMMON, mage.cards.u.UnearthlyExchange.class));
        //cards.add(new SetCardInfo("Windwinder Serpent", 76, Rarity.COMMON, mage.cards.w.WindwinderSerpent.class));
        //cards.add(new SetCardInfo("Accursed Mentoring", 77, Rarity.RARE, mage.cards.a.AccursedMentoring.class));
        //cards.add(new SetCardInfo("Adze Predator", 78, Rarity.COMMON, mage.cards.a.AdzePredator.class));
        //cards.add(new SetCardInfo("Asanbosam", 79, Rarity.UNCOMMON, mage.cards.a.Asanbosam.class));
        //cards.add(new SetCardInfo("Bloodcrawler Adze", 80, Rarity.UNCOMMON, mage.cards.b.BloodcrawlerAdze.class));
        //cards.add(new SetCardInfo("Bog Dweller", 81, Rarity.RARE, mage.cards.b.BogDweller.class));
        //cards.add(new SetCardInfo("Cadaverous Simian", 82, Rarity.COMMON, mage.cards.c.CadaverousSimian.class));
        cards.add(new SetCardInfo("Corpse Churn", 83, Rarity.COMMON, mage.cards.c.CorpseChurn.class));
        //cards.add(new SetCardInfo("Corpse Cultivation", 84, Rarity.COMMON, mage.cards.c.CorpseCultivation.class));
        //cards.add(new SetCardInfo("Cursechanter", 85, Rarity.COMMON, mage.cards.c.Cursechanter.class));
        //cards.add(new SetCardInfo("Dark Soothsaying", 86, Rarity.COMMON, mage.cards.d.DarkSoothsaying.class));
        //cards.add(new SetCardInfo("Deadland Cackler", 87, Rarity.COMMON, mage.cards.d.DeadlandCackler.class));
        //cards.add(new SetCardInfo("Deathburst Hex", 88, Rarity.COMMON, mage.cards.d.DeathburstHex.class));
        //cards.add(new SetCardInfo("Deathcaster Lich", 89, Rarity.RARE, mage.cards.d.DeathcasterLich.class));
        //cards.add(new SetCardInfo("Demonic Scarring", 90, Rarity.COMMON, mage.cards.d.DemonicScarring.class));
        //cards.add(new SetCardInfo("Doom of Fools", 91, Rarity.MYTHIC, mage.cards.d.DoomOfFools.class));
        //cards.add(new SetCardInfo("Dreadlaugh Kinship", 92, Rarity.RARE, mage.cards.d.DreadlaughKinship.class));
        //cards.add(new SetCardInfo("Dreadlaugh Pup", 93, Rarity.UNCOMMON, mage.cards.d.DreadlaughPup.class));
        //cards.add(new SetCardInfo("Dreadlaugh Scavenger", 94, Rarity.COMMON, mage.cards.d.DreadlaughScavenger.class));
        //cards.add(new SetCardInfo("Dreadlaugh Shaman", 95, Rarity.RARE, mage.cards.d.DreadlaughShaman.class));
        //cards.add(new SetCardInfo("Duskstrider", 96, Rarity.COMMON, mage.cards.d.Duskstrider.class));
        //cards.add(new SetCardInfo("Gozani's Torture", 97, Rarity.COMMON, mage.cards.g.GozanisTorture.class));
        //cards.add(new SetCardInfo("Kakrako's Pawn", 98, Rarity.COMMON, mage.cards.k.KakrakosPawn.class));
        //cards.add(new SetCardInfo("Kholomodumo", 99, Rarity.COMMON, mage.cards.k.Kholomodumo.class));
        //cards.add(new SetCardInfo("Lurking Adze", 100, Rarity.COMMON, mage.cards.l.LurkingAdze.class));
        //cards.add(new SetCardInfo("Malevolent Might", 101, Rarity.COMMON, mage.cards.m.MalevolentMight.class));
        //cards.add(new SetCardInfo("Nightwater Assailant", 102, Rarity.COMMON, mage.cards.n.NightwaterAssailant.class));
        //cards.add(new SetCardInfo("Nightwater Terror", 103, Rarity.UNCOMMON, mage.cards.n.NightwaterTerror.class));
        //cards.add(new SetCardInfo("Shady Dealings", 104, Rarity.RARE, mage.cards.s.ShadyDealings.class));
        //cards.add(new SetCardInfo("Sickening Song", 105, Rarity.COMMON, mage.cards.s.SickeningSong.class));
        //cards.add(new SetCardInfo("Skittering Siege", 106, Rarity.UNCOMMON, mage.cards.s.SkitteringSiege.class));
        //cards.add(new SetCardInfo("Soulsnatch", 107, Rarity.COMMON, mage.cards.s.Soulsnatch.class));
        //cards.add(new SetCardInfo("Swarm of Locusts", 108, Rarity.RARE, mage.cards.s.SwarmOfLocusts.class));
        //cards.add(new SetCardInfo("Throatcutter", 109, Rarity.UNCOMMON, mage.cards.t.Throatcutter.class));
        //cards.add(new SetCardInfo("Throne of Madness", 110, Rarity.UNCOMMON, mage.cards.t.ThroneOfMadness.class));
        //cards.add(new SetCardInfo("Twisted Mercy", 111, Rarity.UNCOMMON, mage.cards.t.TwistedMercy.class));
        //cards.add(new SetCardInfo("Wandering Necromancer", 112, Rarity.RARE, mage.cards.w.WanderingNecromancer.class));
        //cards.add(new SetCardInfo("Wasteland Hermit", 113, Rarity.UNCOMMON, mage.cards.w.WastelandHermit.class));
        //cards.add(new SetCardInfo("Wasteland Scrounger", 114, Rarity.COMMON, mage.cards.w.WastelandScrounger.class));
        //cards.add(new SetCardInfo("Battleflight Manticore", 115, Rarity.RARE, mage.cards.b.BattleflightManticore.class));
        //cards.add(new SetCardInfo("Berserker's Rage", 116, Rarity.COMMON, mage.cards.b.BerserkersRage.class));
        //cards.add(new SetCardInfo("Blademaster Nomad", 117, Rarity.UNCOMMON, mage.cards.b.BlademasterNomad.class));
        //cards.add(new SetCardInfo("Cataclysmic Eruption", 118, Rarity.RARE, mage.cards.c.CataclysmicEruption.class));
        //cards.add(new SetCardInfo("Chorus of Thunder", 119, Rarity.COMMON, mage.cards.c.ChorusOfThunder.class));
        //cards.add(new SetCardInfo("Earthen Vengeance", 120, Rarity.UNCOMMON, mage.cards.e.EarthenVengeance.class));
        //cards.add(new SetCardInfo("Eloko Scavenger", 121, Rarity.COMMON, mage.cards.e.ElokoScavenger.class));
        cards.add(new SetCardInfo("Eloko Skullcarver", 122, Rarity.COMMON, mage.cards.e.ElokoSkullcarver.class));
        //cards.add(new SetCardInfo("Emotion Manipulation", 123, Rarity.UNCOMMON, mage.cards.e.EmotionManipulation.class));
        //cards.add(new SetCardInfo("Faralyn's Gambit", 124, Rarity.RARE, mage.cards.f.FaralynsGambit.class));
        //cards.add(new SetCardInfo("Firstblade Elder", 125, Rarity.COMMON, mage.cards.f.FirstbladeElder.class));
        //cards.add(new SetCardInfo("Flamepact Shaman", 126, Rarity.UNCOMMON, mage.cards.f.FlamepactShaman.class));
        cards.add(new SetCardInfo("Fling", 127, Rarity.COMMON, mage.cards.f.Fling.class));
        //cards.add(new SetCardInfo("From the Treetops", 128, Rarity.COMMON, mage.cards.f.FromTheTreetops.class));
        //cards.add(new SetCardInfo("Goblin Explorer", 129, Rarity.RARE, mage.cards.g.GoblinExplorer.class));
        //cards.add(new SetCardInfo("Impulsive Melody", 130, Rarity.COMMON, mage.cards.i.ImpulsiveMelody.class));
        //cards.add(new SetCardInfo("Incendiary Revel", 131, Rarity.MYTHIC, mage.cards.i.IncendiaryRevel.class));
        //cards.add(new SetCardInfo("Junmra's Attendant", 132, Rarity.COMMON, mage.cards.j.JunmrasAttendant.class));
        //cards.add(new SetCardInfo("Lava Torrent", 133, Rarity.COMMON, mage.cards.l.LavaTorrent.class));
        //cards.add(new SetCardInfo("Magefire Phoenix", 134, Rarity.MYTHIC, mage.cards.m.MagefirePhoenix.class));
        //cards.add(new SetCardInfo("Many-Handed Master", 135, Rarity.UNCOMMON, mage.cards.m.ManyHandedMaster.class));
        //cards.add(new SetCardInfo("Niniki Hunter", 136, Rarity.COMMON, mage.cards.n.NinikiHunter.class));
        //cards.add(new SetCardInfo("Phoenix Flames", 137, Rarity.UNCOMMON, mage.cards.p.PhoenixFlames.class));
        //cards.add(new SetCardInfo("Pillage and Plunder", 138, Rarity.UNCOMMON, mage.cards.p.PillageAndPlunder.class));
        //cards.add(new SetCardInfo("Raging Blaze", 139, Rarity.UNCOMMON, mage.cards.r.RagingBlaze.class));
        //cards.add(new SetCardInfo("Raniko Arsonist", 140, Rarity.COMMON, mage.cards.r.RanikoArsonist.class));
        //cards.add(new SetCardInfo("Raniko Cavalry", 141, Rarity.COMMON, mage.cards.r.RanikoCavalry.class));
        //cards.add(new SetCardInfo("Raniko Fireshaper", 142, Rarity.RARE, mage.cards.r.RanikoFireshaper.class));
        //cards.add(new SetCardInfo("Ruthless Skyclaw", 143, Rarity.RARE, mage.cards.r.RuthlessSkyclaw.class));
        //cards.add(new SetCardInfo("Sandwalker", 144, Rarity.COMMON, mage.cards.s.Sandwalker.class));
        //cards.add(new SetCardInfo("Snakewielder Niniki", 145, Rarity.COMMON, mage.cards.s.SnakewielderNiniki.class));
        //cards.add(new SetCardInfo("Squallwing Screecher", 146, Rarity.RARE, mage.cards.s.SquallwingScreecher.class));
        //cards.add(new SetCardInfo("Stampodon Rider", 147, Rarity.COMMON, mage.cards.s.StampodonRider.class));
        //cards.add(new SetCardInfo("Thousand Strikes", 148, Rarity.COMMON, mage.cards.t.ThousandStrikes.class));
        //cards.add(new SetCardInfo("Trial By Fire", 149, Rarity.COMMON, mage.cards.t.TrialByFire.class));
        //cards.add(new SetCardInfo("Tumbiri Master", 150, Rarity.COMMON, mage.cards.t.TumbiriMaster.class));
        //cards.add(new SetCardInfo("Volcanic Bonfire", 151, Rarity.UNCOMMON, mage.cards.v.VolcanicBonfire.class));
        cards.add(new SetCardInfo("Wrangle", 152, Rarity.COMMON, mage.cards.w.Wrangle.class));
        //cards.add(new SetCardInfo("Beckon Growth", 153, Rarity.UNCOMMON, mage.cards.b.BeckonGrowth.class));
        //cards.add(new SetCardInfo("Bog Tusker", 154, Rarity.COMMON, mage.cards.b.BogTusker.class));
        //cards.add(new SetCardInfo("Brutal Hunter", 155, Rarity.UNCOMMON, mage.cards.b.BrutalHunter.class));
        //cards.add(new SetCardInfo("Call of the Oasis", 156, Rarity.COMMON, mage.cards.c.CallOfTheOasis.class));
        cards.add(new SetCardInfo("The Circle of Life", 157, Rarity.MYTHIC, mage.cards.t.TheCircleOfLife.class));
        //cards.add(new SetCardInfo("Clean Shot", 158, Rarity.COMMON, mage.cards.c.CleanShot.class));
        //cards.add(new SetCardInfo("Collective Pilgrimage", 159, Rarity.COMMON, mage.cards.c.CollectivePilgrimage.class));
        cards.add(new SetCardInfo("Cultivate", 160, Rarity.COMMON, mage.cards.c.Cultivate.class));
        //cards.add(new SetCardInfo("Deathcradle Weaver", 161, Rarity.COMMON, mage.cards.d.DeathcradleWeaver.class));
        //cards.add(new SetCardInfo("Dragon Trapper", 162, Rarity.UNCOMMON, mage.cards.d.DragonTrapper.class));
        //cards.add(new SetCardInfo("Enforcer of the Wild", 163, Rarity.RARE, mage.cards.e.EnforcerOfTheWild.class));
        cards.add(new SetCardInfo("Giant Growth", 164, Rarity.COMMON, mage.cards.g.GiantGrowth.class));
        //cards.add(new SetCardInfo("Graceful Abada", 165, Rarity.COMMON, mage.cards.g.GracefulAbada.class));
        //cards.add(new SetCardInfo("Grootslang Dreadwalkers", 166, Rarity.UNCOMMON, mage.cards.g.GrootslangDreadwalkers.class));
        //cards.add(new SetCardInfo("Grootslang Stampede", 167, Rarity.RARE, mage.cards.g.GrootslangStampede.class));
        //cards.add(new SetCardInfo("Hiutha, Kelada Wildborn", 168, Rarity.RARE, mage.cards.h.HiuthaKeladaWildborn.class));
        //cards.add(new SetCardInfo("Hohoja, One with the Jungle", 169, Rarity.MYTHIC, mage.cards.h.HohojaOneWithTheJungle.class));
        //cards.add(new SetCardInfo("Hydra Scavenger", 170, Rarity.RARE, mage.cards.h.HydraScavenger.class));
        //cards.add(new SetCardInfo("Junmra's Blessing", 171, Rarity.COMMON, mage.cards.j.JunmrasBlessing.class));
        cards.add(new SetCardInfo("Kelada Outrider", 172, Rarity.COMMON, mage.cards.k.KeladaOutrider.class));
        //cards.add(new SetCardInfo("Kumra Dryad", 173, Rarity.RARE, mage.cards.k.KumraDryad.class));
        //cards.add(new SetCardInfo("Kumra Wilddancer", 174, Rarity.COMMON, mage.cards.k.KumraWilddancer.class));
        //cards.add(new SetCardInfo("Maul", 175, Rarity.COMMON, mage.cards.m.Maul.class));
        //cards.add(new SetCardInfo("Moonmulch Umdhelbi", 176, Rarity.COMMON, mage.cards.m.MoonmulchUmdhelbi.class));
        //cards.add(new SetCardInfo("Nomadic Druid", 177, Rarity.COMMON, mage.cards.n.NomadicDruid.class));
        //cards.add(new SetCardInfo("Primordial Rampage", 178, Rarity.UNCOMMON, mage.cards.p.PrimordialRampage.class));
        //cards.add(new SetCardInfo("Sahai Sandwurm", 179, Rarity.COMMON, mage.cards.s.SahaiSandwurm.class));
        //cards.add(new SetCardInfo("Sahai Wayfarer", 180, Rarity.UNCOMMON, mage.cards.s.SahaiWayfarer.class));
        //cards.add(new SetCardInfo("Scavenging Tiger", 181, Rarity.COMMON, mage.cards.s.ScavengingTiger.class));
        //cards.add(new SetCardInfo("Shaman of the Cycle", 182, Rarity.RARE, mage.cards.s.ShamanOfTheCycle.class));
        //cards.add(new SetCardInfo("Snakeform Mystic", 183, Rarity.COMMON, mage.cards.s.SnakeformMystic.class));
        //cards.add(new SetCardInfo("Verdant Grandeur", 184, Rarity.COMMON, mage.cards.v.VerdantGrandeur.class));
        //cards.add(new SetCardInfo("Walking Villages", 185, Rarity.UNCOMMON, mage.cards.w.WalkingVillages.class));
        //cards.add(new SetCardInfo("Wasteland Akhlut", 186, Rarity.UNCOMMON, mage.cards.w.WastelandAkhlut.class));
        //cards.add(new SetCardInfo("Wild Beckoning", 187, Rarity.COMMON, mage.cards.w.WildBeckoning.class));
        //cards.add(new SetCardInfo("Wild Emissary", 188, Rarity.COMMON, mage.cards.w.WildEmissary.class));
        //cards.add(new SetCardInfo("Wildbond Hunter", 189, Rarity.UNCOMMON, mage.cards.w.WildbondHunter.class));
        //cards.add(new SetCardInfo("Bazaar Crook", 190, Rarity.RARE, mage.cards.b.BazaarCrook.class));
        //cards.add(new SetCardInfo("Faralyn, Doyen Polymorphist", 191, Rarity.MYTHIC, mage.cards.f.FaralynDoyenPolymorphist.class));
        //cards.add(new SetCardInfo("Flametwist", 192, Rarity.RARE, mage.cards.f.Flametwist.class));
        //cards.add(new SetCardInfo("Gozani, Enforcer of the Cycle", 193, Rarity.MYTHIC, mage.cards.g.GozaniEnforcerOfTheCycle.class));
        //cards.add(new SetCardInfo("Grootslang Groundshaker", 194, Rarity.UNCOMMON, mage.cards.g.GrootslangGroundshaker.class));
        //cards.add(new SetCardInfo("Hellfire Channeler", 195, Rarity.RARE, mage.cards.h.HellfireChanneler.class));
        cards.add(new SetCardInfo("Junmra, Wild Sovereign", 196, Rarity.MYTHIC, mage.cards.j.JunmraWildSovereign.class));
        //cards.add(new SetCardInfo("Kakrako, Lord of Nightwater", 197, Rarity.MYTHIC, mage.cards.k.KakrakoLordOfNightwater.class));
        //cards.add(new SetCardInfo("Kumra Lorekeeper", 198, Rarity.UNCOMMON, mage.cards.k.KumraLorekeeper.class));
        //cards.add(new SetCardInfo("Liege of the Grasslands", 199, Rarity.RARE, mage.cards.l.LiegeOfTheGrasslands.class));
        //cards.add(new SetCardInfo("Loam Predator", 200, Rarity.UNCOMMON, mage.cards.l.LoamPredator.class));
        cards.add(new SetCardInfo("Lord of Extinction", 201, Rarity.RARE, mage.cards.l.LordOfExtinction.class));
        //cards.add(new SetCardInfo("Marrowscythe Ravager", 202, Rarity.UNCOMMON, mage.cards.m.MarrowscytheRavager.class));
        //cards.add(new SetCardInfo("Mindprobe", 203, Rarity.UNCOMMON, mage.cards.m.Mindprobe.class));
        //cards.add(new SetCardInfo("Narset of the Farworld", 204, Rarity.MYTHIC, mage.cards.n.NarsetOfTheFarworld.class));
        //cards.add(new SetCardInfo("Nkisi Trickster", 205, Rarity.UNCOMMON, mage.cards.n.NkisiTrickster.class));
        //cards.add(new SetCardInfo("Noble Abada", 206, Rarity.UNCOMMON, mage.cards.n.NobleAbada.class));
        //cards.add(new SetCardInfo("Rawaya, the Wanderer", 207, Rarity.RARE, mage.cards.r.RawayaTheWanderer.class));
        //cards.add(new SetCardInfo("Sahai Firebeast", 208, Rarity.RARE, mage.cards.s.SahaiFirebeast.class));
        //cards.add(new SetCardInfo("Sandstorm Sovereign", 209, Rarity.RARE, mage.cards.s.SandstormSovereign.class));
        //cards.add(new SetCardInfo("Skill of Masters", 210, Rarity.UNCOMMON, mage.cards.s.SkillOfMasters.class));
        //cards.add(new SetCardInfo("Spellmaw Crocodile", 211, Rarity.RARE, mage.cards.s.SpellmawCrocodile.class));
        //cards.add(new SetCardInfo("Thunderbird's Song", 212, Rarity.UNCOMMON, mage.cards.t.ThunderbirdsSong.class));
        //cards.add(new SetCardInfo("Tikoloshe Mistmage", 213, Rarity.UNCOMMON, mage.cards.t.TikolosheMistmage.class));
        cards.add(new SetCardInfo("Uaria, King of Akuga", 214, Rarity.RARE, mage.cards.u.UariaKingOfAkuga.class));
        //cards.add(new SetCardInfo("Ancient Prism", 215, Rarity.COMMON, mage.cards.a.AncientPrism.class));
        cards.add(new SetCardInfo("Golem of the Lost Temple", 216, Rarity.COMMON, mage.cards.g.GolemOfTheLostTemple.class));
        //cards.add(new SetCardInfo("Ice Golem", 217, Rarity.COMMON, mage.cards.i.IceGolem.class));
        //cards.add(new SetCardInfo("Iron Spear", 218, Rarity.COMMON, mage.cards.i.IronSpear.class));
        //cards.add(new SetCardInfo("Ritualist's Mask", 219, Rarity.UNCOMMON, mage.cards.r.RitualistsMask.class));
        //cards.add(new SetCardInfo("Savage's Boomerang", 220, Rarity.UNCOMMON, mage.cards.s.SavagesBoomerang.class));
        cards.add(new SetCardInfo("Dewdrop Rainforest", 221, Rarity.UNCOMMON, mage.cards.d.DewdropRainforest.class));
        cards.add(new SetCardInfo("Flooded Bog", 222, Rarity.UNCOMMON, mage.cards.f.FloodedBog.class));
        cards.add(new SetCardInfo("Nimbus Maze", 223, Rarity.UNCOMMON, mage.cards.n.NimbusMaze.class));
        cards.add(new SetCardInfo("Ominous Caldera", 224, Rarity.UNCOMMON, mage.cards.o.OminousCaldera.class));
        cards.add(new SetCardInfo("Overgrown Ruins", 225, Rarity.UNCOMMON, mage.cards.o.OvergrownRuins.class));
        cards.add(new SetCardInfo("Savage Wildlands", 226, Rarity.UNCOMMON, mage.cards.s.SavageWildlands.class));
        cards.add(new SetCardInfo("Savannah Encampment", 227, Rarity.UNCOMMON, mage.cards.s.SavannahEncampment.class));
        cards.add(new SetCardInfo("Splendid Oasis", 228, Rarity.UNCOMMON, mage.cards.s.SplendidOasis.class));
        cards.add(new SetCardInfo("Tattered Temple", 229, Rarity.UNCOMMON, mage.cards.t.TatteredTemple.class));
        //cards.add(new SetCardInfo("Temple to the Farworld", 230, Rarity.UNCOMMON, mage.cards.t.TempleToTheFarworld.class));
        cards.add(new SetCardInfo("Totemic Waterfall", 231, Rarity.UNCOMMON, mage.cards.t.TotemicWaterfall.class));
        //cards.add(new SetCardInfo("Unspoiled Expanse", 232, Rarity.COMMON, mage.cards.u.UnspoiledExpanse.class));
        cards.add(new SetCardInfo("Plains", 233, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 234, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 235, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 236, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 237, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 238, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 239, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 240, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 241, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 242, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
    }
}
