package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class Rakoa extends ExpansionSet {
    private static final Rakoa instance = new Rakoa();

    public static Rakoa getInstance() { return instance; }

    private Rakoa() {
        super("Rakoa", "RAK", ExpansionSet.buildDate(2018, 8, 30), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Ancestral Marking", 1, Rarity.UNCOMMON, mage.cards.a.AncestralMarking.class));
        //cards.add(new SetCardInfo("Assemble the Voyagers", 2, Rarity.COMMON, mage.cards.a.AssembleTheVoyagers.class));
        //cards.add(new SetCardInfo("Avatar of the Expanse", 3, Rarity.MYTHIC, mage.cards.a.AvatarOfTheExpanse.class));
        //cards.add(new SetCardInfo("Beached", 4, Rarity.COMMON, mage.cards.b.Beached.class));
        //cards.add(new SetCardInfo("Broken Grove Protectors", 5, Rarity.UNCOMMON, mage.cards.b.BrokenGroveProtectors.class));
        //cards.add(new SetCardInfo("Communal Dwelling", 6, Rarity.COMMON, mage.cards.c.CommunalDwelling.class));
        //cards.add(new SetCardInfo("Defining Confrontation", 7, Rarity.UNCOMMON, mage.cards.d.DefiningConfrontation.class));
        //cards.add(new SetCardInfo("Devourer Tanifa", 8, Rarity.RARE, mage.cards.d.DevourerTanifa.class));
        //cards.add(new SetCardInfo("Divine Amalgam", 9, Rarity.RARE, mage.cards.d.DivineAmalgam.class));
        //cards.add(new SetCardInfo("Elipo Ono Mentor", 10, Rarity.COMMON, mage.cards.e.ElipoOnoMentor.class));
        //cards.add(new SetCardInfo("Elipo Ono Sentinels", 11, Rarity.UNCOMMON, mage.cards.e.ElipoOnoSentinels.class));
        //cards.add(new SetCardInfo("Fieldwatcher Nuno", 12, Rarity.COMMON, mage.cards.f.FieldwatcherNuno.class));
        //cards.add(new SetCardInfo("Golden Savior", 13, Rarity.UNCOMMON, mage.cards.g.GoldenSavior.class));
        //cards.add(new SetCardInfo("Guardian Tanifa", 14, Rarity.UNCOMMON, mage.cards.g.GuardianTanifa.class));
        //cards.add(new SetCardInfo("Keen Sea-Eagle", 15, Rarity.RARE, mage.cards.k.KeenSeaEagle.class));
        //cards.add(new SetCardInfo("Kohea's Brilliance", 16, Rarity.COMMON, mage.cards.k.KoheasBrilliance.class));
        //cards.add(new SetCardInfo("Kohea's Griffin", 17, Rarity.COMMON, mage.cards.k.KoheasGriffin.class));
        //cards.add(new SetCardInfo("Level the Landscape", 18, Rarity.RARE, mage.cards.l.LevelTheLandscape.class));
        cards.add(new SetCardInfo("Mighty Leap", 19, Rarity.COMMON, mage.cards.m.MightyLeap.class));
        //cards.add(new SetCardInfo("Mokupe Earthcrafter", 20, Rarity.COMMON, mage.cards.m.MokupeEarthcrafter.class));
        //cards.add(new SetCardInfo("Moon Weaver", 21, Rarity.RARE, mage.cards.m.MoonWeaver.class));
        //cards.add(new SetCardInfo("Omalu Guide", 22, Rarity.COMMON, mage.cards.o.OmaluGuide.class));
        //cards.add(new SetCardInfo("Omalu Prince", 23, Rarity.UNCOMMON, mage.cards.o.OmaluPrince.class));
        //cards.add(new SetCardInfo("Playful Bottlenose", 24, Rarity.RARE, mage.cards.p.PlayfulBottlenose.class));
        //cards.add(new SetCardInfo("Pristine Daylight", 25, Rarity.UNCOMMON, mage.cards.p.PristineDaylight.class));
        //cards.add(new SetCardInfo("RAK:War Dance", 26, Rarity.COMMON, mage.cards.w.RakWarDance.class));
        //cards.add(new SetCardInfo("Reko's Protege", 27, Rarity.COMMON, mage.cards.r.RekosProtege.class));
        //cards.add(new SetCardInfo("Revered Sovereign", 28, Rarity.UNCOMMON, mage.cards.r.ReveredSovereign.class));
        //cards.add(new SetCardInfo("Roving Sanctuary", 29, Rarity.UNCOMMON, mage.cards.r.RovingSanctuary.class));
        cards.add(new SetCardInfo("Settlement Turtle", 30, Rarity.COMMON, mage.cards.s.SettlementTurtle.class));
        //cards.add(new SetCardInfo("Sunlit Skywhale", 31, Rarity.COMMON, mage.cards.s.SunlitSkywhale.class));
        //cards.add(new SetCardInfo("Suntouched", 32, Rarity.UNCOMMON, mage.cards.s.Suntouched.class));
        cards.add(new SetCardInfo("Take Vengeance", 33, Rarity.COMMON, mage.cards.t.TakeVengeance.class));
        //cards.add(new SetCardInfo("Teacher of Taboos", 34, Rarity.COMMON, mage.cards.t.TeacherOfTaboos.class));
        //cards.add(new SetCardInfo("Tua Rahi Griffin", 35, Rarity.RARE, mage.cards.t.TuaRahiGriffin.class));
        //cards.add(new SetCardInfo("Wander the Unknown", 36, Rarity.UNCOMMON, mage.cards.w.WanderTheUnknown.class));
        //cards.add(new SetCardInfo("Wistful Peka-Bird", 37, Rarity.COMMON, mage.cards.w.WistfulPekaBird.class));
        //cards.add(new SetCardInfo("Wulani, Kahuna of Gifts", 38, Rarity.MYTHIC, mage.cards.w.WulaniKahunaOfGifts.class));
        //cards.add(new SetCardInfo("Wulani's Blessing", 39, Rarity.COMMON, mage.cards.w.WulanisBlessing.class));
        //cards.add(new SetCardInfo("Arcane Torrent", 40, Rarity.COMMON, mage.cards.a.ArcaneTorrent.class));
        //cards.add(new SetCardInfo("Avatar of the Ocean", 41, Rarity.MYTHIC, mage.cards.a.AvatarOfTheOcean.class));
        //cards.add(new SetCardInfo("Budding Seadrake", 42, Rarity.RARE, mage.cards.b.BuddingSeadrake.class));
        //cards.add(new SetCardInfo("Ceaseless Cascade", 43, Rarity.UNCOMMON, mage.cards.c.CeaselessCascade.class));
        cards.add(new SetCardInfo("Coastal Discovery", 44, Rarity.UNCOMMON, mage.cards.c.CoastalDiscovery.class));
        //cards.add(new SetCardInfo("Deep Dive", 45, Rarity.UNCOMMON, mage.cards.d.DeepDive.class));
        //cards.add(new SetCardInfo("Deluge Titan", 46, Rarity.RARE, mage.cards.d.DelugeTitan.class));
        //cards.add(new SetCardInfo("Devastating Deluge", 47, Rarity.UNCOMMON, mage.cards.d.DevastatingDeluge.class));
        //cards.add(new SetCardInfo("Disrupting Current", 48, Rarity.COMMON, mage.cards.d.DisruptingCurrent.class));
        //cards.add(new SetCardInfo("Foraging Seadrake", 49, Rarity.COMMON, mage.cards.f.ForagingSeadrake.class));
        //cards.add(new SetCardInfo("Glow Coral", 50, Rarity.COMMON, mage.cards.g.GlowCoral.class));
        //cards.add(new SetCardInfo("Howling Tempest", 51, Rarity.UNCOMMON, mage.cards.h.HowlingTempest.class));
        //cards.add(new SetCardInfo("Kalepa Drake", 52, Rarity.UNCOMMON, mage.cards.k.KalepaDrake.class));
        //cards.add(new SetCardInfo("Kalepa Dreamer", 53, Rarity.COMMON, mage.cards.k.KalepaDreamer.class));
        //cards.add(new SetCardInfo("Kalepa Sandpiper", 54, Rarity.COMMON, mage.cards.k.KalepaSandpiper.class));
        //cards.add(new SetCardInfo("Kalepa Tidesurger", 55, Rarity.UNCOMMON, mage.cards.k.KalepaTidesurger.class));
        //cards.add(new SetCardInfo("Kanokai's Recruiter", 56, Rarity.RARE, mage.cards.k.KanokaisRecruiter.class));
        //cards.add(new SetCardInfo("Murono's Claim", 57, Rarity.RARE, mage.cards.m.MuronosClaim.class));
        //cards.add(new SetCardInfo("Murono's Ire", 58, Rarity.COMMON, mage.cards.m.MuronosIre.class));
        //cards.add(new SetCardInfo("Ocean Spray", 59, Rarity.UNCOMMON, mage.cards.o.OceanSpray.class));
        //cards.add(new SetCardInfo("Prismatic Loggerhead", 60, Rarity.COMMON, mage.cards.p.PrismaticLoggerhead.class));
        //cards.add(new SetCardInfo("Ramari Scout", 61, Rarity.COMMON, mage.cards.r.RamariScout.class));
        //cards.add(new SetCardInfo("Ramari Sellsword", 62, Rarity.RARE, mage.cards.r.RamariSellsword.class));
        cards.add(new SetCardInfo("Ramari Vagabond", 63, Rarity.COMMON, mage.cards.r.RamariVagabond.class));
        //cards.add(new SetCardInfo("Riptide Ambusher", 64, Rarity.COMMON, mage.cards.r.RiptideAmbusher.class));
        //cards.add(new SetCardInfo("Sarasa, Adventuring Professor", 65, Rarity.MYTHIC, mage.cards.s.SarasaAdventuringProfessor.class));
        //cards.add(new SetCardInfo("Sarasa's Acquisition", 66, Rarity.RARE, mage.cards.s.SarasasAcquisition.class));
        //cards.add(new SetCardInfo("Seafarer's Dream", 67, Rarity.COMMON, mage.cards.s.SeafarersDream.class));
        //cards.add(new SetCardInfo("Stem Hunger", 68, Rarity.COMMON, mage.cards.s.StemHunger.class));
        //cards.add(new SetCardInfo("Storm Serpent", 69, Rarity.COMMON, mage.cards.s.StormSerpent.class));
        //cards.add(new SetCardInfo("Stunning Coils", 70, Rarity.COMMON, mage.cards.s.StunningCoils.class));
        //cards.add(new SetCardInfo("Te Matu's Curiosity", 71, Rarity.COMMON, mage.cards.t.TeMatusCuriosity.class));
        //cards.add(new SetCardInfo("Te Matu's Watcher", 72, Rarity.COMMON, mage.cards.t.TeMatusWatcher.class));
        //cards.add(new SetCardInfo("Tua Rahi Serpent", 73, Rarity.UNCOMMON, mage.cards.t.TuaRahiSerpent.class));
        //cards.add(new SetCardInfo("Vortex Augur", 74, Rarity.UNCOMMON, mage.cards.v.VortexAugur.class));
        //cards.add(new SetCardInfo("Voyager's Advantage", 75, Rarity.RARE, mage.cards.v.VoyagersAdvantage.class));
        //cards.add(new SetCardInfo("Wavebreaker Adept", 76, Rarity.UNCOMMON, mage.cards.w.WavebreakerAdept.class));
        //cards.add(new SetCardInfo("Wavebreaker Shaman", 77, Rarity.UNCOMMON, mage.cards.w.WavebreakerShaman.class));
        //cards.add(new SetCardInfo("Wayfind", 78, Rarity.COMMON, mage.cards.w.Wayfind.class));
        //cards.add(new SetCardInfo("Abyssal Strike", 79, Rarity.RARE, mage.cards.a.AbyssalStrike.class));
        //cards.add(new SetCardInfo("Avatar of the Abyss", 80, Rarity.MYTHIC, mage.cards.a.AvatarOfTheAbyss.class));
        //cards.add(new SetCardInfo("Bandit Warlord", 81, Rarity.UNCOMMON, mage.cards.b.BanditWarlord.class));
        //cards.add(new SetCardInfo("Barang's Blight", 82, Rarity.COMMON, mage.cards.b.BarangsBlight.class));
        //cards.add(new SetCardInfo("Blood in the Water", 83, Rarity.COMMON, mage.cards.b.BloodInTheWater.class));
        //cards.add(new SetCardInfo("Bloodletter Bat", 84, Rarity.COMMON, mage.cards.b.BloodletterBat.class));
        //cards.add(new SetCardInfo("Boiling Outflow", 85, Rarity.RARE, mage.cards.b.BoilingOutflow.class));
        //cards.add(new SetCardInfo("Demand Tribute", 86, Rarity.COMMON, mage.cards.d.DemandTribute.class));
        cards.add(new SetCardInfo("Despise", 87, Rarity.UNCOMMON, mage.cards.d.Despise.class));
        //cards.add(new SetCardInfo("Effervescent Ada", 88, Rarity.COMMON, mage.cards.e.EffervescentAda.class));
        //cards.add(new SetCardInfo("Elder Aswan", 89, Rarity.RARE, mage.cards.e.ElderAswan.class));
        //cards.add(new SetCardInfo("Grim Tikbalang", 90, Rarity.RARE, mage.cards.g.GrimTikbalang.class));
        //cards.add(new SetCardInfo("Haku Haku Hunter", 91, Rarity.UNCOMMON, mage.cards.h.HakuHakuHunter.class));
        cards.add(new SetCardInfo("Haku Haku Strangler", 92, Rarity.COMMON, mage.cards.h.HakuHakuStrangler.class));
        //cards.add(new SetCardInfo("Haku Haku Tyrant", 93, Rarity.COMMON, mage.cards.h.HakuHakuTyrant.class));
        //cards.add(new SetCardInfo("Kanokai, the Deep Blood", 94, Rarity.MYTHIC, mage.cards.k.KanokaiTheDeepBlood.class));
        //cards.add(new SetCardInfo("Kanokai's Bloodlust", 95, Rarity.COMMON, mage.cards.k.KanokaisBloodlust.class));
        //cards.add(new SetCardInfo("Kanokai's Thug", 96, Rarity.COMMON, mage.cards.k.KanokaisThug.class));
        //cards.add(new SetCardInfo("Magma Mutt", 97, Rarity.UNCOMMON, mage.cards.m.MagmaMutt.class));
        //cards.add(new SetCardInfo("Magmatic Rise", 98, Rarity.COMMON, mage.cards.m.MagmaticRise.class));
        //cards.add(new SetCardInfo("Mark of the Aswan", 99, Rarity.COMMON, mage.cards.m.MarkOfTheAswan.class));
        //cards.add(new SetCardInfo("Murk Feeder", 100, Rarity.COMMON, mage.cards.m.MurkFeeder.class));
        //cards.add(new SetCardInfo("Night Marcher", 101, Rarity.COMMON, mage.cards.n.NightMarcher.class));
        //cards.add(new SetCardInfo("Outcast's Etchings", 102, Rarity.COMMON, mage.cards.o.OutcastsEtchings.class));
        //cards.add(new SetCardInfo("Pact of Dark Secrets", 103, Rarity.RARE, mage.cards.p.PactOfDarkSecrets.class));
        //cards.add(new SetCardInfo("Pelagic Peddler", 104, Rarity.RARE, mage.cards.p.PelagicPeddler.class));
        //cards.add(new SetCardInfo("Rahoke's Fumes", 105, Rarity.COMMON, mage.cards.r.RahokesFumes.class));
        //cards.add(new SetCardInfo("Rahoke's Punishment", 106, Rarity.UNCOMMON, mage.cards.r.RahokesPunishment.class));
        //cards.add(new SetCardInfo("Rahoke's Ruiner", 107, Rarity.RARE, mage.cards.r.RahokesRuiner.class));
        //cards.add(new SetCardInfo("Ramari Skull-Hoarder", 108, Rarity.UNCOMMON, mage.cards.r.RamariSkullHoarder.class));
        //cards.add(new SetCardInfo("Reemergence", 109, Rarity.UNCOMMON, mage.cards.r.Reemergence.class));
        //cards.add(new SetCardInfo("Reko's Determined", 110, Rarity.COMMON, mage.cards.r.RekosDetermined.class));
        //cards.add(new SetCardInfo("Ru Kano Scavengers", 111, Rarity.UNCOMMON, mage.cards.r.RuKanoScavengers.class));
        //cards.add(new SetCardInfo("Spreading Corruption", 112, Rarity.UNCOMMON, mage.cards.s.SpreadingCorruption.class));
        //cards.add(new SetCardInfo("Third-Tooth Brute", 113, Rarity.UNCOMMON, mage.cards.t.ThirdToothBrute.class));
        //cards.add(new SetCardInfo("Third-Tooth Ravager", 114, Rarity.COMMON, mage.cards.t.ThirdToothRavager.class));
        //cards.add(new SetCardInfo("Tua Rahi Spotwing", 115, Rarity.UNCOMMON, mage.cards.t.TuaRahiSpotwing.class));
        //cards.add(new SetCardInfo("Untimely Demise", 116, Rarity.UNCOMMON, mage.cards.u.UntimelyDemise.class));
        //cards.add(new SetCardInfo("Utamu Tracker", 117, Rarity.COMMON, mage.cards.u.UtamuTracker.class));
        //cards.add(new SetCardInfo("Avatar of the Volcano", 118, Rarity.MYTHIC, mage.cards.a.AvatarOfTheVolcano.class));
        //cards.add(new SetCardInfo("Bombardment Zone", 119, Rarity.RARE, mage.cards.b.BombardmentZone.class));
        //cards.add(new SetCardInfo("Brewing Storm", 120, Rarity.UNCOMMON, mage.cards.b.BrewingStorm.class));
        //cards.add(new SetCardInfo("Burst Into Being", 121, Rarity.UNCOMMON, mage.cards.b.BurstIntoBeing.class));
        //cards.add(new SetCardInfo("Caldera Tyrant", 122, Rarity.MYTHIC, mage.cards.c.CalderaTyrant.class));
        cards.add(new SetCardInfo("Command the Storm", 123, Rarity.COMMON, mage.cards.c.CommandTheStorm.class));
        //cards.add(new SetCardInfo("Crest the Waters", 124, Rarity.RARE, mage.cards.c.CrestTheWaters.class));
        //cards.add(new SetCardInfo("Daughter of Kalanua", 125, Rarity.COMMON, mage.cards.d.DaughterOfKalanua.class));
        //cards.add(new SetCardInfo("Dual Destruction", 126, Rarity.UNCOMMON, mage.cards.d.DualDestruction.class));
        //cards.add(new SetCardInfo("Elder Pyromancer", 127, Rarity.RARE, mage.cards.e.ElderPyromancer.class));
        //cards.add(new SetCardInfo("Emboldening Markings", 128, Rarity.COMMON, mage.cards.e.EmboldeningMarkings.class));
        //cards.add(new SetCardInfo("Fireshaper Shaman", 129, Rarity.COMMON, mage.cards.f.FireshaperShaman.class));
        //cards.add(new SetCardInfo("Flame-Tail Guide", 130, Rarity.COMMON, mage.cards.f.FlameTailGuide.class));
        cards.add(new SetCardInfo("Flaming Sarimanok", 131, Rarity.COMMON, mage.cards.f.FlamingSarimanok.class));
        //cards.add(new SetCardInfo("Harness the Eruption", 132, Rarity.RARE, mage.cards.h.HarnessTheEruption.class));
        //cards.add(new SetCardInfo("Hupiri's Trespass", 133, Rarity.RARE, mage.cards.h.HupirisTrespass.class));
        //cards.add(new SetCardInfo("Kalanua's Wrath", 134, Rarity.MYTHIC, mage.cards.k.KalanuasWrath.class));
        //cards.add(new SetCardInfo("Lava Leap", 135, Rarity.COMMON, mage.cards.l.LavaLeap.class));
        //cards.add(new SetCardInfo("Lava Shaping", 136, Rarity.UNCOMMON, mage.cards.l.LavaShaping.class));
        //cards.add(new SetCardInfo("Lavaback Youngling", 137, Rarity.COMMON, mage.cards.l.LavabackYoungling.class));
        //cards.add(new SetCardInfo("Loyalty Shift", 138, Rarity.COMMON, mage.cards.l.LoyaltyShift.class));
        //cards.add(new SetCardInfo("Magma Blast", 139, Rarity.COMMON, mage.cards.m.MagmaBlast.class));
        //cards.add(new SetCardInfo("Magma Maul", 140, Rarity.UNCOMMON, mage.cards.m.MagmaMaul.class));
        //cards.add(new SetCardInfo("Maw of Rahoke", 141, Rarity.COMMON, mage.cards.m.MawOfRahoke.class));
        //cards.add(new SetCardInfo("Meke Champion", 142, Rarity.COMMON, mage.cards.m.MekeChampion.class));
        //cards.add(new SetCardInfo("Meke Contender", 143, Rarity.COMMON, mage.cards.m.MekeContender.class));
        //cards.add(new SetCardInfo("Meke Firestoker", 144, Rarity.UNCOMMON, mage.cards.m.MekeFirestoker.class));
        //cards.add(new SetCardInfo("Meke Ventcaller", 145, Rarity.UNCOMMON, mage.cards.m.MekeVentcaller.class));
        //cards.add(new SetCardInfo("Neon Diver", 146, Rarity.COMMON, mage.cards.n.NeonDiver.class));
        //cards.add(new SetCardInfo("Peak Chaos", 147, Rarity.UNCOMMON, mage.cards.p.PeakChaos.class));
        //cards.add(new SetCardInfo("Prodigious Fisher", 148, Rarity.COMMON, mage.cards.p.ProdigiousFisher.class));
        cards.add(new SetCardInfo("Smelt", 149, Rarity.COMMON, mage.cards.s.Smelt.class));
        cards.add(new SetCardInfo("Sure Strike", 150, Rarity.COMMON, mage.cards.s.SureStrike.class));
        //cards.add(new SetCardInfo("Toahanga's Slam", 151, Rarity.COMMON, mage.cards.t.ToahangasSlam.class));
        cards.add(new SetCardInfo("Tua Rahi Avenger", 152, Rarity.UNCOMMON, mage.cards.t.TuaRahiAvenger.class));
        //cards.add(new SetCardInfo("Unproven Hatchling", 153, Rarity.RARE, mage.cards.u.UnprovenHatchling.class));
        //cards.add(new SetCardInfo("Utamu Ravager", 154, Rarity.UNCOMMON, mage.cards.u.UtamuRavager.class));
        cards.add(new SetCardInfo("Volcanic Dragon", 155, Rarity.UNCOMMON, mage.cards.v.VolcanicDragon.class));
        //cards.add(new SetCardInfo("Volcanic Uproar", 156, Rarity.UNCOMMON, mage.cards.v.VolcanicUproar.class));
        //cards.add(new SetCardInfo("Absurd Burgeoning", 157, Rarity.RARE, mage.cards.a.AbsurdBurgeoning.class));
        //cards.add(new SetCardInfo("Ancient Uprising", 158, Rarity.UNCOMMON, mage.cards.a.AncientUprising.class));
        //cards.add(new SetCardInfo("Avatar of the Jungle", 159, Rarity.MYTHIC, mage.cards.a.AvatarOfTheJungle.class));
        //cards.add(new SetCardInfo("Blessing of Strength", 160, Rarity.COMMON, mage.cards.b.BlessingOfStrength.class));
        //cards.add(new SetCardInfo("Boon Artisan", 161, Rarity.UNCOMMON, mage.cards.b.BoonArtisan.class));
        //cards.add(new SetCardInfo("Bounty of the Mokupe", 162, Rarity.COMMON, mage.cards.b.BountyOfTheMokupe.class));
        //cards.add(new SetCardInfo("Coral Titan", 163, Rarity.COMMON, mage.cards.c.CoralTitan.class));
        //cards.add(new SetCardInfo("Cradle of Kohea", 164, Rarity.COMMON, mage.cards.c.CradleOfKohea.class));
        cards.add(new SetCardInfo("Dryad Pummeler", 165, Rarity.COMMON, mage.cards.d.DryadPummeler.class));
        //cards.add(new SetCardInfo("Elemental Surge", 166, Rarity.COMMON, mage.cards.e.ElementalSurge.class));
        cards.add(new SetCardInfo("Farseek", 167, Rarity.UNCOMMON, mage.cards.f.Farseek.class));
        //cards.add(new SetCardInfo("Fruitful Earthcrafters", 168, Rarity.UNCOMMON, mage.cards.f.FruitfulEarthcrafters.class));
        //cards.add(new SetCardInfo("Heart of the Gods", 169, Rarity.MYTHIC, mage.cards.h.HeartOfTheGods.class));
        //cards.add(new SetCardInfo("Heliha, Steward of Tua Rahi", 170, Rarity.RARE, mage.cards.h.HelihaStewardOfTuaRahi.class));
        //cards.add(new SetCardInfo("Hero's Triumph", 171, Rarity.COMMON, mage.cards.h.HerosTriumph.class));
        //cards.add(new SetCardInfo("Hunter's Maneuver", 172, Rarity.UNCOMMON, mage.cards.h.HuntersManeuver.class));
        //cards.add(new SetCardInfo("Jungle Hydra", 173, Rarity.RARE, mage.cards.j.JungleHydra.class));
        //cards.add(new SetCardInfo("Kalanua's Renewal", 174, Rarity.UNCOMMON, mage.cards.k.KalanuasRenewal.class));
        //cards.add(new SetCardInfo("Kohea's Vitality", 175, Rarity.RARE, mage.cards.k.KoheasVitality.class));
        //cards.add(new SetCardInfo("Leafy Companion", 176, Rarity.COMMON, mage.cards.l.LeafyCompanion.class));
        //cards.add(new SetCardInfo("Luaho Barkskin", 177, Rarity.COMMON, mage.cards.l.LuahoBarkskin.class));
        //cards.add(new SetCardInfo("Luaho Bud-Mother", 178, Rarity.UNCOMMON, mage.cards.l.LuahoBudMother.class));
        //cards.add(new SetCardInfo("Luaho Crafter", 179, Rarity.COMMON, mage.cards.l.LuahoCrafter.class));
        //cards.add(new SetCardInfo("Meeting with the Menehune", 180, Rarity.UNCOMMON, mage.cards.m.MeetingWithTheMenehune.class));
        //cards.add(new SetCardInfo("Mokupe Bowmaster", 181, Rarity.UNCOMMON, mage.cards.m.MokupeBowmaster.class));
        //cards.add(new SetCardInfo("Mokupe Fisher", 182, Rarity.COMMON, mage.cards.m.MokupeFisher.class));
        //cards.add(new SetCardInfo("Mokupe Tracker", 183, Rarity.RARE, mage.cards.m.MokupeTracker.class));
        //cards.add(new SetCardInfo("Ornamented Kiwi", 184, Rarity.COMMON, mage.cards.o.OrnamentedKiwi.class));
        //cards.add(new SetCardInfo("Palm-Neck Crocodile", 185, Rarity.COMMON, mage.cards.p.PalmNeckCrocodile.class));
        //cards.add(new SetCardInfo("Path to Paradise", 186, Rarity.COMMON, mage.cards.p.PathToParadise.class));
        //cards.add(new SetCardInfo("Primal Reaction", 187, Rarity.COMMON, mage.cards.p.PrimalReaction.class));
        cards.add(new SetCardInfo("Spawning Grounds", 188, Rarity.RARE, mage.cards.s.SpawningGrounds.class));
        cards.add(new SetCardInfo("Titanic Growth", 189, Rarity.COMMON, mage.cards.t.TitanicGrowth.class));
        cards.add(new SetCardInfo("Toahanga's Tusker", 190, Rarity.COMMON, mage.cards.t.ToahangasTusker.class));
        //cards.add(new SetCardInfo("Tua Rahi Giant", 191, Rarity.UNCOMMON, mage.cards.t.TuaRahiGiant.class));
        //cards.add(new SetCardInfo("Unassuming Duwende", 192, Rarity.COMMON, mage.cards.u.UnassumingDuwende.class));
        //cards.add(new SetCardInfo("Venom Orchid", 193, Rarity.UNCOMMON, mage.cards.v.VenomOrchid.class));
        //cards.add(new SetCardInfo("Verdant Extent", 194, Rarity.UNCOMMON, mage.cards.v.VerdantExtent.class));
        //cards.add(new SetCardInfo("Wild Storyteller", 195, Rarity.RARE, mage.cards.w.WildStoryteller.class));
        //cards.add(new SetCardInfo("Ancient Imprisonment", 196, Rarity.RARE, mage.cards.a.AncientImprisonment.class));
        //cards.add(new SetCardInfo("Clean Slate", 197, Rarity.MYTHIC, mage.cards.c.CleanSlate.class));
        //cards.add(new SetCardInfo("Fierce Spearhead", 198, Rarity.UNCOMMON, mage.cards.f.FierceSpearhead.class));
        //cards.add(new SetCardInfo("Hupiri, Vengeant Storm", 199, Rarity.RARE, mage.cards.h.HupiriVengeantStorm.class));
        //cards.add(new SetCardInfo("Hupiri's Return", 200, Rarity.UNCOMMON, mage.cards.h.HupirisReturn.class));
        //cards.add(new SetCardInfo("Kalanua's Juggernaut", 201, Rarity.UNCOMMON, mage.cards.k.KalanuasJuggernaut.class));
        //cards.add(new SetCardInfo("Make Prey", 202, Rarity.RARE, mage.cards.m.MakePrey.class));
        //cards.add(new SetCardInfo("Mangrove Sifter", 203, Rarity.UNCOMMON, mage.cards.m.MangroveSifter.class));
        //cards.add(new SetCardInfo("Oteo, Conqueror Redeemed", 204, Rarity.RARE, mage.cards.o.OteoConquerorRedeemed.class));
        //cards.add(new SetCardInfo("Overgrowth Crab", 205, Rarity.UNCOMMON, mage.cards.o.OvergrowthCrab.class));
        //cards.add(new SetCardInfo("Prismatic Oddity", 206, Rarity.UNCOMMON, mage.cards.p.PrismaticOddity.class));
        //cards.add(new SetCardInfo("Ramari Hunt Captain", 207, Rarity.UNCOMMON, mage.cards.r.RamariHuntCaptain.class));
        //cards.add(new SetCardInfo("Reko, of the Broken Grove", 208, Rarity.MYTHIC, mage.cards.r.RekoOfTheBrokenGrove.class));
        //cards.add(new SetCardInfo("Snatching Poukai", 209, Rarity.UNCOMMON, mage.cards.s.SnatchingPoukai.class));
        //cards.add(new SetCardInfo("Solidifying Mass", 210, Rarity.RARE, mage.cards.s.SolidifyingMass.class));
        //cards.add(new SetCardInfo("Spiral Salamander", 211, Rarity.UNCOMMON, mage.cards.s.SpiralSalamander.class));
        //cards.add(new SetCardInfo("Toahanga, Shifter Champion", 212, Rarity.MYTHIC, mage.cards.t.ToahangaShifterChampion.class));
        //cards.add(new SetCardInfo("Whaleback Raider", 213, Rarity.UNCOMMON, mage.cards.w.WhalebackRaider.class));
        //cards.add(new SetCardInfo("World Elemental", 214, Rarity.MYTHIC, mage.cards.w.WorldElemental.class));
        //cards.add(new SetCardInfo("Carved Boar", 215, Rarity.UNCOMMON, mage.cards.c.CarvedBoar.class));
        //cards.add(new SetCardInfo("Carving Tools", 216, Rarity.RARE, mage.cards.c.CarvingTools.class));
        cards.add(new SetCardInfo("Echoshells", 217, Rarity.RARE, mage.cards.e.Echoshells.class));
        //cards.add(new SetCardInfo("Engraved Moai", 218, Rarity.COMMON, mage.cards.e.EngravedMoai.class));
        //cards.add(new SetCardInfo("Opalescent Egg", 219, Rarity.UNCOMMON, mage.cards.o.OpalescentEgg.class));
        //cards.add(new SetCardInfo("Paradise Gem", 220, Rarity.RARE, mage.cards.p.ParadiseGem.class));
        cards.add(new SetCardInfo("Paradise Mantle", 221, Rarity.UNCOMMON, mage.cards.p.ParadiseMantle.class));
        //cards.add(new SetCardInfo("Ponamu Keepsake", 222, Rarity.UNCOMMON, mage.cards.p.PonamuKeepsake.class));
        //cards.add(new SetCardInfo("Skyrider's Vessel", 223, Rarity.RARE, mage.cards.s.SkyridersVessel.class));
        //cards.add(new SetCardInfo("Sturdy Canoe", 224, Rarity.UNCOMMON, mage.cards.s.SturdyCanoe.class));
        //cards.add(new SetCardInfo("Voyager's Companion", 225, Rarity.RARE, mage.cards.v.VoyagersCompanion.class));
        //cards.add(new SetCardInfo("Coral Barrens", 226, Rarity.UNCOMMON, mage.cards.c.CoralBarrens.class));
        //cards.add(new SetCardInfo("Crafting Hut", 227, Rarity.UNCOMMON, mage.cards.c.CraftingHut.class));
        //cards.add(new SetCardInfo("Crossroads of Paradise", 228, Rarity.UNCOMMON, mage.cards.c.CrossroadsOfParadise.class));
        //cards.add(new SetCardInfo("Draconic Crevice", "229a", Rarity.RARE, mage.cards.d.DraconicCrevice.class));
        //cards.add(new SetCardInfo("Laza Kolo, the Vigorous", "229b", Rarity.RARE, mage.cards.l.LazaKoloTheVigorous.class));
        //cards.add(new SetCardInfo("Elipo Ono Meadows", 230, Rarity.RARE, mage.cards.e.ElipoOnoMeadows.class));
        //cards.add(new SetCardInfo("Fangmarked Cave", "231a", Rarity.RARE, mage.cards.f.FangmarkedCave.class));
        //cards.add(new SetCardInfo("Hak Bora, the Voracious", "231b", Rarity.RARE, mage.cards.h.HakBoraTheVoracious.class));
        //cards.add(new SetCardInfo("Fogwrapped Cliffs", "232a", Rarity.RARE, mage.cards.f.FogwrappedCliffs.class));
        //cards.add(new SetCardInfo("Ea Ea, the Watchful", "232b", Rarity.RARE, mage.cards.e.EaEaTheWatchful.class));
        //cards.add(new SetCardInfo("Luminescent Lagoon", "233a", Rarity.RARE, mage.cards.l.LuminescentLagoon.class));
        //cards.add(new SetCardInfo("Gau Loni, the Wise", "233b", Rarity.RARE, mage.cards.g.GauLoniTheWise.class));
        //cards.add(new SetCardInfo("Mohele Beacon", 234, Rarity.RARE, mage.cards.m.MoheleBeacon.class));
        //cards.add(new SetCardInfo("Mushroom Bog", 235, Rarity.COMMON, mage.cards.m.MushroomBog.class));
        //cards.add(new SetCardInfo("Opaku Monolith", 236, Rarity.RARE, mage.cards.o.OpakuMonolith.class));
        //cards.add(new SetCardInfo("Ru Kano Ruins", 237, Rarity.RARE, mage.cards.r.RuKanoRuins.class));
        //cards.add(new SetCardInfo("Sea-Soaked Cliff", 238, Rarity.COMMON, mage.cards.s.SeaSoakedCliff.class));
        //cards.add(new SetCardInfo("Shaded Shelter", 239, Rarity.COMMON, mage.cards.s.ShadedShelter.class));
        //cards.add(new SetCardInfo("Shellback Tradepost", 240, Rarity.UNCOMMON, mage.cards.s.ShellbackTradepost.class));
        //cards.add(new SetCardInfo("Slumbering Grotto", "241a", Rarity.RARE, mage.cards.s.SlumberingGrotto.class));
        //cards.add(new SetCardInfo("Kumapa, the Awoken", "241b", Rarity.RARE, mage.cards.k.KumapaTheAwoken.class));
        //cards.add(new SetCardInfo("Stirring Effigies", 242, Rarity.UNCOMMON, mage.cards.s.StirringEffigies.class));
        //cards.add(new SetCardInfo("Tropical Channel", 243, Rarity.COMMON, mage.cards.t.TropicalChannel.class));
        //cards.add(new SetCardInfo("Utamu Core", 244, Rarity.RARE, mage.cards.u.UtamuCore.class));
        //cards.add(new SetCardInfo("Zephyr Peak", 245, Rarity.COMMON, mage.cards.z.ZephyrPeak.class));
        cards.add(new SetCardInfo("Plains", 246, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 247, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 248, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 249, Rarity.LAND, mage.cards.basiclands.Plains.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Island", 251, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 252, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 253, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 254, Rarity.LAND, mage.cards.basiclands.Island.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Island", 255, Rarity.LAND, mage.cards.basiclands.Island.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 256, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 257, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 258, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 259, Rarity.LAND, mage.cards.basiclands.Swamp.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Swamp", 260, Rarity.LAND, mage.cards.basiclands.Swamp.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 261, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 262, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 263, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 264, Rarity.LAND, mage.cards.basiclands.Mountain.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Mountain", 265, Rarity.LAND, mage.cards.basiclands.Mountain.class, FULL_ART_BFZ_VARIOUS));
        cards.add(new SetCardInfo("Forest", 266, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 267, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 268, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 269, Rarity.LAND, mage.cards.basiclands.Forest.class, NON_FULL_USE_VARIOUS));
        cards.add(new SetCardInfo("Forest", 270, Rarity.LAND, mage.cards.basiclands.Forest.class, FULL_ART_BFZ_VARIOUS));
    }
}
