package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class RuinsOfDoharum extends ExpansionSet {
    private static final RuinsOfDoharum instance = new RuinsOfDoharum();

    public static RuinsOfDoharum getInstance() { return instance; }

    private RuinsOfDoharum() {
        super("Ruins of Doharum", "DHM", ExpansionSet.buildDate(2018, 8, 30), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Ancient Covenant", 1, Rarity.RARE, mage.cards.a.AncientCovenant.class));
        //cards.add(new SetCardInfo("Arduous Journey", 2, Rarity.COMMON, mage.cards.a.ArduousJourney.class));
        //cards.add(new SetCardInfo("Ashkal Lookout", 3, Rarity.COMMON, mage.cards.a.AshkalLookout.class));
        //cards.add(new SetCardInfo("Awe for the Dohar", 4, Rarity.COMMON, mage.cards.a.AweForTheDohar.class));
        //cards.add(new SetCardInfo("Azelduum Gatekeepers", 5, Rarity.UNCOMMON, mage.cards.a.AzelduumGatekeepers.class));
        //cards.add(new SetCardInfo("Bastion Defender", 6, Rarity.COMMON, mage.cards.b.BastionDefender.class));
        //cards.add(new SetCardInfo("Chthonic Wastemaker", 7, Rarity.MYTHIC, mage.cards.c.ChthonicWastemaker.class));
        //cards.add(new SetCardInfo("Desolation Priest", 8, Rarity.UNCOMMON, mage.cards.d.DesolationPriest.class));
        //cards.add(new SetCardInfo("Dune Watcher", 9, Rarity.COMMON, mage.cards.d.DuneWatcher.class));
        //cards.add(new SetCardInfo("End of Civilization", 10, Rarity.RARE, mage.cards.e.EndOfCivilization.class));
        //cards.add(new SetCardInfo("High Priestess of Urukh", 11, Rarity.RARE, mage.cards.h.HighPriestessOfUrukh.class));
        //cards.add(new SetCardInfo("Lithomancy Adept", 12, Rarity.COMMON, mage.cards.l.LithomancyAdept.class));
        //cards.add(new SetCardInfo("Lithomantic Touch", 13, Rarity.COMMON, mage.cards.l.LithomanticTouch.class));
        //cards.add(new SetCardInfo("Meditations of Stone", 14, Rarity.UNCOMMON, mage.cards.m.MeditationsOfStone.class));
        //cards.add(new SetCardInfo("Merkym Survivors", 15, Rarity.COMMON, mage.cards.m.MerkymSurvivors.class));
        //cards.add(new SetCardInfo("Nahiri, the Weary", 16, Rarity.MYTHIC, mage.cards.n.NahiriTheWeary.class));
        //cards.add(new SetCardInfo("Oasis Wayfinder", 17, Rarity.RARE, mage.cards.o.OasisWayfinder.class));
        //cards.add(new SetCardInfo("Radiant Scouring", 18, Rarity.COMMON, mage.cards.r.RadiantScouring.class));
        //cards.add(new SetCardInfo("Rebuff the Sinful", 19, Rarity.UNCOMMON, mage.cards.r.RebuffTheSinful.class));
        //cards.add(new SetCardInfo("Roaming Sentinels", 20, Rarity.UNCOMMON, mage.cards.r.RoamingSentinels.class));
        //cards.add(new SetCardInfo("Sand Sentinel", 21, Rarity.COMMON, mage.cards.s.SandSentinel.class));
        //cards.add(new SetCardInfo("Scouring Winds", 22, Rarity.UNCOMMON, mage.cards.s.ScouringWinds.class));
        //cards.add(new SetCardInfo("Shelter in the Wastes", 23, Rarity.UNCOMMON, mage.cards.s.ShelterInTheWastes.class));
        //cards.add(new SetCardInfo("Souls of the Lost", 24, Rarity.COMMON, mage.cards.s.SoulsOfTheLost.class));
        //cards.add(new SetCardInfo("Stoneforge Paragon", 25, Rarity.RARE, mage.cards.s.StoneforgeParagon.class));
        //cards.add(new SetCardInfo("Suran Chief", 26, Rarity.UNCOMMON, mage.cards.s.SuranChief.class));
        //cards.add(new SetCardInfo("Suran Pilgrimage", 27, Rarity.RARE, mage.cards.s.SuranPilgrimage.class));
        //cards.add(new SetCardInfo("Suran Pilgrims", 28, Rarity.COMMON, mage.cards.s.SuranPilgrims.class));
        //cards.add(new SetCardInfo("Swift Reproach", 29, Rarity.COMMON, mage.cards.s.SwiftReproach.class));
        //cards.add(new SetCardInfo("Temple to the Dohar", 30, Rarity.RARE, mage.cards.t.TempleToTheDohar.class));
        //cards.add(new SetCardInfo("Tyrant's Edict", 31, Rarity.COMMON, mage.cards.t.TyrantsEdict.class));
        //cards.add(new SetCardInfo("Tyrant's Enforcer", 32, Rarity.UNCOMMON, mage.cards.t.TyrantsEnforcer.class));
        //cards.add(new SetCardInfo("Urukh Justiciars", 33, Rarity.COMMON, mage.cards.u.UrukhJusticiars.class));
        //cards.add(new SetCardInfo("Wandering Ascetic", 34, Rarity.COMMON, mage.cards.w.WanderingAscetic.class));
        //cards.add(new SetCardInfo("Ancient Insight", 35, Rarity.COMMON, mage.cards.a.AncientInsight.class));
        //cards.add(new SetCardInfo("Arcane Merchant", 36, Rarity.UNCOMMON, mage.cards.a.ArcaneMerchant.class));
        //cards.add(new SetCardInfo("Ashkal Everseekers", 37, Rarity.COMMON, mage.cards.a.AshkalEverseekers.class));
        //cards.add(new SetCardInfo("Ashkal Guard", 38, Rarity.UNCOMMON, mage.cards.a.AshkalGuard.class));
        //cards.add(new SetCardInfo("Awaken the Nameless", 39, Rarity.MYTHIC, mage.cards.a.AwakenTheNameless.class));
        //cards.add(new SetCardInfo("Bury the Past", 40, Rarity.RARE, mage.cards.b.BuryThePast.class));
        cards.add(new SetCardInfo("Cancel", 41, Rarity.COMMON, mage.cards.c.Cancel.class));
        cards.add(new SetCardInfo("Disdainful Stroke", 42, Rarity.COMMON, mage.cards.d.DisdainfulStroke.class));
        //cards.add(new SetCardInfo("Dune Predator", 43, Rarity.COMMON, mage.cards.d.DunePredator.class));
        //cards.add(new SetCardInfo("Endless Passages", 44, Rarity.UNCOMMON, mage.cards.e.EndlessPassages.class));
        //cards.add(new SetCardInfo("Explorer's Intuition", 45, Rarity.COMMON, mage.cards.e.ExplorersIntuition.class));
        //cards.add(new SetCardInfo("Fleeting Opportunity", 46, Rarity.RARE, mage.cards.f.FleetingOpportunity.class));
        //cards.add(new SetCardInfo("Hidden Knowledge", 47, Rarity.COMMON, mage.cards.h.HiddenKnowledge.class));
        //cards.add(new SetCardInfo("Intrepid Loreseeker", 48, Rarity.COMMON, mage.cards.i.IntrepidLoreseeker.class));
        //cards.add(new SetCardInfo("Keep at Bay", 49, Rarity.COMMON, mage.cards.k.KeepAtBay.class));
        //cards.add(new SetCardInfo("Leyline Nexus", 50, Rarity.RARE, mage.cards.l.LeylineNexus.class));
        //cards.add(new SetCardInfo("Library of Tel'tor", 51, Rarity.RARE, mage.cards.l.LibraryOfTeltor.class));
        //cards.add(new SetCardInfo("Lost History", 52, Rarity.UNCOMMON, mage.cards.l.LostHistory.class));
        //cards.add(new SetCardInfo("Pull of the Past", 53, Rarity.UNCOMMON, mage.cards.p.PullOfThePast.class));
        //cards.add(new SetCardInfo("Relic Translator", 54, Rarity.COMMON, mage.cards.r.RelicTranslator.class));
        //cards.add(new SetCardInfo("Ruin Drake", 55, Rarity.COMMON, mage.cards.r.RuinDrake.class));
        //cards.add(new SetCardInfo("Runestone Shyft", 56, Rarity.RARE, mage.cards.r.RunestoneShyft.class));
        //cards.add(new SetCardInfo("Runewarder", 57, Rarity.COMMON, mage.cards.r.Runewarder.class));
        //cards.add(new SetCardInfo("Runic Barrier", 58, Rarity.UNCOMMON, mage.cards.r.RunicBarrier.class));
        //cards.add(new SetCardInfo("Secret Hoarder", 59, Rarity.COMMON, mage.cards.s.SecretHoarder.class));
        //cards.add(new SetCardInfo("Seeker of Lost Lore", 60, Rarity.UNCOMMON, mage.cards.s.SeekerOfLostLore.class));
        //cards.add(new SetCardInfo("Shape Reality", 61, Rarity.RARE, mage.cards.s.ShapeReality.class));
        //cards.add(new SetCardInfo("Stasis Chamber", 62, Rarity.COMMON, mage.cards.s.StasisChamber.class));
        //cards.add(new SetCardInfo("Tel'tor Ruin Diver", 63, Rarity.COMMON, mage.cards.t.TeltorRuinDiver.class));
        //cards.add(new SetCardInfo("Time-Lost Ascetic", 64, Rarity.MYTHIC, mage.cards.t.TimeLostAscetic.class));
        //cards.add(new SetCardInfo("Unravelling Reality", 65, Rarity.COMMON, mage.cards.u.UnravellingReality.class));
        //cards.add(new SetCardInfo("Unsealed Horrors", 66, Rarity.UNCOMMON, mage.cards.u.UnsealedHorrors.class));
        //cards.add(new SetCardInfo("Will of the Dohar", 67, Rarity.UNCOMMON, mage.cards.w.WillOfTheDohar.class));
        //cards.add(new SetCardInfo("Ahnkar Bombardier", 68, Rarity.COMMON, mage.cards.a.AhnkarBombardier.class));
        //cards.add(new SetCardInfo("Ahnkar Militant", 69, Rarity.COMMON, mage.cards.a.AhnkarMilitant.class));
        //cards.add(new SetCardInfo("Banestatue Hex", 70, Rarity.COMMON, mage.cards.b.BanestatueHex.class));
        //cards.add(new SetCardInfo("Blackscar Chargers", 71, Rarity.COMMON, mage.cards.b.BlackscarChargers.class));
        //cards.add(new SetCardInfo("Delve into the Crypts", 72, Rarity.COMMON, mage.cards.d.DelveIntoTheCrypts.class));
        //cards.add(new SetCardInfo("Enslaved Laborer", 73, Rarity.COMMON, mage.cards.e.EnslavedLaborer.class));
        //cards.add(new SetCardInfo("Fate of the Weak", 74, Rarity.COMMON, mage.cards.f.FateOfTheWeak.class));
        //cards.add(new SetCardInfo("Horrid Rite", 75, Rarity.COMMON, mage.cards.h.HorridRite.class));
        //cards.add(new SetCardInfo("Keeper of Dead Secrets", 76, Rarity.RARE, mage.cards.k.KeeperOfDeadSecrets.class));
        //cards.add(new SetCardInfo("Ladar Raiders", 77, Rarity.COMMON, mage.cards.l.LadarRaiders.class));
        //cards.add(new SetCardInfo("Ladar Ritualist", 78, Rarity.UNCOMMON, mage.cards.l.LadarRitualist.class));
        //cards.add(new SetCardInfo("Ladar Warlord", 79, Rarity.RARE, mage.cards.l.LadarWarlord.class));
        //cards.add(new SetCardInfo("Leyline Miasma", 80, Rarity.RARE, mage.cards.l.LeylineMiasma.class));
        //cards.add(new SetCardInfo("Looming Shadows", 81, Rarity.UNCOMMON, mage.cards.l.LoomingShadows.class));
        //cards.add(new SetCardInfo("Marad's Inquiry", 82, Rarity.UNCOMMON, mage.cards.m.MaradsInquiry.class));
        //cards.add(new SetCardInfo("Nameless Whispers", 83, Rarity.COMMON, mage.cards.n.NamelessWhispers.class));
        //cards.add(new SetCardInfo("Nerim Deathseer", 84, Rarity.UNCOMMON, mage.cards.n.NerimDeathseer.class));
        //cards.add(new SetCardInfo("Nerim Heretic", 85, Rarity.COMMON, mage.cards.n.NerimHeretic.class));
        //cards.add(new SetCardInfo("Nezadar Broodqueen", 86, Rarity.RARE, mage.cards.n.NezadarBroodqueen.class));
        //cards.add(new SetCardInfo("Nibinem, Tyrant King", 87, Rarity.MYTHIC, mage.cards.n.NibinemTyrantKing.class));
        //cards.add(new SetCardInfo("Oblivion Gate", 88, Rarity.MYTHIC, mage.cards.o.OblivionGate.class));
        //cards.add(new SetCardInfo("Reckless Explorer", 89, Rarity.UNCOMMON, mage.cards.r.RecklessExplorer.class));
        //cards.add(new SetCardInfo("Relic Channeler", 90, Rarity.COMMON, mage.cards.r.RelicChanneler.class));
        //cards.add(new SetCardInfo("Scarland Devourer", 91, Rarity.COMMON, mage.cards.s.ScarlandDevourer.class));
        //cards.add(new SetCardInfo("Scarland Monstrosity", 92, Rarity.RARE, mage.cards.s.ScarlandMonstrosity.class));
        //cards.add(new SetCardInfo("Scourging Stones", 93, Rarity.UNCOMMON, mage.cards.s.ScourgingStones.class));
        //cards.add(new SetCardInfo("Shadows of Oblivion", 94, Rarity.RARE, mage.cards.s.ShadowsOfOblivion.class));
        //cards.add(new SetCardInfo("Soul Tether", 95, Rarity.COMMON, mage.cards.s.SoulTether.class));
        //cards.add(new SetCardInfo("Time-Lost Power", 96, Rarity.COMMON, mage.cards.t.TimeLostPower.class));
        //cards.add(new SetCardInfo("Tomb of the Dohar", 97, Rarity.RARE, mage.cards.t.TombOfTheDohar.class));
        //cards.add(new SetCardInfo("Tyrant's Dominion", 98, Rarity.UNCOMMON, mage.cards.t.TyrantsDominion.class));
        //cards.add(new SetCardInfo("Uncover the Tomb", 99, Rarity.UNCOMMON, mage.cards.u.UncoverTheTomb.class));
        //cards.add(new SetCardInfo("Urukh Slaver", 100, Rarity.UNCOMMON, mage.cards.u.UrukhSlaver.class));
        //cards.add(new SetCardInfo("Wasteland Bandits", 101, Rarity.COMMON, mage.cards.w.WastelandBandits.class));
        //cards.add(new SetCardInfo("Azelduum Wardriver", 102, Rarity.UNCOMMON, mage.cards.a.AzelduumWardriver.class));
        //cards.add(new SetCardInfo("Blackscar Breaker", 103, Rarity.RARE, mage.cards.b.BlackscarBreaker.class));
        //cards.add(new SetCardInfo("Blackscar Chieftain", 104, Rarity.MYTHIC, mage.cards.b.BlackscarChieftain.class));
        //cards.add(new SetCardInfo("Bolgrim Archaeologist", 105, Rarity.COMMON, mage.cards.b.BolgrimArchaeologist.class));
        //cards.add(new SetCardInfo("Consuming Darkfire", 106, Rarity.UNCOMMON, mage.cards.c.ConsumingDarkfire.class));
        //cards.add(new SetCardInfo("Darkfire Burst", 107, Rarity.COMMON, mage.cards.d.DarkfireBurst.class));
        //cards.add(new SetCardInfo("Darkfire Despot", 108, Rarity.MYTHIC, mage.cards.d.DarkfireDespot.class));
        //cards.add(new SetCardInfo("Darkfire Roamer", 109, Rarity.COMMON, mage.cards.d.DarkfireRoamer.class));
        cards.add(new SetCardInfo("Desert Cutthroat", 110, Rarity.COMMON, mage.cards.d.DesertCutthroat.class));
        //cards.add(new SetCardInfo("Devastating Raze", 111, Rarity.COMMON, mage.cards.d.DevastatingRaze.class));
        //cards.add(new SetCardInfo("Discharge", 112, Rarity.UNCOMMON, mage.cards.d.Discharge.class));
        //cards.add(new SetCardInfo("Dwarven Ambushers", 113, Rarity.COMMON, mage.cards.d.DwarvenAmbushers.class));
        //cards.add(new SetCardInfo("Dwarven Heartrager", 114, Rarity.RARE, mage.cards.d.DwarvenHeartrager.class));
        //cards.add(new SetCardInfo("Echo of the Past", 115, Rarity.COMMON, mage.cards.e.EchoOfThePast.class));
        //cards.add(new SetCardInfo("Engraved Prophecy", 116, Rarity.RARE, mage.cards.e.EngravedProphecy.class));
        //cards.add(new SetCardInfo("Gnarled-Pass Brute", 117, Rarity.COMMON, mage.cards.g.GnarledPassBrute.class));
        //cards.add(new SetCardInfo("Ley Mutation", 118, Rarity.COMMON, mage.cards.l.LeyMutation.class));
        //cards.add(new SetCardInfo("Lingering Leyfever", 119, Rarity.UNCOMMON, mage.cards.l.LingeringLeyfever.class));
        //cards.add(new SetCardInfo("Ruin Collapse", 120, Rarity.COMMON, mage.cards.r.RuinCollapse.class));
        //cards.add(new SetCardInfo("Ruin Wanderer", 121, Rarity.UNCOMMON, mage.cards.r.RuinWanderer.class));
        //cards.add(new SetCardInfo("Runestone Crucible", 122, Rarity.RARE, mage.cards.r.RunestoneCrucible.class));
        //cards.add(new SetCardInfo("Runestone Igniter", 123, Rarity.UNCOMMON, mage.cards.r.RunestoneIgniter.class));
        //cards.add(new SetCardInfo("Sandshaper", 124, Rarity.UNCOMMON, mage.cards.s.Sandshaper.class));
        //cards.add(new SetCardInfo("Scarland Marauders", 125, Rarity.COMMON, mage.cards.s.ScarlandMarauders.class));
        //cards.add(new SetCardInfo("Stoneforge Assault", 126, Rarity.COMMON, mage.cards.s.StoneforgeAssault.class));
        //cards.add(new SetCardInfo("Surgebringer", 127, Rarity.COMMON, mage.cards.s.Surgebringer.class));
        //cards.add(new SetCardInfo("Tectonic Shift", 128, Rarity.COMMON, mage.cards.t.TectonicShift.class));
        //cards.add(new SetCardInfo("Terem Skirmisher", 129, Rarity.COMMON, mage.cards.t.TeremSkirmisher.class));
        //cards.add(new SetCardInfo("Terem Vanguard", 130, Rarity.UNCOMMON, mage.cards.t.TeremVanguard.class));
        //cards.add(new SetCardInfo("United Strike", 131, Rarity.COMMON, mage.cards.u.UnitedStrike.class));
        //cards.add(new SetCardInfo("Unstable Power", 132, Rarity.RARE, mage.cards.u.UnstablePower.class));
        //cards.add(new SetCardInfo("Wandering Sibyl", 133, Rarity.RARE, mage.cards.w.WanderingSibyl.class));
        //cards.add(new SetCardInfo("Warlord's Authority", 134, Rarity.UNCOMMON, mage.cards.w.WarlordsAuthority.class));
        //cards.add(new SetCardInfo("Ancient Might", 135, Rarity.COMMON, mage.cards.a.AncientMight.class));
        //cards.add(new SetCardInfo("Call of the Hive", 136, Rarity.COMMON, mage.cards.c.CallOfTheHive.class));
        //cards.add(new SetCardInfo("Channel the Heart", 137, Rarity.RARE, mage.cards.c.ChannelTheHeart.class));
        //cards.add(new SetCardInfo("Channel the Sands", 138, Rarity.UNCOMMON, mage.cards.c.ChannelTheSands.class));
        //cards.add(new SetCardInfo("Convoy Vigil", 139, Rarity.COMMON, mage.cards.c.ConvoyVigil.class));
        //cards.add(new SetCardInfo("Cut Down", 140, Rarity.COMMON, mage.cards.c.CutDown.class));
        //cards.add(new SetCardInfo("Druidic Seeker", 141, Rarity.COMMON, mage.cards.d.DruidicSeeker.class));
        //cards.add(new SetCardInfo("Dune Ambush", 142, Rarity.COMMON, mage.cards.d.DuneAmbush.class));
        //cards.add(new SetCardInfo("Erode", 143, Rarity.UNCOMMON, mage.cards.e.Erode.class));
        //cards.add(new SetCardInfo("Grandeur of the Dohar", 144, Rarity.MYTHIC, mage.cards.g.GrandeurOfTheDohar.class));
        //cards.add(new SetCardInfo("Hidden Potential", 145, Rarity.UNCOMMON, mage.cards.h.HiddenPotential.class));
        //cards.add(new SetCardInfo("Husk of the Heart Tree", 146, Rarity.RARE, mage.cards.h.HuskOfTheHeartTree.class));
        //cards.add(new SetCardInfo("Lithotic Fungi", 147, Rarity.RARE, mage.cards.l.LithoticFungi.class));
        //cards.add(new SetCardInfo("Monument Crawler", 148, Rarity.MYTHIC, mage.cards.m.MonumentCrawler.class));
        //cards.add(new SetCardInfo("Nerim Gargantuan", 149, Rarity.RARE, mage.cards.n.NerimGargantuan.class));
        //cards.add(new SetCardInfo("Nerim Patrol", 150, Rarity.COMMON, mage.cards.n.NerimPatrol.class));
        //cards.add(new SetCardInfo("Nerim Ritualist", 151, Rarity.COMMON, mage.cards.n.NerimRitualist.class));
        //cards.add(new SetCardInfo("Nerim Scavenger", 152, Rarity.UNCOMMON, mage.cards.n.NerimScavenger.class));
        //cards.add(new SetCardInfo("Nerim Scytheclaw", 153, Rarity.UNCOMMON, mage.cards.n.NerimScytheclaw.class));
        //cards.add(new SetCardInfo("Nezadar Culler", 154, Rarity.UNCOMMON, mage.cards.n.NezadarCuller.class));
        //cards.add(new SetCardInfo("Nezadar Sacrament", 155, Rarity.RARE, mage.cards.n.NezadarSacrament.class));
        //cards.add(new SetCardInfo("Oasis Pathkeepers", 156, Rarity.COMMON, mage.cards.o.OasisPathkeepers.class));
        //cards.add(new SetCardInfo("Passage of Time", 157, Rarity.COMMON, mage.cards.p.PassageOfTime.class));
        //cards.add(new SetCardInfo("Petrified Remains", 158, Rarity.UNCOMMON, mage.cards.p.PetrifiedRemains.class));
        //cards.add(new SetCardInfo("Relic Scavenger", 159, Rarity.COMMON, mage.cards.r.RelicScavenger.class));
        //cards.add(new SetCardInfo("Savage Centaurs", 160, Rarity.COMMON, mage.cards.s.SavageCentaurs.class));
        //cards.add(new SetCardInfo("Scarland Ranger", 161, Rarity.COMMON, mage.cards.s.ScarlandRanger.class));
        //cards.add(new SetCardInfo("Sheltered Life", 162, Rarity.COMMON, mage.cards.s.ShelteredLife.class));
        //cards.add(new SetCardInfo("Tel'tor Explorer", 163, Rarity.UNCOMMON, mage.cards.t.TeltorExplorer.class));
        //cards.add(new SetCardInfo("Tunnel Guard", 164, Rarity.COMMON, mage.cards.t.TunnelGuard.class));
        //cards.add(new SetCardInfo("Walk Amongst the Ancient", 165, Rarity.COMMON, mage.cards.w.WalkAmongstTheAncient.class));
        //cards.add(new SetCardInfo("Wasteland Caravan", 166, Rarity.UNCOMMON, mage.cards.w.WastelandCaravan.class));
        //cards.add(new SetCardInfo("Anatu, Queen of Ashkal", 167, Rarity.MYTHIC, mage.cards.a.AnatuQueenOfAshkal.class));
        //cards.add(new SetCardInfo("Belit, Tel'tor Emissary", 168, Rarity.RARE, mage.cards.b.BelitTeltorEmissary.class));
        //cards.add(new SetCardInfo("Bolgrim Reclaimers", 169, Rarity.UNCOMMON, mage.cards.b.BolgrimReclaimers.class));
        //cards.add(new SetCardInfo("Caravan Beastmaster", 170, Rarity.UNCOMMON, mage.cards.c.CaravanBeastmaster.class));
        //cards.add(new SetCardInfo("Dragon King Teremos", 171, Rarity.MYTHIC, mage.cards.d.DragonKingTeremos.class));
        //cards.add(new SetCardInfo("Drelum, Deepheart Seer", 172, Rarity.RARE, mage.cards.d.DrelumDeepheartSeer.class));
        //cards.add(new SetCardInfo("Marad, Truth Seeker", 173, Rarity.RARE, mage.cards.m.MaradTruthSeeker.class));
        //cards.add(new SetCardInfo("Nerim Siegebreaker", 174, Rarity.UNCOMMON, mage.cards.n.NerimSiegebreaker.class));
        //cards.add(new SetCardInfo("Nezadar Council", 175, Rarity.RARE, mage.cards.n.NezadarCouncil.class));
        //cards.add(new SetCardInfo("Pilgrim Caravan", 176, Rarity.UNCOMMON, mage.cards.p.PilgrimCaravan.class));
        //cards.add(new SetCardInfo("Roving Warlord", 177, Rarity.UNCOMMON, mage.cards.r.RovingWarlord.class));
        //cards.add(new SetCardInfo("Runic Savant", 178, Rarity.UNCOMMON, mage.cards.r.RunicSavant.class));
        //cards.add(new SetCardInfo("Scarland Despot", 179, Rarity.UNCOMMON, mage.cards.s.ScarlandDespot.class));
        //cards.add(new SetCardInfo("Seek the Mysterious", 180, Rarity.UNCOMMON, mage.cards.s.SeekTheMysterious.class));
        //cards.add(new SetCardInfo("Tel'tor Expedition", 181, Rarity.UNCOMMON, mage.cards.t.TeltorExpedition.class));
        //cards.add(new SetCardInfo("Theren, Azelduum Regent", 182, Rarity.MYTHIC, mage.cards.t.TherenAzelduumRegent.class));
        //cards.add(new SetCardInfo("Tomb Spawn", 183, Rarity.UNCOMMON, mage.cards.t.TombSpawn.class));
        //cards.add(new SetCardInfo("Aetherforge", 184, Rarity.RARE, mage.cards.a.Aetherforge.class));
        //cards.add(new SetCardInfo("Ageless Behemoth", 185, Rarity.COMMON, mage.cards.a.AgelessBehemoth.class));
        //cards.add(new SetCardInfo("Ancient Amalgam", 186, Rarity.UNCOMMON, mage.cards.a.AncientAmalgam.class));
        //cards.add(new SetCardInfo("Ancient Passageway", 187, Rarity.UNCOMMON, mage.cards.a.AncientPassageway.class));
        //cards.add(new SetCardInfo("Antique Curio", 188, Rarity.COMMON, mage.cards.a.AntiqueCurio.class));
        //cards.add(new SetCardInfo("Arcane Orrery", 189, Rarity.UNCOMMON, mage.cards.a.ArcaneOrrery.class));
        //cards.add(new SetCardInfo("Ashkal Pillarstone", 190, Rarity.UNCOMMON, mage.cards.a.AshkalPillarstone.class));
        //cards.add(new SetCardInfo("Ashkal Sentry", 191, Rarity.COMMON, mage.cards.a.AshkalSentry.class));
        //cards.add(new SetCardInfo("Barrier Skystones", 192, Rarity.UNCOMMON, mage.cards.b.BarrierSkystones.class));
        //cards.add(new SetCardInfo("Channeling Tower", 193, Rarity.UNCOMMON, mage.cards.c.ChannelingTower.class));
        //cards.add(new SetCardInfo("Clearsight Eye", 194, Rarity.RARE, mage.cards.c.ClearsightEye.class));
        //cards.add(new SetCardInfo("Coiling Matrix", 195, Rarity.UNCOMMON, mage.cards.c.CoilingMatrix.class));
        //cards.add(new SetCardInfo("Colossal Strider", 196, Rarity.UNCOMMON, mage.cards.c.ColossalStrider.class));
        //cards.add(new SetCardInfo("Crucible Attendant", 197, Rarity.COMMON, mage.cards.c.CrucibleAttendant.class));
        //cards.add(new SetCardInfo("Cryptic Cenotaphs", 198, Rarity.UNCOMMON, mage.cards.c.CrypticCenotaphs.class));
        //cards.add(new SetCardInfo("Deepwater Strider", 199, Rarity.COMMON, mage.cards.d.DeepwaterStrider.class));
        //cards.add(new SetCardInfo("Dohar Bastion", 200, Rarity.UNCOMMON, mage.cards.d.DoharBastion.class));
        //cards.add(new SetCardInfo("Dohar Mana Vault", 201, Rarity.RARE, mage.cards.d.DoharManaVault.class));
        //cards.add(new SetCardInfo("Enflamed Guardian", 202, Rarity.COMMON, mage.cards.e.EnflamedGuardian.class));
        //cards.add(new SetCardInfo("Escort of the Lost", 203, Rarity.RARE, mage.cards.e.EscortOfTheLost.class));
        //cards.add(new SetCardInfo("Eternity Simulacrum", 204, Rarity.MYTHIC, mage.cards.e.EternitySimulacrum.class));
        //cards.add(new SetCardInfo("Fading Lithograph", 205, Rarity.COMMON, mage.cards.f.FadingLithograph.class));
        //cards.add(new SetCardInfo("Forlorn Temple", 206, Rarity.RARE, mage.cards.f.ForlornTemple.class));
        //cards.add(new SetCardInfo("Fossilized Colossus", 207, Rarity.RARE, mage.cards.f.FossilizedColossus.class));
        //cards.add(new SetCardInfo("Gateway Guardian", 208, Rarity.RARE, mage.cards.g.GatewayGuardian.class));
        //cards.add(new SetCardInfo("Gliding Stoneskates", 209, Rarity.UNCOMMON, mage.cards.g.GlidingStoneskates.class));
        //cards.add(new SetCardInfo("Gnarled Overpass", 210, Rarity.UNCOMMON, mage.cards.g.GnarledOverpass.class));
        //cards.add(new SetCardInfo("Heart Tree Warden", 211, Rarity.COMMON, mage.cards.h.HeartTreeWarden.class));
        //cards.add(new SetCardInfo("Hive Protector", 212, Rarity.UNCOMMON, mage.cards.h.HiveProtector.class));
        //cards.add(new SetCardInfo("Intact Leystone", 213, Rarity.COMMON, mage.cards.i.IntactLeystone.class));
        //cards.add(new SetCardInfo("Ley Siphoner", 214, Rarity.COMMON, mage.cards.l.LeySiphoner.class));
        //cards.add(new SetCardInfo("Library Cache", 215, Rarity.UNCOMMON, mage.cards.l.LibraryCache.class));
        //cards.add(new SetCardInfo("Lost Vault", 216, Rarity.COMMON, mage.cards.l.LostVault.class));
        //cards.add(new SetCardInfo("Mantle Smasher", 217, Rarity.RARE, mage.cards.m.MantleSmasher.class));
        //cards.add(new SetCardInfo("Molten Hellion", 218, Rarity.UNCOMMON, mage.cards.m.MoltenHellion.class));
        //cards.add(new SetCardInfo("Pillar of Binding", 219, Rarity.MYTHIC, mage.cards.p.PillarOfBinding.class));
        //cards.add(new SetCardInfo("Purewrought Golem", 220, Rarity.RARE, mage.cards.p.PurewroughtGolem.class));
        //cards.add(new SetCardInfo("Purgation Failsafe", 221, Rarity.RARE, mage.cards.p.PurgationFailsafe.class));
        //cards.add(new SetCardInfo("Runeshard Charger", 222, Rarity.UNCOMMON, mage.cards.r.RuneshardCharger.class));
        //cards.add(new SetCardInfo("Runestone Citadel", 223, Rarity.UNCOMMON, mage.cards.r.RunestoneCitadel.class));
        //cards.add(new SetCardInfo("Runestone Mollusks", 224, Rarity.UNCOMMON, mage.cards.r.RunestoneMollusks.class));
        //cards.add(new SetCardInfo("Runestone Sculpture", 225, Rarity.COMMON, mage.cards.r.RunestoneSculpture.class));
        //cards.add(new SetCardInfo("Runestone Tower", 226, Rarity.COMMON, mage.cards.r.RunestoneTower.class));
        //cards.add(new SetCardInfo("Runestone Wanderer", 227, Rarity.COMMON, mage.cards.r.RunestoneWanderer.class));
        //cards.add(new SetCardInfo("Runewrought Purveyor", 228, Rarity.COMMON, mage.cards.r.RunewroughtPurveyor.class));
        //cards.add(new SetCardInfo("Sanctum Sentinel", 229, Rarity.COMMON, mage.cards.s.SanctumSentinel.class));
        //cards.add(new SetCardInfo("Scarland Reaper", 230, Rarity.UNCOMMON, mage.cards.s.ScarlandReaper.class));
        //cards.add(new SetCardInfo("Secluded Prison", 231, Rarity.UNCOMMON, mage.cards.s.SecludedPrison.class));
        //cards.add(new SetCardInfo("Shadow Vault", 232, Rarity.UNCOMMON, mage.cards.s.ShadowVault.class));
        //cards.add(new SetCardInfo("Shrouded Ruins", 233, Rarity.RARE, mage.cards.s.ShroudedRuins.class));
        //cards.add(new SetCardInfo("Skyborne Sanctuary", 234, Rarity.UNCOMMON, mage.cards.s.SkyborneSanctuary.class));
        //cards.add(new SetCardInfo("Spires of Malice", 235, Rarity.UNCOMMON, mage.cards.s.SpiresOfMalice.class));
        //cards.add(new SetCardInfo("Stonebound Shadow", 236, Rarity.COMMON, mage.cards.s.StoneboundShadow.class));
        //cards.add(new SetCardInfo("Stoneforge Archway", 237, Rarity.UNCOMMON, mage.cards.s.StoneforgeArchway.class));
        //cards.add(new SetCardInfo("Stoneforge Vestige", 238, Rarity.COMMON, mage.cards.s.StoneforgeVestige.class));
        //cards.add(new SetCardInfo("Tel'tor Gate", 239, Rarity.COMMON, mage.cards.t.TeltorGate.class));
        //cards.add(new SetCardInfo("Timeworn Foundry", 240, Rarity.RARE, mage.cards.t.TimewornFoundry.class));
        //cards.add(new SetCardInfo("Tomb Sentinel", 241, Rarity.RARE, mage.cards.t.TombSentinel.class));
        //cards.add(new SetCardInfo("Tomb Wanderer", 242, Rarity.COMMON, mage.cards.t.TombWanderer.class));
        //cards.add(new SetCardInfo("Urukh Favor", 243, Rarity.COMMON, mage.cards.u.UrukhFavor.class));
        //cards.add(new SetCardInfo("Ashkal, Civilization's Cradle", 244, Rarity.RARE, mage.cards.a.AshkalCivilizationsCradle.class));
        cards.add(new SetCardInfo("Buried Ruin", 245, Rarity.UNCOMMON, mage.cards.b.BuriedRuin.class));
        //cards.add(new SetCardInfo("Ledaru, Strait of the Shapers", 246, Rarity.RARE, mage.cards.l.LedaruStraitOfTheShapers.class));
        //cards.add(new SetCardInfo("Nezadar, the Lost City", 247, Rarity.RARE, mage.cards.n.NezadarTheLostCity.class));
        //cards.add(new SetCardInfo("Norgrod, the Ruined Forge", 248, Rarity.RARE, mage.cards.n.NorgrodTheRuinedForge.class));
        //cards.add(new SetCardInfo("Telum, Maw of the Past", 249, Rarity.RARE, mage.cards.t.TelumMawOfThePast.class));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class));
        cards.add(new SetCardInfo("Island", 251, Rarity.LAND, mage.cards.basiclands.Island.class));
        cards.add(new SetCardInfo("Swamp", 252, Rarity.LAND, mage.cards.basiclands.Swamp.class));
        cards.add(new SetCardInfo("Mountain", 253, Rarity.LAND, mage.cards.basiclands.Mountain.class));
        cards.add(new SetCardInfo("Forest", 254, Rarity.LAND, mage.cards.basiclands.Forest.class));
    }
}
