package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class SecretsOfTheRiverCities extends ExpansionSet {
    private static final SecretsOfTheRiverCities instance = new SecretsOfTheRiverCities();

    public static SecretsOfTheRiverCities getInstance() { return instance; }

    private SecretsOfTheRiverCities() {
        super("Secrets of the River Cities", "SRC", ExpansionSet.buildDate(2020, 1, 1), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 1;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Abigail, Cawyer Station Chief", 1, Rarity.RARE, mage.cards.a.AbigailCawyerStationChief.class));
        cards.add(new SetCardInfo("Adamant Will", 2, Rarity.COMMON, mage.cards.a.AdamantWill.class));
        //cards.add(new SetCardInfo("Ameret's Sanctity", 3, Rarity.RARE, mage.cards.a.AmeretsSanctity.class));
        //cards.add(new SetCardInfo("Angelic Embezzler", 4, Rarity.UNCOMMON, mage.cards.a.AngelicEmbezzler.class));
        //cards.add(new SetCardInfo("Archbishop of the Way", 5, Rarity.RARE, mage.cards.a.ArchbishopOfTheWay.class));
        cards.add(new SetCardInfo("Arrest", 6, Rarity.UNCOMMON, mage.cards.a.Arrest.class));
        //cards.add(new SetCardInfo("Backup Brigade", 7, Rarity.COMMON, mage.cards.b.BackupBrigade.class));
        //cards.add(new SetCardInfo("Blessing of Hope", 8, Rarity.COMMON, mage.cards.b.BlessingOfHope.class));
        cards.add(new SetCardInfo("Burden of Guilt", 9, Rarity.COMMON, mage.cards.b.BurdenOfGuilt.class));
        //cards.add(new SetCardInfo("Catscratch Broker", 10, Rarity.UNCOMMON, mage.cards.c.CatscratchBroker.class));
        //cards.add(new SetCardInfo("Catscratch Mafioso", 11, Rarity.COMMON, mage.cards.c.CatscratchMafioso.class));
        //cards.add(new SetCardInfo("Cawyer Station Deputy", 12, Rarity.COMMON, mage.cards.c.CawyerStationDeputy.class));
        //cards.add(new SetCardInfo("Cawyer Station Veteran", 13, Rarity.COMMON, mage.cards.c.CawyerStationVeteran.class));
        //cards.add(new SetCardInfo("Cleansing Wave", 14, Rarity.UNCOMMON, mage.cards.c.CleansingWave.class));
        //cards.add(new SetCardInfo("Dazzling Archangel", 15, Rarity.MYTHIC, mage.cards.d.DazzlingArchangel.class));
        //cards.add(new SetCardInfo("Deacon of Ameret's Way", 16, Rarity.COMMON, mage.cards.d.DeaconOfAmeretsWay.class));
        //cards.add(new SetCardInfo("Debt Collection", 17, Rarity.COMMON, mage.cards.d.DebtCollection.class));
        //cards.add(new SetCardInfo("Family Man", 18, Rarity.UNCOMMON, mage.cards.f.FamilyMan.class));
        //cards.add(new SetCardInfo("Fourth Street Enforcer", 19, Rarity.UNCOMMON, mage.cards.f.FourthStreetEnforcer.class));
        //cards.add(new SetCardInfo("Griffin's Grace", 20, Rarity.UNCOMMON, mage.cards.g.GriffinsGrace.class));
        //cards.add(new SetCardInfo("Helpful Butler", 21, Rarity.UNCOMMON, mage.cards.h.HelpfulButler.class));
        //cards.add(new SetCardInfo("Inhibit", 22, Rarity.UNCOMMON, mage.cards.i.Inhibit.class));
        //cards.add(new SetCardInfo("Interrogate", 23, Rarity.COMMON, mage.cards.i.Interrogate.class));
        //cards.add(new SetCardInfo("Jaded Copper", 24, Rarity.UNCOMMON, mage.cards.j.JadedCopper.class));
        //cards.add(new SetCardInfo("Lorre Dealbroker", 25, Rarity.RARE, mage.cards.l.LorreDealbroker.class));
        //cards.add(new SetCardInfo("Lorre Lackey", 26, Rarity.COMMON, mage.cards.l.LorreLackey.class));
        //cards.add(new SetCardInfo("Lorre Lookout", 27, Rarity.COMMON, mage.cards.l.LorreLookout.class));
        //cards.add(new SetCardInfo("Lotus Lane Kidnapper", 28, Rarity.UNCOMMON, mage.cards.l.LotusLaneKidnapper.class));
        //cards.add(new SetCardInfo("Lovebird's Gambit", 29, Rarity.RARE, mage.cards.l.LovebirdsGambit.class));
        //cards.add(new SetCardInfo("Midnight Call", 30, Rarity.COMMON, mage.cards.m.MidnightCall.class));
        //cards.add(new SetCardInfo("Mob Cleaning", 31, Rarity.COMMON, mage.cards.m.MobCleaning.class));
        cards.add(new SetCardInfo("Oblivious Handyman", 32, Rarity.COMMON, mage.cards.o.ObliviousHandyman.class));
        //cards.add(new SetCardInfo("Obsessive Bureaucrat", 33, Rarity.COMMON, mage.cards.o.ObsessiveBureaucrat.class));
        //cards.add(new SetCardInfo("Resigned Shepherd", 34, Rarity.COMMON, mage.cards.r.ResignedShepherd.class));
        //cards.add(new SetCardInfo("Shepherd Cop", 35, Rarity.COMMON, mage.cards.s.ShepherdCop.class));
        //cards.add(new SetCardInfo("Skyscraper Griffin", 36, Rarity.COMMON, mage.cards.s.SkyscraperGriffin.class));
        //cards.add(new SetCardInfo("Solo Officer", 37, Rarity.RARE, mage.cards.s.SoloOfficer.class));
        //cards.add(new SetCardInfo("Up the River", 38, Rarity.UNCOMMON, mage.cards.u.UpTheRiver.class));
        //cards.add(new SetCardInfo("Watchful Griffin", 39, Rarity.RARE, mage.cards.w.WatchfulGriffin.class));
        //cards.add(new SetCardInfo("Aerial Sleuth", 40, Rarity.COMMON, mage.cards.a.AerialSleuth.class));
        //cards.add(new SetCardInfo("Amnesiac Sleuth", 41, Rarity.COMMON, mage.cards.a.AmnesiacSleuth.class));
        //cards.add(new SetCardInfo("Associate of the Spider", 42, Rarity.COMMON, mage.cards.a.AssociateOfTheSpider.class));
        //cards.add(new SetCardInfo("Barton, Sleuth Extraordinaire", 43, Rarity.RARE, mage.cards.b.BartonSleuthExtraordinaire.class));
        //cards.add(new SetCardInfo("Blank Memory", 44, Rarity.UNCOMMON, mage.cards.b.BlankMemory.class));
        //cards.add(new SetCardInfo("Clandestine Snitch", 45, Rarity.COMMON, mage.cards.c.ClandestineSnitch.class));
        //cards.add(new SetCardInfo("Confiscate Evidence", 46, Rarity.RARE, mage.cards.c.ConfiscateEvidence.class));
        //cards.add(new SetCardInfo("Conspiracy Vendor", 47, Rarity.COMMON, mage.cards.c.ConspiracyVendor.class));
        //cards.add(new SetCardInfo("Crippling Hallucinations", 48, Rarity.UNCOMMON, mage.cards.c.CripplingHallucinations.class));
        //cards.add(new SetCardInfo("Detective's Gambit", 49, Rarity.RARE, mage.cards.d.DetectivesGambit.class));
        //cards.add(new SetCardInfo("Detective's Intuition", 50, Rarity.COMMON, mage.cards.d.DetectivesIntuition.class));
        //cards.add(new SetCardInfo("Detective's Ploy", 51, Rarity.UNCOMMON, mage.cards.d.DetectivesPloy.class));
        //cards.add(new SetCardInfo("Double Agent", 52, Rarity.RARE, mage.cards.d.DoubleAgent.class));
        //cards.add(new SetCardInfo("Dreamer of the Opulent", 53, Rarity.UNCOMMON, mage.cards.d.DreamerOfTheOpulent.class));
        //cards.add(new SetCardInfo("Endless Paper Trail", 54, Rarity.MYTHIC, mage.cards.e.EndlessPaperTrail.class));
        //cards.add(new SetCardInfo("Ensorcellor", 55, Rarity.RARE, mage.cards.e.Ensorcellor.class));
        //cards.add(new SetCardInfo("Escape the Plane", 56, Rarity.RARE, mage.cards.e.EscapeThePlane.class));
        //cards.add(new SetCardInfo("Examine the Goods", 57, Rarity.COMMON, mage.cards.e.ExamineTheGoods.class));
        //cards.add(new SetCardInfo("Faceless Stalker", 58, Rarity.UNCOMMON, mage.cards.f.FacelessStalker.class));
        //cards.add(new SetCardInfo("Foiled Plans", 59, Rarity.COMMON, mage.cards.f.FoiledPlans.class));
        //cards.add(new SetCardInfo("Forbidden Findings", 60, Rarity.UNCOMMON, mage.cards.f.ForbiddenFindings.class));
        //cards.add(new SetCardInfo("Frankie's Frostmage", 61, Rarity.UNCOMMON, mage.cards.f.FrankiesFrostmage.class));
        //cards.add(new SetCardInfo("Guide Dog", 62, Rarity.COMMON, mage.cards.g.GuideDog.class));
        //cards.add(new SetCardInfo("Malevolent Observer", 63, Rarity.COMMON, mage.cards.m.MalevolentObserver.class));
        cards.add(new SetCardInfo("Master Thief", 64, Rarity.UNCOMMON, mage.cards.m.MasterThief.class));
        //cards.add(new SetCardInfo("Messenger Magpie", 65, Rarity.UNCOMMON, mage.cards.m.MessengerMagpie.class));
        //cards.add(new SetCardInfo("Occultist of Heirlooms", 66, Rarity.COMMON, mage.cards.o.OccultistOfHeirlooms.class));
        //cards.add(new SetCardInfo("Overworked", 67, Rarity.COMMON, mage.cards.o.Overworked.class));
        //cards.add(new SetCardInfo("Phantom's Jurisdiction", 68, Rarity.COMMON, mage.cards.p.PhantomsJurisdiction.class));
        //cards.add(new SetCardInfo("Private Eye", 69, Rarity.COMMON, mage.cards.p.PrivateEye.class));
        //cards.add(new SetCardInfo("Quick-Witted Detective", 70, Rarity.RARE, mage.cards.q.QuickWittedDetective.class));
        cards.add(new SetCardInfo("Rescue", 71, Rarity.COMMON, mage.cards.r.Rescue.class));
        //cards.add(new SetCardInfo("Ride to Nowhere", 72, Rarity.COMMON, mage.cards.r.RideToNowhere.class));
        //cards.add(new SetCardInfo("Sleep with the Fishes", 73, Rarity.COMMON, mage.cards.s.SleepWithTheFishes.class));
        //cards.add(new SetCardInfo("Slippery Informant", 74, Rarity.UNCOMMON, mage.cards.s.SlipperyInformant.class));
        //cards.add(new SetCardInfo("Spill the Beans", 75, Rarity.COMMON, mage.cards.s.SpillTheBeans.class));
        //cards.add(new SetCardInfo("Tethaleeg, the Opulent", 76, Rarity.MYTHIC, mage.cards.t.TethaleegTheOpulent.class));
        //cards.add(new SetCardInfo("Throw Off the Trail", 77, Rarity.UNCOMMON, mage.cards.t.ThrowOffTheTrail.class));
        //cards.add(new SetCardInfo("Uncanny Duplicant", 78, Rarity.RARE, mage.cards.u.UncannyDuplicant.class));
        //cards.add(new SetCardInfo("Witness Protection", 79, Rarity.UNCOMMON, mage.cards.w.WitnessProtection.class));
        //cards.add(new SetCardInfo("Woman with a Story", 80, Rarity.COMMON, mage.cards.w.WomanWithAStory.class));
        //cards.add(new SetCardInfo("Air of Decay", 81, Rarity.UNCOMMON, mage.cards.a.AirOfDecay.class));
        //cards.add(new SetCardInfo("Alley Shade", 82, Rarity.COMMON, mage.cards.a.AlleyShade.class));
        //cards.add(new SetCardInfo("Brutalize", 83, Rarity.COMMON, mage.cards.b.Brutalize.class));
        //cards.add(new SetCardInfo("Calling Card", 84, Rarity.RARE, mage.cards.c.CallingCard.class));
        //cards.add(new SetCardInfo("Choking Demise", 85, Rarity.COMMON, mage.cards.c.ChokingDemise.class));
        //cards.add(new SetCardInfo("Conspicuous Homicide", 86, Rarity.UNCOMMON, mage.cards.c.ConspicuousHomicide.class));
        //cards.add(new SetCardInfo("Corrupt Defrauder", 87, Rarity.COMMON, mage.cards.c.CorruptDefrauder.class));
        //cards.add(new SetCardInfo("Cryptid's Gambit", 88, Rarity.RARE, mage.cards.c.CryptidsGambit.class));
        //cards.add(new SetCardInfo("Dame on the Run", 89, Rarity.COMMON, mage.cards.d.DameOnTheRun.class));
        cards.add(new SetCardInfo("Duress", 90, Rarity.COMMON, mage.cards.d.Duress.class));
        cards.add(new SetCardInfo("Exsanguinate", 91, Rarity.UNCOMMON, mage.cards.e.Exsanguinate.class));
        //cards.add(new SetCardInfo("Fatal Flaw", 92, Rarity.COMMON, mage.cards.f.FatalFlaw.class));
        //cards.add(new SetCardInfo("Fishing for Bodies", 93, Rarity.COMMON, mage.cards.f.FishingForBodies.class));
        //cards.add(new SetCardInfo("Hound of Rounded Corners", 94, Rarity.COMMON, mage.cards.h.HoundOfRoundedCorners.class));
        //cards.add(new SetCardInfo("Infernal Haunting", 95, Rarity.UNCOMMON, mage.cards.i.InfernalHaunting.class));
        //cards.add(new SetCardInfo("Liliana, Femme Fatale", 96, Rarity.MYTHIC, mage.cards.l.LilianaFemmeFatale.class));
        //cards.add(new SetCardInfo("Liliana's Goon", 97, Rarity.RARE, mage.cards.l.LilianasGoon.class));
        //cards.add(new SetCardInfo("Liturgy of Liliana", 98, Rarity.UNCOMMON, mage.cards.l.LiturgyOfLiliana.class));
        //cards.add(new SetCardInfo("Lorre Blackmailer", 99, Rarity.COMMON, mage.cards.l.LorreBlackmailer.class));
        //cards.add(new SetCardInfo("Lorre Earner", 100, Rarity.UNCOMMON, mage.cards.l.LorreEarner.class));
        //cards.add(new SetCardInfo("Lucky Break", 101, Rarity.COMMON, mage.cards.l.LuckyBreak.class));
        //cards.add(new SetCardInfo("Lurker on the Walls", 102, Rarity.RARE, mage.cards.l.LurkerOnTheWalls.class));
        //cards.add(new SetCardInfo("Mafia Capo", 103, Rarity.UNCOMMON, mage.cards.m.MafiaCapo.class));
        //cards.add(new SetCardInfo("Memory Hostage", 104, Rarity.RARE, mage.cards.m.MemoryHostage.class));
        //cards.add(new SetCardInfo("Morgue Manager", 105, Rarity.RARE, mage.cards.m.MorgueManager.class));
        //cards.add(new SetCardInfo("Moroii Aristocrat", 106, Rarity.COMMON, mage.cards.m.MoroiiAristocrat.class));
        cards.add(new SetCardInfo("Murder", 107, Rarity.UNCOMMON, mage.cards.m.Murder.class));
        //cards.add(new SetCardInfo("Murder Spree", 108, Rarity.RARE, mage.cards.m.MurderSpree.class));
        //cards.add(new SetCardInfo("Ne'er-do-wells", 109, Rarity.COMMON, mage.cards.n.NeerDoWells.class));
        //cards.add(new SetCardInfo("Nimble Mothman", 110, Rarity.COMMON, mage.cards.n.NimbleMothman.class));
        //cards.add(new SetCardInfo("Nrom, the Chthonic", 111, Rarity.MYTHIC, mage.cards.n.NromTheChthonic.class));
        //cards.add(new SetCardInfo("Ocular Fog", 112, Rarity.COMMON, mage.cards.o.OcularFog.class));
        //cards.add(new SetCardInfo("Patron of Veda's Club", 113, Rarity.UNCOMMON, mage.cards.p.PatronOfVedasClub.class));
        //cards.add(new SetCardInfo("Rigged Negotiations", 114, Rarity.UNCOMMON, mage.cards.r.RiggedNegotiations.class));
        //cards.add(new SetCardInfo("Seductive Gorgon", 115, Rarity.COMMON, mage.cards.s.SeductiveGorgon.class));
        //cards.add(new SetCardInfo("Stalking Neonate", 116, Rarity.UNCOMMON, mage.cards.s.StalkingNeonate.class));
        //cards.add(new SetCardInfo("Successful Racket", 117, Rarity.COMMON, mage.cards.s.SuccessfulRacket.class));
        //cards.add(new SetCardInfo("Undead Flapper", 118, Rarity.COMMON, mage.cards.u.UndeadFlapper.class));
        //cards.add(new SetCardInfo("Vicious Cleaner", 119, Rarity.RARE, mage.cards.v.ViciousCleaner.class));
        //cards.add(new SetCardInfo("Vile Blessing", 120, Rarity.COMMON, mage.cards.v.VileBlessing.class));
        //cards.add(new SetCardInfo("Zhang Traveller", 121, Rarity.UNCOMMON, mage.cards.z.ZhangTraveller.class));
        //cards.add(new SetCardInfo("Abrupt Possession", 122, Rarity.COMMON, mage.cards.a.AbruptPossession.class));
        cards.add(new SetCardInfo("Act on Impulse", 123, Rarity.UNCOMMON, mage.cards.a.ActOnImpulse.class));
        //cards.add(new SetCardInfo("All-Out Assault", 124, Rarity.UNCOMMON, mage.cards.a.AllOutAssault.class));
        //cards.add(new SetCardInfo("Azra Fixer", 125, Rarity.COMMON, mage.cards.a.AzraFixer.class));
        //cards.add(new SetCardInfo("Blazing Shot", 126, Rarity.COMMON, mage.cards.b.BlazingShot.class));
        //cards.add(new SetCardInfo("Bloodthirst Vampire", 127, Rarity.COMMON, mage.cards.b.BloodthirstVampire.class));
        //cards.add(new SetCardInfo("Borrowed Time", 128, Rarity.MYTHIC, mage.cards.b.BorrowedTime.class));
        //cards.add(new SetCardInfo("Buddy Cops", 129, Rarity.COMMON, mage.cards.b.BuddyCops.class));
        //cards.add(new SetCardInfo("Cartel Muscle", 130, Rarity.UNCOMMON, mage.cards.c.CartelMuscle.class));
        //cards.add(new SetCardInfo("Cityscape Dragon", 131, Rarity.MYTHIC, mage.cards.c.CityscapeDragon.class));
        //cards.add(new SetCardInfo("Crime Spree", 132, Rarity.RARE, mage.cards.c.CrimeSpree.class));
        //cards.add(new SetCardInfo("Deranged Cultist", 133, Rarity.COMMON, mage.cards.d.DerangedCultist.class));
        //cards.add(new SetCardInfo("Distracting Flapper", 134, Rarity.COMMON, mage.cards.d.DistractingFlapper.class));
        //cards.add(new SetCardInfo("Dramatic End", 135, Rarity.RARE, mage.cards.d.DramaticEnd.class));
        //cards.add(new SetCardInfo("Dwarven Butcher", 136, Rarity.COMMON, mage.cards.d.DwarvenButcher.class));
        //cards.add(new SetCardInfo("Elvish Poet", 137, Rarity.COMMON, mage.cards.e.ElvishPoet.class));
        cards.add(new SetCardInfo("Fleeting Options", 138, Rarity.UNCOMMON, mage.cards.f.FleetingOptions.class));
        //cards.add(new SetCardInfo("Getaway Ride", 139, Rarity.COMMON, mage.cards.g.GetawayRide.class));
        //cards.add(new SetCardInfo("Go Nuts", 140, Rarity.UNCOMMON, mage.cards.g.GoNuts.class));
        //cards.add(new SetCardInfo("Harsh Commander", 141, Rarity.UNCOMMON, mage.cards.h.HarshCommander.class));
        //cards.add(new SetCardInfo("Heavenly Fire", 142, Rarity.COMMON, mage.cards.h.HeavenlyFire.class));
        //cards.add(new SetCardInfo("Illicit Electromancer", 143, Rarity.UNCOMMON, mage.cards.i.IllicitElectromancer.class));
        //cards.add(new SetCardInfo("Inciting Charmer", 144, Rarity.UNCOMMON, mage.cards.i.IncitingCharmer.class));
        cards.add(new SetCardInfo("Off-Duty Officer", 145, Rarity.COMMON, mage.cards.o.OffDutyOfficer.class));
        //cards.add(new SetCardInfo("Officer's Gambit", 146, Rarity.RARE, mage.cards.o.OfficersGambit.class));
        //cards.add(new SetCardInfo("Orphanage Keeper", 147, Rarity.UNCOMMON, mage.cards.o.OrphanageKeeper.class));
        //cards.add(new SetCardInfo("Passionate Reunion", 148, Rarity.COMMON, mage.cards.p.PassionateReunion.class));
        //cards.add(new SetCardInfo("Pencil Pusher", 149, Rarity.UNCOMMON, mage.cards.p.PencilPusher.class));
        //cards.add(new SetCardInfo("Psionic Burst", 150, Rarity.UNCOMMON, mage.cards.p.PsionicBurst.class));
        //cards.add(new SetCardInfo("Reckless Corporal", 151, Rarity.COMMON, mage.cards.r.RecklessCorporal.class));
        //cards.add(new SetCardInfo("Sermon of the Way", 152, Rarity.UNCOMMON, mage.cards.s.SermonOfTheWay.class));
        //cards.add(new SetCardInfo("Shank", 153, Rarity.COMMON, mage.cards.s.Shank.class));
        //cards.add(new SetCardInfo("Station Seven Host", 154, Rarity.RARE, mage.cards.s.StationSevenHost.class));
        //cards.add(new SetCardInfo("Street Razings", 155, Rarity.COMMON, mage.cards.s.StreetRazings.class));
        //cards.add(new SetCardInfo("Threatening Officer", 156, Rarity.COMMON, mage.cards.t.ThreateningOfficer.class));
        //cards.add(new SetCardInfo("Torch Singer", 157, Rarity.RARE, mage.cards.t.TorchSinger.class));
        //cards.add(new SetCardInfo("Vehement Rage", 158, Rarity.COMMON, mage.cards.v.VehementRage.class));
        //cards.add(new SetCardInfo("Vigilante Firebug", 159, Rarity.RARE, mage.cards.v.VigilanteFirebug.class));
        //cards.add(new SetCardInfo("Wealthy Patron", 160, Rarity.COMMON, mage.cards.w.WealthyPatron.class));
        //cards.add(new SetCardInfo("A World of Crime", 161, Rarity.RARE, mage.cards.a.AWorldOfCrime.class));
        //cards.add(new SetCardInfo("Alluring Spirit", 162, Rarity.UNCOMMON, mage.cards.a.AlluringSpirit.class));
        //cards.add(new SetCardInfo("Bizarre Menagerie", 163, Rarity.UNCOMMON, mage.cards.b.BizarreMenagerie.class));
        //cards.add(new SetCardInfo("Butcher the Shepherd", 164, Rarity.COMMON, mage.cards.b.ButcherTheShepherd.class));
        //cards.add(new SetCardInfo("Cover Up", 165, Rarity.COMMON, mage.cards.c.CoverUp.class));
        //cards.add(new SetCardInfo("Decipher the Evidence", 166, Rarity.COMMON, mage.cards.d.DecipherTheEvidence.class));
        //cards.add(new SetCardInfo("Dose of Dust", 167, Rarity.COMMON, mage.cards.d.DoseOfDust.class));
        //cards.add(new SetCardInfo("Dust Smugglers", 168, Rarity.COMMON, mage.cards.d.DustSmugglers.class));
        //cards.add(new SetCardInfo("Embiggen", 169, Rarity.UNCOMMON, mage.cards.e.Embiggen.class));
        cards.add(new SetCardInfo("Epic Confrontation", 170, Rarity.COMMON, mage.cards.e.EpicConfrontation.class));
        //cards.add(new SetCardInfo("Following the Matchbook", 171, Rarity.COMMON, mage.cards.f.FollowingTheMatchbook.class));
        //cards.add(new SetCardInfo("Fox Agency Operator", 172, Rarity.RARE, mage.cards.f.FoxAgencyOperator.class));
        //cards.add(new SetCardInfo("Fox Agency Sleuths", 173, Rarity.UNCOMMON, mage.cards.f.FoxAgencySleuths.class));
        //cards.add(new SetCardInfo("Hidden in the Outlands", 174, Rarity.RARE, mage.cards.h.HiddenInTheOutlands.class));
        //cards.add(new SetCardInfo("Jericho's Assistant", 175, Rarity.RARE, mage.cards.j.JerichosAssistant.class));
        //cards.add(new SetCardInfo("Lotus Lane Socialite", 176, Rarity.COMMON, mage.cards.l.LotusLaneSocialite.class));
        //cards.add(new SetCardInfo("Manipulative Phantom", 177, Rarity.UNCOMMON, mage.cards.m.ManipulativePhantom.class));
        //cards.add(new SetCardInfo("Moribund Witness", 178, Rarity.COMMON, mage.cards.m.MoribundWitness.class));
        //cards.add(new SetCardInfo("Mystery of the Strange Door", 179, Rarity.MYTHIC, mage.cards.m.MysteryOfTheStrangeDoor.class));
        //cards.add(new SetCardInfo("Occultist's Gambit", 180, Rarity.RARE, mage.cards.o.OccultistsGambit.class));
        //cards.add(new SetCardInfo("Orc Reporter", 181, Rarity.UNCOMMON, mage.cards.o.OrcReporter.class));
        //cards.add(new SetCardInfo("Outlands Farmer", 182, Rarity.COMMON, mage.cards.o.OutlandsFarmer.class));
        //cards.add(new SetCardInfo("Primordial Unveiling", 183, Rarity.RARE, mage.cards.p.PrimordialUnveiling.class));
        //cards.add(new SetCardInfo("Protective Detective", 184, Rarity.UNCOMMON, mage.cards.p.ProtectiveDetective.class));
        //cards.add(new SetCardInfo("Rat-Eater", 185, Rarity.RARE, mage.cards.r.RatEater.class));
        //cards.add(new SetCardInfo("Resounding Shot", 186, Rarity.UNCOMMON, mage.cards.r.ResoundingShot.class));
        //cards.add(new SetCardInfo("Rhulha, the Aberrant", 187, Rarity.MYTHIC, mage.cards.r.RhulhaTheAberrant.class));
        //cards.add(new SetCardInfo("Rhulha's Lamb", 188, Rarity.COMMON, mage.cards.r.RhulhasLamb.class));
        //cards.add(new SetCardInfo("Sewer Gators", 189, Rarity.COMMON, mage.cards.s.SewerGators.class));
        //cards.add(new SetCardInfo("Share the Concoction", 190, Rarity.UNCOMMON, mage.cards.s.ShareTheConcoction.class));
        //cards.add(new SetCardInfo("Sinuous Tantalizer", 191, Rarity.UNCOMMON, mage.cards.s.SinuousTantalizer.class));
        //cards.add(new SetCardInfo("Sleuthhound", 192, Rarity.COMMON, mage.cards.s.Sleuthhound.class));
        //cards.add(new SetCardInfo("Songmistress of the Rivers", 193, Rarity.RARE, mage.cards.s.SongmistressOfTheRivers.class));
        //cards.add(new SetCardInfo("Spectral Boon", 194, Rarity.UNCOMMON, mage.cards.s.SpectralBoon.class));
        //cards.add(new SetCardInfo("Stone-Faced Gumshoe", 195, Rarity.UNCOMMON, mage.cards.s.StoneFacedGumshoe.class));
        //cards.add(new SetCardInfo("Towering Aracatnid", 196, Rarity.COMMON, mage.cards.t.ToweringAracatnid.class));
        //cards.add(new SetCardInfo("Uncanny Woodghast", 197, Rarity.RARE, mage.cards.u.UncannyWoodghast.class));
        //cards.add(new SetCardInfo("Uncover Evidence", 198, Rarity.COMMON, mage.cards.u.UncoverEvidence.class));
        //cards.add(new SetCardInfo("Unexplained Behemoth", 199, Rarity.COMMON, mage.cards.u.UnexplainedBehemoth.class));
        //cards.add(new SetCardInfo("Vine Street Stoolie", 200, Rarity.COMMON, mage.cards.v.VineStreetStoolie.class));
        //cards.add(new SetCardInfo("Wander the Outlands", 201, Rarity.COMMON, mage.cards.w.WanderTheOutlands.class));
        //cards.add(new SetCardInfo("Writhing Thrasher", 202, Rarity.COMMON, mage.cards.w.WrithingThrasher.class));
        //cards.add(new SetCardInfo("Agency Detectives", 203, Rarity.UNCOMMON, mage.cards.a.AgencyDetectives.class));
        //cards.add(new SetCardInfo("Ameret, Hope of Night", 204, Rarity.MYTHIC, mage.cards.a.AmeretHopeOfNight.class));
        //cards.add(new SetCardInfo("Black Dogs of Eve's Garden", 205, Rarity.UNCOMMON, mage.cards.b.BlackDogsOfEvesGarden.class));
        //cards.add(new SetCardInfo("Chief of District Nine", 206, Rarity.UNCOMMON, mage.cards.c.ChiefOfDistrictNine.class));
        //cards.add(new SetCardInfo("Cult Leader", 207, Rarity.MYTHIC, mage.cards.c.CultLeader.class));
        //cards.add(new SetCardInfo("Eldritch Spirit", 208, Rarity.UNCOMMON, mage.cards.e.EldritchSpirit.class));
        //cards.add(new SetCardInfo("Elusive Stranger", 209, Rarity.UNCOMMON, mage.cards.e.ElusiveStranger.class));
        //cards.add(new SetCardInfo("Frankie \"the Spider\" Lorre", 210, Rarity.RARE, mage.cards.f.FrankieTheSpiderLorre.class));
        //cards.add(new SetCardInfo("Gregor Eddie, Dustmaker", 211, Rarity.RARE, mage.cards.g.GregorEddieDustmaker.class));
        cards.add(new SetCardInfo("Henry, River Cities Mayor", 212, Rarity.MYTHIC, mage.cards.h.HenryRiverCitiesMayor.class));
        //cards.add(new SetCardInfo("Incident on Fourth Street", 213, Rarity.RARE, mage.cards.i.IncidentOnFourthStreet.class));
        //cards.add(new SetCardInfo("Jericho Hudson", 214, Rarity.MYTHIC, mage.cards.j.JerichoHudson.class));
        //cards.add(new SetCardInfo("Loose End Cutter", 215, Rarity.UNCOMMON, mage.cards.l.LooseEndCutter.class));
        //cards.add(new SetCardInfo("Lorre Underboss", 216, Rarity.UNCOMMON, mage.cards.l.LorreUnderboss.class));
        //cards.add(new SetCardInfo("The Masked Benefactor", 217, Rarity.MYTHIC, mage.cards.t.TheMaskedBenefactor.class));
        //cards.add(new SetCardInfo("Murderous Moroii", 218, Rarity.UNCOMMON, mage.cards.m.MurderousMoroii.class));
        //cards.add(new SetCardInfo("Painter of the Waking Dream", 219, Rarity.RARE, mage.cards.p.PainterOfTheWakingDream.class));
        //cards.add(new SetCardInfo("Perfect Crime", 220, Rarity.RARE, mage.cards.p.PerfectCrime.class));
        //cards.add(new SetCardInfo("Prying Lawmaker", 221, Rarity.UNCOMMON, mage.cards.p.PryingLawmaker.class));
        //cards.add(new SetCardInfo("Scandalous Phantom", 222, Rarity.UNCOMMON, mage.cards.s.ScandalousPhantom.class));
        //cards.add(new SetCardInfo("Wayward Lawkeeper", 223, Rarity.RARE, mage.cards.w.WaywardLawkeeper.class));
        //cards.add(new SetCardInfo("Attentive Rabota", 224, Rarity.RARE, mage.cards.a.AttentiveRabota.class));
        //cards.add(new SetCardInfo("Contraband Dagger", 225, Rarity.COMMON, mage.cards.c.ContrabandDagger.class));
        //cards.add(new SetCardInfo("Copper Copper", 226, Rarity.COMMON, mage.cards.c.CopperCopper.class));
        //cards.add(new SetCardInfo("Counterfeit Currency", 227, Rarity.UNCOMMON, mage.cards.c.CounterfeitCurrency.class));
        cards.add(new SetCardInfo("Coveted Jewel", 228, Rarity.RARE, mage.cards.c.CovetedJewel.class));
        cards.add(new SetCardInfo("Cozy Rabota", 229, Rarity.COMMON, mage.cards.c.CozyRabota.class));
        //cards.add(new SetCardInfo("Detective's Familiar", 230, Rarity.UNCOMMON, mage.cards.d.DetectivesFamiliar.class));
        //cards.add(new SetCardInfo("Forged Documents", 231, Rarity.UNCOMMON, mage.cards.f.ForgedDocuments.class));
        //cards.add(new SetCardInfo("Impenetrable Vault", 232, Rarity.RARE, mage.cards.i.ImpenetrableVault.class));
        cards.add(new SetCardInfo("Magnifying Glass", 233, Rarity.UNCOMMON, mage.cards.m.MagnifyingGlass.class));
        //cards.add(new SetCardInfo("Murder Weapon", 234, Rarity.UNCOMMON, mage.cards.m.MurderWeapon.class));
        //cards.add(new SetCardInfo("Pilfered Jewels", 235, Rarity.COMMON, mage.cards.p.PilferedJewels.class));
        //cards.add(new SetCardInfo("Portrait of the Lost", 236, Rarity.UNCOMMON, mage.cards.p.PortraitOfTheLost.class));
        //cards.add(new SetCardInfo("Rabota Bystander", 237, Rarity.UNCOMMON, mage.cards.r.RabotaBystander.class));
        //cards.add(new SetCardInfo("Shroud of Disguise", 238, Rarity.RARE, mage.cards.s.ShroudOfDisguise.class));
        //cards.add(new SetCardInfo("Tome of the Primordials", 239, Rarity.MYTHIC, mage.cards.t.TomeOfThePrimordials.class));
        //cards.add(new SetCardInfo("Trench Sweeper", 240, Rarity.COMMON, mage.cards.t.TrenchSweeper.class));
        //cards.add(new SetCardInfo("Unlicensed Pistol", 241, Rarity.UNCOMMON, mage.cards.u.UnlicensedPistol.class));
        //cards.add(new SetCardInfo("Baron's Skyscrapers", 242, Rarity.RARE, mage.cards.b.BaronsSkyscrapers.class));
        //cards.add(new SetCardInfo("Benefactor's Ballroom", 243, Rarity.RARE, mage.cards.b.BenefactorsBallroom.class));
        //cards.add(new SetCardInfo("Bureaucrat's Office", 244, Rarity.RARE, mage.cards.b.BureaucratsOffice.class));
        //cards.add(new SetCardInfo("Cultivator's Sanctuary", 245, Rarity.RARE, mage.cards.c.CultivatorsSanctuary.class));
        //cards.add(new SetCardInfo("Luxury District", 246, Rarity.UNCOMMON, mage.cards.l.LuxuryDistrict.class));
        //cards.add(new SetCardInfo("Rogue's Alleyway", 247, Rarity.RARE, mage.cards.r.RoguesAlleyway.class));
        //cards.add(new SetCardInfo("Rural Sinkhole", 248, Rarity.UNCOMMON, mage.cards.r.RuralSinkhole.class));
        cards.add(new SetCardInfo("Warped Landscape", 249, Rarity.COMMON, mage.cards.w.WarpedLandscape.class));
        cards.add(new SetCardInfo("Plains", 250, Rarity.LAND, mage.cards.basiclands.Plains.class));
        cards.add(new SetCardInfo("Island", 251, Rarity.LAND, mage.cards.basiclands.Island.class));
        cards.add(new SetCardInfo("Swamp", 252, Rarity.LAND, mage.cards.basiclands.Swamp.class));
        cards.add(new SetCardInfo("Mountain", 253, Rarity.LAND, mage.cards.basiclands.Mountain.class));
        cards.add(new SetCardInfo("Forest", 254, Rarity.LAND, mage.cards.basiclands.Forest.class));
    }
}
