package mage.sets;

import mage.cards.ExpansionSet;
import mage.constants.Rarity;
import mage.constants.SetType;

/**
 * @author Fenhl
 */
public final class Vastuum extends ExpansionSet {
    private static final Vastuum instance = new Vastuum();

    public static Vastuum getInstance() { return instance; }

    private Vastuum() {
        super("Vastuum", "VST", ExpansionSet.buildDate(2018, 6, 18), SetType.CUSTOM_SET);
        this.hasBoosters = true;
        this.hasBasicLands = true;
        this.numBoosterLands = 0;
        this.numBoosterCommon = 10;
        this.numBoosterUncommon = 3;
        this.numBoosterRare = 1;
        this.ratioBoosterMythic = 8;

        //cards.add(new SetCardInfo("Karn, Heart of Guilt", 1, Rarity.MYTHIC, mage.cards.k.KarnHeartOfGuilt.class));
        //cards.add(new SetCardInfo("Angel of Dismay", 2, Rarity.MYTHIC, mage.cards.a.AngelOfDismay.class));
        //cards.add(new SetCardInfo("Caravan Skyrider", 3, Rarity.COMMON, mage.cards.c.CaravanSkyrider.class));
        //cards.add(new SetCardInfo("Chosen of the Faultless", 4, Rarity.UNCOMMON, mage.cards.c.ChosenOfTheFaultless.class));
        //cards.add(new SetCardInfo("Convoy Forerunner", 5, Rarity.RARE, mage.cards.c.ConvoyForerunner.class));
        //cards.add(new SetCardInfo("Convoy Laggu-Rider", 6, Rarity.COMMON, mage.cards.c.ConvoyLagguRider.class));
        //cards.add(new SetCardInfo("Disciple of the Faultless", 7, Rarity.COMMON, mage.cards.d.DiscipleOfTheFaultless.class));
        //cards.add(new SetCardInfo("Dune Banneret", 8, Rarity.COMMON, mage.cards.d.DuneBanneret.class));
        //cards.add(new SetCardInfo("Endtimes Hatchling", 9, Rarity.COMMON, mage.cards.e.EndtimesHatchling.class));
        //cards.add(new SetCardInfo("Enrobe in Light", 10, Rarity.UNCOMMON, mage.cards.e.EnrobeInLight.class));
        //cards.add(new SetCardInfo("Flawed Undertaking", 11, Rarity.COMMON, mage.cards.f.FlawedUndertaking.class));
        //cards.add(new SetCardInfo("Forlorn Firstspear", 12, Rarity.UNCOMMON, mage.cards.f.ForlornFirstspear.class));
        //cards.add(new SetCardInfo("Griffin Taming", 13, Rarity.COMMON, mage.cards.g.GriffinTaming.class));
        //cards.add(new SetCardInfo("Guardian-Wing Griffin", 14, Rarity.RARE, mage.cards.g.GuardianWingGriffin.class));
        cards.add(new SetCardInfo("Isolation Zone", 15, Rarity.COMMON, mage.cards.i.IsolationZone.class));
        //cards.add(new SetCardInfo("Last of Us", 16, Rarity.RARE, mage.cards.l.LastOfUs.class));
        //cards.add(new SetCardInfo("Left to Time", 17, Rarity.UNCOMMON, mage.cards.l.LeftToTime.class));
        cards.add(new SetCardInfo("Luma's Kindred", 18, Rarity.COMMON, mage.cards.l.LumasKindred.class));
        //cards.add(new SetCardInfo("Naomi's Faithful", 19, Rarity.UNCOMMON, mage.cards.n.NaomisFaithful.class));
        //cards.add(new SetCardInfo("Nivia's Regret", 20, Rarity.UNCOMMON, mage.cards.n.NiviasRegret.class));
        //cards.add(new SetCardInfo("Nomad Enforcer", 21, Rarity.COMMON, mage.cards.n.NomadEnforcer.class));
        //cards.add(new SetCardInfo("Nomad's Companion", 22, Rarity.COMMON, mage.cards.n.NomadsCompanion.class));
        //cards.add(new SetCardInfo("Oasis Seeker", 23, Rarity.COMMON, mage.cards.o.OasisSeeker.class));
        //cards.add(new SetCardInfo("Overcome the Dunes", 24, Rarity.COMMON, mage.cards.o.OvercomeTheDunes.class));
        //cards.add(new SetCardInfo("Path of Resilience", 25, Rarity.UNCOMMON, mage.cards.p.PathOfResilience.class));
        //cards.add(new SetCardInfo("Repel the Impure", 26, Rarity.UNCOMMON, mage.cards.r.RepelTheImpure.class));
        //cards.add(new SetCardInfo("Resigned Seraph", 27, Rarity.COMMON, mage.cards.r.ResignedSeraph.class));
        //cards.add(new SetCardInfo("Runic Sealer", 28, Rarity.RARE, mage.cards.r.RunicSealer.class));
        //cards.add(new SetCardInfo("Sanctum's Light", 29, Rarity.COMMON, mage.cards.s.SanctumsLight.class));
        //cards.add(new SetCardInfo("Saviour of the Lost", 30, Rarity.RARE, mage.cards.s.SaviourOfTheLost.class));
        //cards.add(new SetCardInfo("Seek Out Survivors", 31, Rarity.UNCOMMON, mage.cards.s.SeekOutSurvivors.class));
        cards.add(new SetCardInfo("Seize the Initiative", 32, Rarity.COMMON, mage.cards.s.SeizeTheInitiative.class));
        //cards.add(new SetCardInfo("Sentry Griffin", 33, Rarity.UNCOMMON, mage.cards.s.SentryGriffin.class));
        //cards.add(new SetCardInfo("Skywatch Brigade", 34, Rarity.UNCOMMON, mage.cards.s.SkywatchBrigade.class));
        //cards.add(new SetCardInfo("Survey the Ruins", 35, Rarity.COMMON, mage.cards.s.SurveyTheRuins.class));
        //cards.add(new SetCardInfo("Travel Together", 36, Rarity.RARE, mage.cards.t.TravelTogether.class));
        //cards.add(new SetCardInfo("United in Survival", 37, Rarity.RARE, mage.cards.u.UnitedInSurvival.class));
        //cards.add(new SetCardInfo("Vaya's Subjugator", 38, Rarity.UNCOMMON, mage.cards.v.VayasSubjugator.class));
        //cards.add(new SetCardInfo("Wander the Ruins", 39, Rarity.COMMON, mage.cards.w.WanderTheRuins.class));
        //cards.add(new SetCardInfo("Antiquity Seeker", 40, Rarity.UNCOMMON, mage.cards.a.AntiquitySeeker.class));
        //cards.add(new SetCardInfo("Blind Wyvern", 41, Rarity.COMMON, mage.cards.b.BlindWyvern.class));
        //cards.add(new SetCardInfo("Brackcliff Drakes", 42, Rarity.COMMON, mage.cards.b.BrackcliffDrakes.class));
        //cards.add(new SetCardInfo("Crafted Exogene", 43, Rarity.COMMON, mage.cards.c.CraftedExogene.class));
        //cards.add(new SetCardInfo("Dust Enigma", 44, Rarity.UNCOMMON, mage.cards.d.DustEnigma.class));
        //cards.add(new SetCardInfo("Endtimes Monstrosity", 45, Rarity.COMMON, mage.cards.e.EndtimesMonstrosity.class));
        cards.add(new SetCardInfo("Essence Scatter", 46, Rarity.COMMON, mage.cards.e.EssenceScatter.class));
        //cards.add(new SetCardInfo("Eternal Wanderer", 47, Rarity.RARE, mage.cards.e.EternalWanderer.class));
        //cards.add(new SetCardInfo("Evaldi's Harmonizer", 48, Rarity.RARE, mage.cards.e.EvaldisHarmonizer.class));
        //cards.add(new SetCardInfo("Exogene Spitter", 49, Rarity.COMMON, mage.cards.e.ExogeneSpitter.class));
        //cards.add(new SetCardInfo("Geneshifter Adept", 50, Rarity.UNCOMMON, mage.cards.g.GeneshifterAdept.class));
        //cards.add(new SetCardInfo("Geneshifting", 51, Rarity.RARE, mage.cards.g.Geneshifting.class));
        //cards.add(new SetCardInfo("Getting Lost", 52, Rarity.COMMON, mage.cards.g.GettingLost.class));
        //cards.add(new SetCardInfo("Know the Way", 53, Rarity.COMMON, mage.cards.k.KnowTheWay.class));
        //cards.add(new SetCardInfo("Leave to the Sands", 54, Rarity.COMMON, mage.cards.l.LeaveToTheSands.class));
        //cards.add(new SetCardInfo("Leyline Feedback", 55, Rarity.COMMON, mage.cards.l.LeylineFeedback.class));
        //cards.add(new SetCardInfo("Leyline Router", 56, Rarity.COMMON, mage.cards.l.LeylineRouter.class));
        //cards.add(new SetCardInfo("Lore Investigator", 57, Rarity.COMMON, mage.cards.l.LoreInvestigator.class));
        //cards.add(new SetCardInfo("Mirage Oddity", 58, Rarity.RARE, mage.cards.m.MirageOddity.class));
        //cards.add(new SetCardInfo("Mysterious Undertaking", 59, Rarity.COMMON, mage.cards.m.MysteriousUndertaking.class));
        //cards.add(new SetCardInfo("Nimbus Drifters", 60, Rarity.UNCOMMON, mage.cards.n.NimbusDrifters.class));
        //cards.add(new SetCardInfo("Part Ways", 61, Rarity.UNCOMMON, mage.cards.p.PartWays.class));
        //cards.add(new SetCardInfo("Path of Caution", 62, Rarity.UNCOMMON, mage.cards.p.PathOfCaution.class));
        //cards.add(new SetCardInfo("Quintessence Manta", 63, Rarity.RARE, mage.cards.q.QuintessenceManta.class));
        //cards.add(new SetCardInfo("Relic Wayfarer", 64, Rarity.COMMON, mage.cards.r.RelicWayfarer.class));
        //cards.add(new SetCardInfo("Render Inert", 65, Rarity.RARE, mage.cards.r.RenderInert.class));
        //cards.add(new SetCardInfo("Ruin Scholar", 66, Rarity.COMMON, mage.cards.r.RuinScholar.class));
        //cards.add(new SetCardInfo("Sand Manipulator", 67, Rarity.COMMON, mage.cards.s.SandManipulator.class));
        //cards.add(new SetCardInfo("Sandwarp", 68, Rarity.RARE, mage.cards.s.Sandwarp.class));
        //cards.add(new SetCardInfo("Seawing Shrieker", 69, Rarity.COMMON, mage.cards.s.SeawingShrieker.class));
        //cards.add(new SetCardInfo("Secrets of the Sands", 70, Rarity.COMMON, mage.cards.s.SecretsOfTheSands.class));
        //cards.add(new SetCardInfo("Sephius, Reckless Scholar", 71, Rarity.MYTHIC, mage.cards.s.SephiusRecklessScholar.class));
        //cards.add(new SetCardInfo("Sephius's Research", 72, Rarity.UNCOMMON, mage.cards.s.SephiussResearch.class));
        //cards.add(new SetCardInfo("Sidetracked", 73, Rarity.UNCOMMON, mage.cards.s.Sidetracked.class));
        //cards.add(new SetCardInfo("Sink into Doubt", 74, Rarity.UNCOMMON, mage.cards.s.SinkIntoDoubt.class));
        //cards.add(new SetCardInfo("Umbral Glider", 75, Rarity.UNCOMMON, mage.cards.u.UmbralGlider.class));
        //cards.add(new SetCardInfo("Uneasy Encounter", 76, Rarity.UNCOMMON, mage.cards.u.UneasyEncounter.class));
        cards.add(new SetCardInfo("Unprecedented Genius", 77, Rarity.MYTHIC, mage.cards.u.UnprecedentedGenius.class));
        //cards.add(new SetCardInfo("Wall of Mysteries", 78, Rarity.UNCOMMON, mage.cards.w.WallOfMysteries.class));
        //cards.add(new SetCardInfo("Aethanis Undying", 79, Rarity.RARE, mage.cards.a.AethanisUndying.class));
        //cards.add(new SetCardInfo("Carrion Divers", 80, Rarity.UNCOMMON, mage.cards.c.CarrionDivers.class));
        //cards.add(new SetCardInfo("Consign to Failure", 81, Rarity.MYTHIC, mage.cards.c.ConsignToFailure.class));
        //cards.add(new SetCardInfo("Council of Vaya", 82, Rarity.UNCOMMON, mage.cards.c.CouncilOfVaya.class));
        //cards.add(new SetCardInfo("Doomed Temptation", 83, Rarity.RARE, mage.cards.d.DoomedTemptation.class));
        //cards.add(new SetCardInfo("Doomed Undertaking", 84, Rarity.COMMON, mage.cards.d.DoomedUndertaking.class));
        //cards.add(new SetCardInfo("Ego Collapse", 85, Rarity.COMMON, mage.cards.e.EgoCollapse.class));
        //cards.add(new SetCardInfo("Embraced by Dusk", 86, Rarity.COMMON, mage.cards.e.EmbracedByDusk.class));
        //cards.add(new SetCardInfo("Endtimes Steward", 87, Rarity.COMMON, mage.cards.e.EndtimesSteward.class));
        //cards.add(new SetCardInfo("Erode to Nothing", 88, Rarity.RARE, mage.cards.e.ErodeToNothing.class));
        //cards.add(new SetCardInfo("Fall Lurker", 89, Rarity.COMMON, mage.cards.f.FallLurker.class));
        //cards.add(new SetCardInfo("The Fall of Aethanis", 90, Rarity.RARE, mage.cards.t.TheFallOfAethanis.class));
        //cards.add(new SetCardInfo("Falltouched Emergence", 91, Rarity.UNCOMMON, mage.cards.f.FalltouchedEmergence.class));
        //cards.add(new SetCardInfo("Falltouched Predator", 92, Rarity.COMMON, mage.cards.f.FalltouchedPredator.class));
        cards.add(new SetCardInfo("Faultless Bloodhunter", 93, Rarity.COMMON, mage.cards.f.FaultlessBloodhunter.class));
        //cards.add(new SetCardInfo("Filth Swooper", 94, Rarity.UNCOMMON, mage.cards.f.FilthSwooper.class));
        //cards.add(new SetCardInfo("Foug, Indulgent Broker", 95, Rarity.MYTHIC, mage.cards.f.FougIndulgentBroker.class));
        //cards.add(new SetCardInfo("Foug's Quandary", 96, Rarity.UNCOMMON, mage.cards.f.FougsQuandary.class));
        //cards.add(new SetCardInfo("Gnoll Deathraider", 97, Rarity.COMMON, mage.cards.g.GnollDeathraider.class));
        //cards.add(new SetCardInfo("Grasp of the Fallen", 98, Rarity.COMMON, mage.cards.g.GraspOfTheFallen.class));
        //cards.add(new SetCardInfo("Grim Determination", 99, Rarity.COMMON, mage.cards.g.GrimDetermination.class));
        //cards.add(new SetCardInfo("Harvester of Vigor", 100, Rarity.COMMON, mage.cards.h.HarvesterOfVigor.class));
        //cards.add(new SetCardInfo("Hopeless Predicament", 101, Rarity.UNCOMMON, mage.cards.h.HopelessPredicament.class));
        //cards.add(new SetCardInfo("Inflict Torment", 102, Rarity.UNCOMMON, mage.cards.i.InflictTorment.class));
        //cards.add(new SetCardInfo("Lethal Dose", 103, Rarity.RARE, mage.cards.l.LethalDose.class));
        //cards.add(new SetCardInfo("Leyline Reaper", 104, Rarity.RARE, mage.cards.l.LeylineReaper.class));
        //cards.add(new SetCardInfo("Life Desecrator", 105, Rarity.COMMON, mage.cards.l.LifeDesecrator.class));
        //cards.add(new SetCardInfo("Malformed Rebirth", 106, Rarity.COMMON, mage.cards.m.MalformedRebirth.class));
        //cards.add(new SetCardInfo("Pursued Eremite", 107, Rarity.RARE, mage.cards.p.PursuedEremite.class));
        //cards.add(new SetCardInfo("Radaran Butcher", 108, Rarity.UNCOMMON, mage.cards.r.RadaranButcher.class));
        //cards.add(new SetCardInfo("Radaran Monstrosity", 109, Rarity.COMMON, mage.cards.r.RadaranMonstrosity.class));
        //cards.add(new SetCardInfo("Radaran Stirrings", 110, Rarity.UNCOMMON, mage.cards.r.RadaranStirrings.class));
        //cards.add(new SetCardInfo("Rayak, Radaran Overlord", 111, Rarity.RARE, mage.cards.r.RayakRadaranOverlord.class));
        //cards.add(new SetCardInfo("Rayak's Prelate", 112, Rarity.UNCOMMON, mage.cards.r.RayaksPrelate.class));
        //cards.add(new SetCardInfo("Resilient Raiders", 113, Rarity.UNCOMMON, mage.cards.r.ResilientRaiders.class));
        //cards.add(new SetCardInfo("Shi-Fang Bandits", 114, Rarity.COMMON, mage.cards.s.ShiFangBandits.class));
        //cards.add(new SetCardInfo("Supply Raid", 115, Rarity.UNCOMMON, mage.cards.s.SupplyRaid.class));
        //cards.add(new SetCardInfo("Twilight Screechers", 116, Rarity.COMMON, mage.cards.t.TwilightScreechers.class));
        //cards.add(new SetCardInfo("Warped Worshipper", 117, Rarity.COMMON, mage.cards.w.WarpedWorshipper.class));
        //cards.add(new SetCardInfo("Wither Away", 118, Rarity.COMMON, mage.cards.w.WitherAway.class));
        //cards.add(new SetCardInfo("Ashen Dunekite", 119, Rarity.UNCOMMON, mage.cards.a.AshenDunekite.class));
        cards.add(new SetCardInfo("Blood Feud", 120, Rarity.UNCOMMON, mage.cards.b.BloodFeud.class));
        cards.add(new SetCardInfo("Bloodrage Brawler", 121, Rarity.UNCOMMON, mage.cards.b.BloodrageBrawler.class));
        //cards.add(new SetCardInfo("Claim What Remains", 122, Rarity.RARE, mage.cards.c.ClaimWhatRemains.class));
        //cards.add(new SetCardInfo("Dereliction", 123, Rarity.COMMON, mage.cards.d.Dereliction.class));
        //cards.add(new SetCardInfo("Dustborn Phoenix", 124, Rarity.RARE, mage.cards.d.DustbornPhoenix.class));
        //cards.add(new SetCardInfo("Endtimes Hunter", 125, Rarity.COMMON, mage.cards.e.EndtimesHunter.class));
        //cards.add(new SetCardInfo("Gnoll Raidleaders", 126, Rarity.UNCOMMON, mage.cards.g.GnollRaidleaders.class));
        //cards.add(new SetCardInfo("Gnoll Ravager", 127, Rarity.COMMON, mage.cards.g.GnollRavager.class));
        //cards.add(new SetCardInfo("Goresand Marauder", 128, Rarity.COMMON, mage.cards.g.GoresandMarauder.class));
        cards.add(new SetCardInfo("Goresand Wardriver", 129, Rarity.COMMON, mage.cards.g.GoresandWardriver.class));
        //cards.add(new SetCardInfo("Grin, Scourge of Goresand", 130, Rarity.RARE, mage.cards.g.GrinScourgeOfGoresand.class));
        //cards.add(new SetCardInfo("Grin's Reaver", 131, Rarity.RARE, mage.cards.g.GrinsReaver.class));
        //cards.add(new SetCardInfo("Hateseer Elder", 132, Rarity.UNCOMMON, mage.cards.h.HateseerElder.class));
        //cards.add(new SetCardInfo("Hostile Undertaking", 133, Rarity.COMMON, mage.cards.h.HostileUndertaking.class));
        //cards.add(new SetCardInfo("Huntscent Pillagers", 134, Rarity.COMMON, mage.cards.h.HuntscentPillagers.class));
        //cards.add(new SetCardInfo("Incandescent Rain", 135, Rarity.UNCOMMON, mage.cards.i.IncandescentRain.class));
        //cards.add(new SetCardInfo("Insistent Lightning", 136, Rarity.RARE, mage.cards.i.InsistentLightning.class));
        //cards.add(new SetCardInfo("Instincts of the Pack", 137, Rarity.RARE, mage.cards.i.InstinctsOfThePack.class));
        //cards.add(new SetCardInfo("Luma's Acolyte", 138, Rarity.UNCOMMON, mage.cards.l.LumasAcolyte.class));
        //cards.add(new SetCardInfo("Marauder's Fire", 139, Rarity.COMMON, mage.cards.m.MaraudersFire.class));
        //cards.add(new SetCardInfo("The Pack Feasts", 140, Rarity.COMMON, mage.cards.t.ThePackFeasts.class));
        //cards.add(new SetCardInfo("Path of Brutality", 141, Rarity.UNCOMMON, mage.cards.p.PathOfBrutality.class));
        //cards.add(new SetCardInfo("Plunder and Maim", 142, Rarity.COMMON, mage.cards.p.PlunderAndMaim.class));
        //cards.add(new SetCardInfo("Rabid Whelps", 143, Rarity.UNCOMMON, mage.cards.r.RabidWhelps.class));
        //cards.add(new SetCardInfo("Radaran Pioneer", 144, Rarity.COMMON, mage.cards.r.RadaranPioneer.class));
        //cards.add(new SetCardInfo("Raid Preparations", 145, Rarity.UNCOMMON, mage.cards.r.RaidPreparations.class));
        //cards.add(new SetCardInfo("Raider's Loyalty", 146, Rarity.COMMON, mage.cards.r.RaidersLoyalty.class));
        //cards.add(new SetCardInfo("Ransack and Burn", 147, Rarity.COMMON, mage.cards.r.RansackAndBurn.class));
        //cards.add(new SetCardInfo("Regard the Remnants", 148, Rarity.COMMON, mage.cards.r.RegardTheRemnants.class));
        //cards.add(new SetCardInfo("Rubble Messenger", 149, Rarity.COMMON, mage.cards.r.RubbleMessenger.class));
        //cards.add(new SetCardInfo("Sandscald", 150, Rarity.UNCOMMON, mage.cards.s.Sandscald.class));
        //cards.add(new SetCardInfo("Scrapfire Technician", 151, Rarity.UNCOMMON, mage.cards.s.ScrapfireTechnician.class));
        //cards.add(new SetCardInfo("Shi-Fang Ambusher", 152, Rarity.COMMON, mage.cards.s.ShiFangAmbusher.class));
        //cards.add(new SetCardInfo("Shimmering Dunekite", 153, Rarity.MYTHIC, mage.cards.s.ShimmeringDunekite.class));
        //cards.add(new SetCardInfo("Sunflare Dragon", 154, Rarity.RARE, mage.cards.s.SunflareDragon.class));
        //cards.add(new SetCardInfo("Territorial Sandshark", 155, Rarity.COMMON, mage.cards.t.TerritorialSandshark.class));
        //cards.add(new SetCardInfo("Warpath Minotaur", 156, Rarity.RARE, mage.cards.w.WarpathMinotaur.class));
        //cards.add(new SetCardInfo("Way of the Raider", 157, Rarity.COMMON, mage.cards.w.WayOfTheRaider.class));
        //cards.add(new SetCardInfo("Bitter Redemption", 158, Rarity.RARE, mage.cards.b.BitterRedemption.class));
        //cards.add(new SetCardInfo("Consumption Tyrant", 159, Rarity.RARE, mage.cards.c.ConsumptionTyrant.class));
        //cards.add(new SetCardInfo("Debris Surveyors", 160, Rarity.COMMON, mage.cards.d.DebrisSurveyors.class));
        //cards.add(new SetCardInfo("Desperate Animist", 161, Rarity.COMMON, mage.cards.d.DesperateAnimist.class));
        //cards.add(new SetCardInfo("Endtimes Pilgrim", 162, Rarity.COMMON, mage.cards.e.EndtimesPilgrim.class));
        //cards.add(new SetCardInfo("Evaldi, Genesis of Hope", 163, Rarity.RARE, mage.cards.e.EvaldiGenesisOfHope.class));
        //cards.add(new SetCardInfo("Evaldi's Masterpiece", 164, Rarity.MYTHIC, mage.cards.e.EvaldisMasterpiece.class));
        //cards.add(new SetCardInfo("Evaldi's Search", 165, Rarity.UNCOMMON, mage.cards.e.EvaldisSearch.class));
        //cards.add(new SetCardInfo("Exiled Channeler", 166, Rarity.COMMON, mage.cards.e.ExiledChanneler.class));
        //cards.add(new SetCardInfo("Exogene Prowler", 167, Rarity.UNCOMMON, mage.cards.e.ExogeneProwler.class));
        //cards.add(new SetCardInfo("Falltouched Hunger", 168, Rarity.COMMON, mage.cards.f.FalltouchedHunger.class));
        //cards.add(new SetCardInfo("Fluorescent Sprinter", 169, Rarity.UNCOMMON, mage.cards.f.FluorescentSprinter.class));
        //cards.add(new SetCardInfo("Gene Gorger", 170, Rarity.COMMON, mage.cards.g.GeneGorger.class));
        //cards.add(new SetCardInfo("Geneshifted Goliath", 171, Rarity.UNCOMMON, mage.cards.g.GeneshiftedGoliath.class));
        //cards.add(new SetCardInfo("Geneshifted Warbler", 172, Rarity.UNCOMMON, mage.cards.g.GeneshiftedWarbler.class));
        //cards.add(new SetCardInfo("Grievous Confrontation", 173, Rarity.UNCOMMON, mage.cards.g.GrievousConfrontation.class));
        cards.add(new SetCardInfo("Horizon Eater", 174, Rarity.COMMON, mage.cards.h.HorizonEater.class));
        //cards.add(new SetCardInfo("Hunter's Tenacity", 175, Rarity.COMMON, mage.cards.h.HuntersTenacity.class));
        //cards.add(new SetCardInfo("Laggu Outrider", 176, Rarity.COMMON, mage.cards.l.LagguOutrider.class));
        //cards.add(new SetCardInfo("Landscape Decay", 177, Rarity.UNCOMMON, mage.cards.l.LandscapeDecay.class));
        //cards.add(new SetCardInfo("Leyline Feeder", 178, Rarity.RARE, mage.cards.l.LeylineFeeder.class));
        //cards.add(new SetCardInfo("Lost in the Past", 179, Rarity.UNCOMMON, mage.cards.l.LostInThePast.class));
        cards.add(new SetCardInfo("Market Festival", 180, Rarity.COMMON, mage.cards.m.MarketFestival.class));
        //cards.add(new SetCardInfo("Plated Charger", 181, Rarity.UNCOMMON, mage.cards.p.PlatedCharger.class));
        //cards.add(new SetCardInfo("Radaran Hunter", 182, Rarity.COMMON, mage.cards.r.RadaranHunter.class));
        //cards.add(new SetCardInfo("Radaran Reclaimer", 183, Rarity.UNCOMMON, mage.cards.r.RadaranReclaimer.class));
        //cards.add(new SetCardInfo("Reduce to Earth", 184, Rarity.COMMON, mage.cards.r.ReduceToEarth.class));
        //cards.add(new SetCardInfo("Sandstalker Duo", 185, Rarity.UNCOMMON, mage.cards.s.SandstalkerDuo.class));
        //cards.add(new SetCardInfo("Sandtrap Spider", 186, Rarity.COMMON, mage.cards.s.SandtrapSpider.class));
        //cards.add(new SetCardInfo("Savage Undertaking", 187, Rarity.COMMON, mage.cards.s.SavageUndertaking.class));
        //cards.add(new SetCardInfo("Skytouch Wurm", 188, Rarity.UNCOMMON, mage.cards.s.SkytouchWurm.class));
        //cards.add(new SetCardInfo("Stampeding Orvs", 189, Rarity.RARE, mage.cards.s.StampedingOrvs.class));
        //cards.add(new SetCardInfo("Struggle for Survival", 190, Rarity.RARE, mage.cards.s.StruggleForSurvival.class));
        //cards.add(new SetCardInfo("Twisted Endurance", 191, Rarity.COMMON, mage.cards.t.TwistedEndurance.class));
        //cards.add(new SetCardInfo("Valley Carver", 192, Rarity.COMMON, mage.cards.v.ValleyCarver.class));
        //cards.add(new SetCardInfo("Wayfarer's Destination", 193, Rarity.COMMON, mage.cards.w.WayfarersDestination.class));
        //cards.add(new SetCardInfo("Wurm's Wake", 194, Rarity.MYTHIC, mage.cards.w.WurmsWake.class));
        //cards.add(new SetCardInfo("Zerul Beastdriver", 195, Rarity.RARE, mage.cards.z.ZerulBeastdriver.class));
        //cards.add(new SetCardInfo("Zerul Mangler", 196, Rarity.COMMON, mage.cards.z.ZerulMangler.class));
        //cards.add(new SetCardInfo("Biramous Entity", 197, Rarity.RARE, mage.cards.b.BiramousEntity.class));
        //cards.add(new SetCardInfo("Claim of the Fallen", 198, Rarity.RARE, mage.cards.c.ClaimOfTheFallen.class));
        //cards.add(new SetCardInfo("Deathraider Elite", 199, Rarity.UNCOMMON, mage.cards.d.DeathraiderElite.class));
        //cards.add(new SetCardInfo("Dusk Dancer", 200, Rarity.UNCOMMON, mage.cards.d.DuskDancer.class));
        //cards.add(new SetCardInfo("Find of a Lifetime", 201, Rarity.RARE, mage.cards.f.FindOfALifetime.class));
        //cards.add(new SetCardInfo("Growthblazers", 202, Rarity.UNCOMMON, mage.cards.g.Growthblazers.class));
        cards.add(new SetCardInfo("Irradiated Amalgam", 203, Rarity.UNCOMMON, mage.cards.i.IrradiatedAmalgam.class));
        //cards.add(new SetCardInfo("Luma, Guiding Star", 204, Rarity.MYTHIC, mage.cards.l.LumaGuidingStar.class));
        //cards.add(new SetCardInfo("Manta Wrangler", 205, Rarity.UNCOMMON, mage.cards.m.MantaWrangler.class));
        //cards.add(new SetCardInfo("Naomi, Pathleader", 206, Rarity.MYTHIC, mage.cards.n.NaomiPathleader.class));
        //cards.add(new SetCardInfo("Nivia, Last of the Aethanis", 207, Rarity.MYTHIC, mage.cards.n.NiviaLastOfTheAethanis.class));
        //cards.add(new SetCardInfo("Nivia's Safekeeper", 208, Rarity.UNCOMMON, mage.cards.n.NiviasSafekeeper.class));
        //cards.add(new SetCardInfo("Preacher of the Faultless", 209, Rarity.UNCOMMON, mage.cards.p.PreacherOfTheFaultless.class));
        //cards.add(new SetCardInfo("Raid Veteran", 210, Rarity.UNCOMMON, mage.cards.r.RaidVeteran.class));
        //cards.add(new SetCardInfo("Realm Siphoner", 211, Rarity.RARE, mage.cards.r.RealmSiphoner.class));
        //cards.add(new SetCardInfo("Revel in Perfection", 212, Rarity.RARE, mage.cards.r.RevelInPerfection.class));
        //cards.add(new SetCardInfo("Ruinstorm Wurm", 213, Rarity.RARE, mage.cards.r.RuinstormWurm.class));
        //cards.add(new SetCardInfo("Settlement Convoy", 214, Rarity.UNCOMMON, mage.cards.s.SettlementConvoy.class));
        //cards.add(new SetCardInfo("Unbridled Antoch", 215, Rarity.UNCOMMON, mage.cards.u.UnbridledAntoch.class));
        //cards.add(new SetCardInfo("Vaya, Arbiter of Perfection", 216, Rarity.MYTHIC, mage.cards.v.VayaArbiterOfPerfection.class));
        //cards.add(new SetCardInfo("Vlad-Shi, Packmother", 217, Rarity.MYTHIC, mage.cards.v.VladShiPackmother.class));
        //cards.add(new SetCardInfo("Abandoned Astrolabe", 218, Rarity.UNCOMMON, mage.cards.a.AbandonedAstrolabe.class));
        //cards.add(new SetCardInfo("Aethanis Conservator", 219, Rarity.RARE, mage.cards.a.AethanisConservator.class));
        //cards.add(new SetCardInfo("Aethanis Leylinker", 220, Rarity.UNCOMMON, mage.cards.a.AethanisLeylinker.class));
        //cards.add(new SetCardInfo("Aethanis Sentinel", 221, Rarity.COMMON, mage.cards.a.AethanisSentinel.class));
        cards.add(new SetCardInfo("Aethanis Strider", 222, Rarity.COMMON, mage.cards.a.AethanisStrider.class));
        //cards.add(new SetCardInfo("Aether Conducter", 223, Rarity.RARE, mage.cards.a.AetherConducter.class));
        //cards.add(new SetCardInfo("Enigmatic Constructor", 224, Rarity.RARE, mage.cards.e.EnigmaticConstructor.class));
        //cards.add(new SetCardInfo("Eon Overwatch", 225, Rarity.RARE, mage.cards.e.EonOverwatch.class));
        //cards.add(new SetCardInfo("Eradicator Engine", 226, Rarity.RARE, mage.cards.e.EradicatorEngine.class));
        //cards.add(new SetCardInfo("Flareshot Bow", 227, Rarity.COMMON, mage.cards.f.FlareshotBow.class));
        //cards.add(new SetCardInfo("Liminal Observer", 228, Rarity.RARE, mage.cards.l.LiminalObserver.class));
        //cards.add(new SetCardInfo("Pathfinder's Tools", 229, Rarity.COMMON, mage.cards.p.PathfindersTools.class));
        //cards.add(new SetCardInfo("The Source", 230, Rarity.MYTHIC, mage.cards.t.TheSource.class));
        //cards.add(new SetCardInfo("Source Conduits", 231, Rarity.UNCOMMON, mage.cards.s.SourceConduits.class));
        //cards.add(new SetCardInfo("Source Sentries", 232, Rarity.UNCOMMON, mage.cards.s.SourceSentries.class));
        //cards.add(new SetCardInfo("Stasis Enforcer", 233, Rarity.UNCOMMON, mage.cards.s.StasisEnforcer.class));
        //cards.add(new SetCardInfo("Survival Gear", 234, Rarity.COMMON, mage.cards.s.SurvivalGear.class));
        //cards.add(new SetCardInfo("Timeless Custodian", 235, Rarity.COMMON, mage.cards.t.TimelessCustodian.class));
        //cards.add(new SetCardInfo("Unstable Relic", 236, Rarity.COMMON, mage.cards.u.UnstableRelic.class));
        //cards.add(new SetCardInfo("Abandoned Excavation", 237, Rarity.UNCOMMON, mage.cards.a.AbandonedExcavation.class));
        //cards.add(new SetCardInfo("Aethanis, the Fallen Capital", 238, Rarity.RARE, mage.cards.a.AethanisTheFallenCapital.class));
        //cards.add(new SetCardInfo("Ancient Shelter", 239, Rarity.RARE, mage.cards.a.AncientShelter.class));
        cards.add(new SetCardInfo("Buried Ruin", 240, Rarity.UNCOMMON, mage.cards.b.BuriedRuin.class));
        cards.add(new SetCardInfo("Field of Ruin", 241, Rarity.UNCOMMON, mage.cards.f.FieldOfRuin.class));
        //cards.add(new SetCardInfo("Fractured Remnant", 242, Rarity.RARE, mage.cards.f.FracturedRemnant.class));
        cards.add(new SetCardInfo("Holdout Settlement", 243, Rarity.COMMON, mage.cards.h.HoldoutSettlement.class));
        //cards.add(new SetCardInfo("Malign Outskirts", 244, Rarity.UNCOMMON, mage.cards.m.MalignOutskirts.class));
        //cards.add(new SetCardInfo("Neglected Nexus", 245, Rarity.COMMON, mage.cards.n.NeglectedNexus.class));
        //cards.add(new SetCardInfo("Starved Oasis", 246, Rarity.RARE, mage.cards.s.StarvedOasis.class));
        //cards.add(new SetCardInfo("Twilight Depths", 247, Rarity.COMMON, mage.cards.t.TwilightDepths.class));
        cards.add(new SetCardInfo("Wastes", 248, Rarity.COMMON, mage.cards.w.Wastes.class, FULL_ART_BFZ));
        cards.add(new SetCardInfo("Plains", 249, Rarity.LAND, mage.cards.basiclands.Plains.class));
        cards.add(new SetCardInfo("Island", 250, Rarity.LAND, mage.cards.basiclands.Island.class));
        cards.add(new SetCardInfo("Swamp", 251, Rarity.LAND, mage.cards.basiclands.Swamp.class));
        cards.add(new SetCardInfo("Mountain", 252, Rarity.LAND, mage.cards.basiclands.Mountain.class));
        cards.add(new SetCardInfo("Forest", 253, Rarity.LAND, mage.cards.basiclands.Forest.class));
    }
}
